#!/usr/bin/env python3
"""One-shot generator for gfx/map/fleet_entities/02_extra_fleet_entities.txt.

Extracts vanilla fleet_entity blocks from vic3's 01_fleet_entities.txt and
emits clones for each mod ship_type, performing only the two key
substitutions documented in GitHub issue #120:
  - top-level key (e.g. `ship_type_destroyer = {` -> `ship_type_asw_destroyer = {`)
  - inner `ship_type = ship_type_destroyer` -> `ship_type = ship_type_asw_destroyer`
Every other line (entity, vfx_entity, attach, locator, damage_decal_positions)
is preserved verbatim so the new ship_types render with vanilla 3D assets.

Run from repo root: `python3 scripts/generators/gen_fleet_entities.py`.
Re-run safe: overwrites the output file in place.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))
from path_constants import mod_path, vanilla_source_repo_path  # noqa: E402

VANILLA = (
    Path(vanilla_source_repo_path) / "game" / "gfx" / "map" / "fleet_entities" / "01_fleet_entities.txt"
)
OUT = Path(mod_path) / "gfx" / "map" / "fleet_entities" / "02_extra_fleet_entities.txt"

# (mod_ship_type, vanilla_template_block) — per #120 mapping + plan judgments
SHIPS = [
    ("ship_type_asw_destroyer",                          "ship_type_destroyer"),
    ("ship_type_guided_missile_ship",                    "ship_type_destroyer"),
    ("ship_type_pulsed_laser_escort",                    "ship_type_destroyer"),
    ("ship_type_nuclear_submarine",                      "ship_type_submarine"),
    ("ship_type_stealth_attack_submarine",               "ship_type_submarine"),
    ("ship_type_autonomous_swarm_submarine",             "ship_type_submarine"),
    ("ship_type_nuclear_supercarrier",                   "ship_type_aircraft_carrier"),
    ("ship_type_fleet_carrier",                          "ship_type_aircraft_carrier"),
    ("ship_type_arsenal_ship",                           "ship_type_super_dreadnought"),
    ("ship_type_antimatter_battleship",                  "ship_type_super_dreadnought"),
    ("ship_type_hypersonic_missile_platform",            "ship_type_super_dreadnought"),
    ("ship_type_stealth_battlecruiser",                  "ship_type_dreadnought"),
    ("ship_type_networked_air_defense_cruiser",          "ship_type_light_cruiser"),
    ("ship_type_swarm_coordination_vessel",              "ship_type_light_cruiser"),
    ("ship_type_amphibious_assault_ship",                "ship_type_troop_ship"),
    ("ship_type_marine_assault_ship",                    "ship_type_troop_ship"),
    ("ship_type_expeditionary_sea_base",                 "ship_type_troop_ship"),
    ("ship_type_expeditionary_fast_transport",           "ship_type_troop_ship"),
    ("ship_type_orbital_support_amphibious_mothership",  "ship_type_troop_ship"),
]

TEMPLATE_FAMILIES = {
    "ship_type_destroyer":         "Destroyer-class escorts",
    "ship_type_submarine":         "Submarines",
    "ship_type_aircraft_carrier":  "Aircraft carriers",
    "ship_type_super_dreadnought": "Capital ships (super-dreadnought template)",
    "ship_type_dreadnought":       "Battlecruisers (dreadnought template)",
    "ship_type_light_cruiser":     "Light cruisers / coordination vessels",
    "ship_type_troop_ship":        "Amphibious / troop ships",
}


def extract_block(text: str, key: str) -> str:
    pattern = re.compile(rf"^{re.escape(key)}\s*=\s*\{{", re.MULTILINE)
    m = pattern.search(text)
    if not m:
        sys.exit(f"could not find vanilla block: {key}")
    depth = 0
    i = m.end() - 1
    while i < len(text):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[m.start():i + 1]
        i += 1
    sys.exit(f"unterminated block: {key}")


def rekey(block: str, old: str, new: str) -> str:
    out = re.sub(
        rf"^{re.escape(old)}(\s*=\s*\{{)",
        f"{new}\\1",
        block,
        count=1,
        flags=re.MULTILINE,
    )
    out = re.sub(
        rf"(^\s*ship_type\s*=\s*){re.escape(old)}\b",
        f"\\1{new}",
        out,
        count=1,
        flags=re.MULTILINE,
    )
    return out


def main() -> None:
    vanilla_text = VANILLA.read_text(encoding="utf-8-sig")

    needed = sorted({tpl for _, tpl in SHIPS})
    cache = {tpl: extract_block(vanilla_text, tpl) for tpl in needed}

    parts = [
        "###################################################################\n"
        "### Mod-added ship fleet_entity bindings (GitHub issue #120).\n"
        "###\n"
        "### AUTO-GENERATED by scripts/generators/gen_fleet_entities.py.\n"
        "### Do not edit manually — re-run the generator after changing\n"
        "### the SHIPS table or after a vanilla 1.X bump.\n"
        "###\n"
        "### Each block below is a verbatim copy of the named vanilla\n"
        "### fleet_entity from gfx/map/fleet_entities/01_fleet_entities.txt,\n"
        "### with only the top-level key and inner `ship_type =` line\n"
        "### changed to the mod ship_type ID. Every entity, vfx_entity,\n"
        "### attach, damage_decal_positions, and locator field is\n"
        "### unchanged so the new ship_types render using vanilla 3D\n"
        "### assets they reference.\n"
        "###\n"
        "### Authoring original 3D ship art is out of scope (Paradox's\n"
        "### .mesh format is proprietary with no public exporter).\n"
        "###################################################################\n"
    ]

    last_family = None
    for new, old in SHIPS:
        family = TEMPLATE_FAMILIES[old]
        if family != last_family:
            parts.append(f"\n# ===== {family} (clones of {old}) =====\n")
            last_family = family
        parts.append("")
        parts.append(rekey(cache[old], old, new))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8-sig")  # emit Paradox BOM
    line_count = OUT.read_text(encoding="utf-8-sig").count("\n")
    print(f"wrote {OUT} ({line_count} lines, {len(SHIPS)} ship blocks)")


if __name__ == "__main__":
    main()
