"""Generate the power bloc principle slot code that names every principle.

A bloc has te_pb_principle_slot_cap principle slots (common/script_values/
te_power_bloc_principle_slot_values.txt). Two pieces of that system have to list
every principle, so this writes them:

* common/power_bloc_principles/te_principle_slot_gates_generated.txt:
  ``INJECT:<principle> = { possible = { te_pb_principle_slot_free = { GROUP = <group> } } }``
  for each vanilla principle the mod doesn't define, REPLACE or INJECT. That
  trigger (common/scripted_triggers/te_power_bloc_principle_slot_triggers.txt)
  holds the AI to the slot count. A principle the mod defines, REPLACEs or
  INJECTs carries the line in its own block instead, because an INJECT on a
  mod-defined principle is dropped and two INJECTs on one entity are untested.
  A vanilla principle with its own ``possible`` can't take the INJECT (it would
  get a second ``possible``), so it is an error until the mod REPLACEs it, as
  extra_power_bloc_principles.txt does for principle_freedom_of_movement_1.
* common/scripted_effects/te_pb_remove_principle_generated.txt:
  te_pb_remove_principle_in_scope, one branch per principle. remove_principle
  takes only a literal key (a scope fails PostValidate and logs "Power bloc
  principle provided is invalid"), so the panel's remove button compares
  scope:te_principle with each principle and removes it by key.

Only principles listed in a group's ``levels`` count: nothing else can be
selected (the mod's Sacred Civics REPLACE leaves vanilla's three tiers out).

Inputs: principles and principle groups (vanilla snapshot + mod). Run
``python3 scripts/generators/gen_pb_principle_slots.py [--dry-run | --check]``.
No game install or running server is needed. Not run on /reload;
test_pb_principle_slots.py fails CI when the committed files are stale.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

PRINCIPLES_DIR = Path("common/power_bloc_principles")
GATES_OUT = PRINCIPLES_DIR / "te_principle_slot_gates_generated.txt"
REMOVE_OUT = Path("common/scripted_effects/te_pb_remove_principle_generated.txt")

HEADER = "# AUTO-GENERATED by scripts/generators/gen_pb_principle_slots.py - do not edit manually.\n"

GATES_PREAMBLE = """\
# Holds the AI to its bloc's principle slot count (te_pb_principle_slot_free,
# common/scripted_triggers/te_power_bloc_principle_slot_triggers.txt) on every
# vanilla principle the mod doesn't define, REPLACE or INJECT. Principles the
# mod does touch carry the same line in their own `possible`.
"""

REMOVE_PREAMBLE = """\
# Scope: power bloc. scope:te_principle is the principle to remove; the panel's
# remove button (te_pb_remove_principle_sgui) passes it. remove_principle takes
# only a literal key, so each principle is compared and removed by name.
"""

ENTITY_RE = re.compile(r"^((?:REPLACE:|INJECT:)?)(principle_\w+)\s*=\s*\{", re.M)

ENTITY_TYPES = ("Principles", "Principle Groups")


def load_state(root: Path = ROOT):
    """Principles and principle groups: vanilla from the committed snapshot, mod from disk."""
    from mod_state import VANILLA_COMMON_DIRS, ModState
    from vanilla_parsed import load

    snapshot = load(str(root / "vanilla_parsed"))
    state = ModState(
        {kind: "/nonexistent" for kind in ENTITY_TYPES},
        {kind: str(root / "common" / VANILLA_COMMON_DIRS[kind]) for kind in ENTITY_TYPES},
        vanilla_data=snapshot.data,
    )
    if state.parse_failures:
        raise ValueError(f"Cannot generate principle slot code from an incomplete parse: {state.parse_failures}")
    return state, snapshot.data


def _unwrap(v):
    if isinstance(v, (list, tuple)) and len(v) == 2 and isinstance(v[0], str):
        return v[1]
    return v


def _levels(group) -> list[str]:
    out: list[str] = []

    def walk(v):
        v = _unwrap(v)
        if isinstance(v, str):
            out.append(v)
        elif isinstance(v, (list, tuple)):
            for x in v:
                walk(x)

    walk(_unwrap(group).get("levels"))
    return out


def grouped_principles(mod_state) -> list[tuple[str, str]]:
    """(principle, group) for every principle a group lists, by group then tier."""
    groups = mod_state.get_data("Principle Groups") or {}
    rows = []
    for group in sorted(groups):
        rows.extend((principle, group) for principle in _levels(groups[group]))
    return rows


def mod_touched(root: Path = ROOT) -> set[str]:
    """Principles the mod defines, REPLACEs or INJECTs, outside this generator's output."""
    names = set()
    for path in sorted((root / PRINCIPLES_DIR).glob("*.txt")):
        if path.name == GATES_OUT.name:
            continue
        names.update(m.group(2) for m in ENTITY_RE.finditer(path.read_text(encoding="utf-8-sig")))
    return names


def gate_targets(rows, vanilla_principles: dict, touched: set[str]) -> list[tuple[str, str]]:
    """The vanilla principles the generated file gates; raises on one it can't."""
    targets, blocked = [], []
    for principle, group in rows:
        if principle in touched or principle not in vanilla_principles:
            continue
        if "possible" in _unwrap(vanilla_principles[principle]):
            blocked.append(principle)
        else:
            targets.append((principle, group))
    if blocked:
        raise ValueError(
            "Vanilla gives these principles their own `possible`, so an INJECT would add a second one: "
            f"{', '.join(blocked)}. REPLACE them in extra_power_bloc_principles.txt with "
            "te_pb_principle_slot_free added to their `possible`."
        )
    return targets


def render_gate(principle: str, group: str) -> str:
    return (
        f"INJECT:{principle} = {{\n"
        "\tpossible = {\n"
        f"\t\tte_pb_principle_slot_free = {{ GROUP = {group} }}\n"
        "\t}\n"
        "}\n"
    )


def render_remove(rows) -> str:
    branches = []
    for i, (principle, _group) in enumerate(rows):
        keyword = "if" if i == 0 else "else_if"
        branches.append(
            f"\t{keyword} = {{\n"
            f"\t\tlimit = {{ scope:te_principle ?= principle:{principle} }}\n"
            f"\t\tremove_principle = {principle}\n"
            "\t}\n"
        )
    return "te_pb_remove_principle_in_scope = {\n" + "".join(branches) + "}\n"


def plan_outputs(mod_state, vanilla_data: dict, root: Path = ROOT) -> dict[Path, str]:
    rows = grouped_principles(mod_state)
    targets = gate_targets(rows, vanilla_data.get("Principles") or {}, mod_touched(root))
    gates = HEADER + GATES_PREAMBLE + "".join("\n" + render_gate(p, g) for p, g in targets)
    remove = HEADER + REMOVE_PREAMBLE + "\n" + render_remove(rows)
    return {GATES_OUT: gates, REMOVE_OUT: remove}


def regenerate(*, root: Path = ROOT, dry_run: bool = False) -> dict:
    """Write each output whose content changed, with one UTF-8 BOM."""
    mod_state, vanilla_data = load_state(root)
    changed = []
    for relative, text in plan_outputs(mod_state, vanilla_data, root).items():
        target = root / relative
        expected = text.encode("utf-8-sig")
        if not target.exists() or target.read_bytes() != expected:
            changed.append(str(relative))
            if not dry_run:
                target.write_bytes(expected)
    return {"changed": bool(changed), "changed_files": changed}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true", help="report what would change; write nothing")
    mode.add_argument("--check", action="store_true", help="exit 1 if any output is stale")
    args = parser.parse_args()
    result = regenerate(dry_run=args.dry_run or args.check)
    verb = "stale" if args.check else "would write" if args.dry_run else "wrote"
    for path in result["changed_files"]:
        print(f"{verb}: {path}")
    if not result["changed"]:
        print("principle slot code: current")
    return int(args.check and result["changed"])


if __name__ == "__main__":
    raise SystemExit(main())
