#!/usr/bin/env python3
"""Generate the legislated tax code's rate amendments, script values and loc.

The tax code (docs/superpowers/specs/2026-09-29-legislated-tax-code-design.md)
holds each tax instrument as an integer index: rate = index x step. The carrier
law `law_te_tax_code` collects nothing; one generated amendment per instrument
and index carries the rate, identical in all five native tax levels so that a
level change moves only the political static modifier. INSTRUMENTS below is the
single source of truth for that table; MIGRATION, for the rates each vanilla
taxation law sets at each native level.

Outputs (each is registered in OUTPUTS and written byte for byte):

  common/amendments/te_tax_amendments_generated.txt
      amendment_te_tax_<key>_<idx> for every instrument and every idx 1..max.
  common/script_values/te_tax_generated_values.txt
      te_tax_step_<key>, te_tax_max_<key> and te_tax_pct_step_<key> constants,
      and te_tax_slot_id_<slot> for the history ring.
  localization/english/te_tax_generated_l_english.yml
      A name and a _desc per amendment. organize_loc.py files these keys here
      (category TAX_GENERATED) and renders the file itself, so this script
      renders through organize_loc and the two always agree.
  common/scripted_effects/te_tax_generated_effects.txt
      The collection writer's per-instrument and per-good parts
      (te_tax_gen_sync_<key>, te_tax_gen_sync_goods), the initialiser's
      (te_tax_gen_init_instruments, te_tax_gen_init_goods,
      te_tax_gen_init_schedule) and the scheduler's (te_tax_gen_sunset_<key>,
      te_tax_gen_commence/hold_missed/apply/store_<slot>, te_tax_gen_next_month,
      te_tax_gen_history_write) and the migration's (te_tax_gen_migrate_rates,
      one branch per vanilla taxation law and native level from MIGRATION;
      te_tax_gen_migrate_goods; te_tax_gen_migrate_provisions).
  common/scripted_triggers/te_tax_generated_triggers.txt
      Amendment-scope family and match triggers the syncs filter on, the
      scheduler's package and bill checks (te_tax_gen_package_current_<slot>,
      te_tax_gen_package_touches_goods_<slot>, te_tax_gen_bill_sunsets_valid)
      and the draft and bill checks (te_tax_gen_draft_touches_any/_goods,
      te_tax_gen_bill_touches_goods, te_tax_gen_draft_baseline_current,
      te_tax_gen_draft_differs_from_bill, te_tax_gen_bill_current,
      te_tax_gen_bill_small_steps, te_tax_gen_bill_overlaps_<slot>,
      te_tax_gen_package_empty_<slot>, te_tax_gen_package_unsuperseded_<slot>).
  common/scripted_effects/te_tax_generated_bill_effects.txt
      The draft, bill and passage parts (te_tax_gen_draft_init/_from_bill/
      _clear, te_tax_gen_bill_from_draft/_clear, te_tax_gen_supersede_<slot>,
      te_tax_gen_bump_pver, te_tax_gen_reset_commitments,
      te_tax_gen_refresh_support, te_tax_gen_oppose_approval). The only
      generated file that removes variables: a closed record's payload.
  common/script_values/te_tax_generated_support_values.txt
      The draft, bill and support-model values: the baselines at the due
      month, delta-levels, the per-group reasons from the EXPOSURE and
      TAX_LAW_PROGRESSIVENESS tables, and the clout sums.
  common/customizable_localization/te_tax_generated_custom_loc.txt
      te_tax_hist_event_<i>: the line each history row prints (newest first),
      chosen by the entry's kind and, for a sunset, its instrument.

The script-value file also carries the guarded te_tax_view_* display values
for every instrument and every catalog good, and the panels' views: the open
draft and bill, the package slots, the last change and the history ring
newest first (te_tax_view_hist_<i>_*). The consumption-goods catalog is
derived from the pop needs (vanilla_parsed/common/pop_needs.json plus the mod's
common/pop_needs/*.txt) and the goods definitions (vanilla_parsed/common/
goods.json plus common/goods/*.txt), always read from this repo, never --root.
Schema and catalog rule: docs/systems/tax_code_schema.md.

Later tasks register more outputs the same way: write a function returning the
file's bytes and decorate it with @output("<repo-relative path>").

Usage (repo root, system python3; standard library plus the repo's own
organize_loc and paradox_file_parser):

    python3 scripts/generators/gen_tax_code.py            # write the outputs
    python3 scripts/generators/gen_tax_code.py --check    # write nothing; exit 1 on drift
    python3 scripts/generators/gen_tax_code.py --root DIR # another tree (tests)
"""

import argparse
import functools
import glob
import json
import os
import sys
from decimal import Decimal
from typing import NamedTuple

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO)

from organize_loc import _render_loc_file, section_label  # noqa: E402
from paradox_file_parser import ParadoxFileParser  # noqa: E402

HEADER = "# AUTO-GENERATED by scripts/generators/gen_tax_code.py — do not edit manually"
CARRIER_LAW = "law_te_tax_code"
GATE_TRIGGER = "te_tax_code_on"
LOC_CATEGORY = "TAX_GENERATED"
LEVELS = (
    "tax_modifier_very_low", "tax_modifier_low", "tax_modifier_medium",
    "tax_modifier_high", "tax_modifier_very_high",
)

AMENDMENTS_PATH = "common/amendments/te_tax_amendments_generated.txt"
VALUES_PATH = "common/script_values/te_tax_generated_values.txt"
LOC_PATH = "localization/english/te_tax_generated_l_english.yml"
EFFECTS_PATH = "common/scripted_effects/te_tax_generated_effects.txt"
TRIGGERS_PATH = "common/scripted_triggers/te_tax_generated_triggers.txt"

# Catalog inputs, read from REPO (never --root).
VANILLA_POP_NEEDS = "vanilla_parsed/common/pop_needs.json"
VANILLA_GOODS = "vanilla_parsed/common/goods.json"
MOD_POP_NEEDS_GLOB = "common/pop_needs/*.txt"
MOD_GOODS_GLOB = "common/goods/*.txt"

# Per-instrument schema tokens (docs/systems/tax_code_schema.md) and their
# sentinels: te_tax_en_<key><suffix>, then the two version tokens.
INSTRUMENT_TOKENS = (("", 0), ("_since", -1), ("_exp", -1), ("_succ", -1))
VERSION_TOKENS = (("te_tax_pver_", 0), ("te_tax_xver_", 0))

# Scheduler (docs/systems/tax_code_schema.md, "Scheduler, package slots and
# history"). Two approved-package slots; a history ring of eight entries.
SLOTS = ("a", "b")
SLOT_IDS = (("none", 0), ("a", 1), ("b", 2))    # te_tax_slot_id_<slot>, stored in history
PACKAGE_HEADER = (("_on", 0), ("_due", -1), ("_state", 0), ("_seq", 0))
HISTORY_SIZE = 8
HISTORY_FIELDS = (("month", -1), ("kind", 0), ("slot", 0), ("inst", 0), ("version", -1))
# History kinds the scheduler writes (the schema doc lists all ten).
KIND_COMMENCED, KIND_SUNSET, KIND_HELD_CONFLICT, KIND_HELD_MISSED = 1, 2, 3, 4
# Package state values.
STATE_EMPTY, STATE_AWAITING, STATE_HELD_CONFLICT, STATE_HELD_MISSED = 0, 1, 2, 3
# Relief fields a package carries besides the per-instrument and per-good ones.
PACKAGE_RELIEF_FIELDS = ("agrel", "regrel", "xver_relief")
# Every scheduler debug line ends with these. In the country events that run the
# scheduler ROOT = THIS = the country: the tax probe printed month=22032 through
# this ScriptValue form from a country event, and vanilla 1.14.5's election
# lines print the date through TimeKeeper. No $PARAM$ may appear in a debug_log.
LOG_STAMP = ("month=[SCOPE.ScriptValue('te_history_month_index')|0] "
             "date=[TimeKeeper.GetCurrentDate.GetString] "
             "country=[THIS.GetCountry.GetNameNoFormatting]")

# Draft, bill and passage (docs/systems/tax_code_schema.md, "Draft, bill and
# passage"). The draft is te_tax_dr_*, the bill under debate te_tax_bl_*; both
# hold, per instrument, the target index (-1 untouched), the sunset offset in
# months and the planned version recorded when the provision was first touched.
BILL_EFFECTS_PATH = "common/scripted_effects/te_tax_generated_bill_effects.txt"
SUPPORT_VALUES_PATH = "common/script_values/te_tax_generated_support_values.txt"
RECORDS = ("dr", "bl")
RECORD_KEY_FIELDS = (("", -1), ("_sun", 0), ("_pver", -1))   # te_tax_<rec>_<key><field>, draft sentinel
KIND_APPROVED, KIND_SUPERSEDED, KIND_RESCHEDULED, KIND_RELEASED = 6, 8, 9, 10

# The panels (plan Task 7): the Budget > Tax Code tab and the journal entry.
# The history rows' text is one customizable localization per row.
CUSTOM_LOC_PATH = "common/customizable_localization/te_tax_generated_custom_loc.txt"
KIND_MIGRATED, KIND_REPAIRED = 5, 7
# Kinds that changed the enacted code (te_tax_code_version moved); the
# overview's last change is the newest of them.
CODE_CHANGE_KINDS = (KIND_COMMENCED, KIND_SUNSET, KIND_MIGRATED, KIND_REPAIRED)
# The line each history kind prints (te_tax_l_english.yml). A sunset prints
# te_tax_hist_kind_sunset_<key> for the instrument in its _inst.
HISTORY_KIND_KEYS = {
    KIND_COMMENCED: "te_tax_hist_kind_commenced",
    KIND_HELD_CONFLICT: "te_tax_hist_kind_held_conflict",
    KIND_HELD_MISSED: "te_tax_hist_kind_held_missed",
    KIND_MIGRATED: "te_tax_hist_kind_migrated",
    KIND_APPROVED: "te_tax_hist_kind_approved",
    KIND_REPAIRED: "te_tax_hist_kind_repaired",
    KIND_SUPERSEDED: "te_tax_hist_kind_superseded",
    KIND_RESCHEDULED: "te_tax_hist_kind_rescheduled",
    KIND_RELEASED: "te_tax_hist_kind_released",
}
HISTORY_KIND_FALLBACK = "te_tax_hist_kind_other"
# The interest groups the support model scores, by type key (ig_<key>).
IGS = ("armed_forces", "devout", "industrialists", "intelligentsia",
       "landowners", "petty_bourgeoisie", "rural_folk", "trade_unions")
# One vanilla tax level per channel: the material and ideology reasons count a
# change in these units (delta index x step / level step).
LEVEL_STEPS = {"wage": Decimal("0.05"), "div": Decimal("0.05"), "land": Decimal("0.15"),
               "head": Decimal("0.15"), "cons": Decimal("0.05")}
# How exposed each interest group is to each channel (0..1), in INSTRUMENTS order.
EXPOSURE = {
    "trade_unions": "1.0 0.0 0.0 0.8 0.8",
    "rural_folk": "0.4 0.1 1.0 0.3 0.8",
    "petty_bourgeoisie": "0.6 0.4 0.1 0.5 0.6",
    "intelligentsia": "0.6 0.2 0.0 0.3 0.4",
    "devout": "0.4 0.3 0.3 0.4 0.5",
    "armed_forces": "0.3 0.2 0.1 0.3 0.4",
    "industrialists": "0.2 1.0 0.0 0.1 0.2",
    "landowners": "0.1 0.8 0.3 0.1 0.2",
}
# Raising these channels makes the code more progressive; raising the others, less.
PROGRESSIVE_KEYS = ("wage", "div")
# Vanilla 1.14.5 taxation laws and their progressiveness (checked against
# vanilla_parsed/common/laws.json by test_tax_code_bill.py). An interest group's
# fiscal ideology is the sum over these laws of its stance x progressiveness / 100.
TAX_LAW_PROGRESSIVENESS = (
    ("law_consumption_based_taxation", -100),
    ("law_land_based_taxation", -50),
    ("law_per_capita_based_taxation", 0),
    ("law_proportional_taxation", 50),
    ("law_graduated_taxation", 100),
)
# law_stance buckets, strongest first so each stance scores once.
STANCE_BRANCHES = (("value > approve", 2), ("value > neutral", 1),
                   ("value < disapprove", -2), ("value < neutral", -1))
MATERIAL_WEIGHT, IDEOLOGY_WEIGHT, GOVERNMENT_BONUS = -10, 5, 10
REASON_CAP, SCORE_CAP = 40, 100
SUPPORT_REASONS = ("mat", "ideo", "fisc", "gov", "prom", "trust")


class Instrument(NamedTuple):
    key: str            # short name used in every generated identifier
    modifier: str       # the native tax modifier the amendment carries
    step: Decimal       # rate per index
    max_idx: int        # highest index that gets an amendment
    label: str          # shown to the player (title-cased in loc)
    payer: str          # who pays, as it reads in "Taxes <payer> at <rate>."
    percent: bool       # printed as a percentage (else as a bare amount)
    vanilla: tuple      # every value the five vanilla taxation laws set


def _values(text):
    return tuple(Decimal(value) for value in text.split())


INSTRUMENTS = (
    Instrument("wage", "tax_income_add", Decimal("0.025"), 20, "Wage tax",
               "the wages of employed pops", True,
               _values("0.05 0.075 0.10 0.125 0.15 0.175 0.20 0.25 0.30")),
    Instrument("div", "tax_dividends_add", Decimal("0.025"), 20, "Dividend tax",
               "dividends paid to pops who own private buildings", True,
               _values("0.025 0.05 0.10 0.15 0.20 0.25 0.30")),
    Instrument("land", "tax_land_add", Decimal("0.025"), 48, "Rural assessment",
               "peasants and farmers working agricultural buildings, who then pay no head tax",
               False, _values("0.20 0.275 0.35 0.40 0.425 0.50 0.55 0.70 0.85 1.00")),
    Instrument("head", "tax_per_capita_add", Decimal("0.05"), 30, "Head tax",
               "working adults who pay no rural assessment", False,
               _values("0.40 0.55 0.70 0.85 1.00")),
    Instrument("cons", "tax_consumption_add", Decimal("0.05"), 12, "Consumption tax rate",
               "goods on the taxed-goods list when pops buy them", True,
               _values("0.15 0.20 0.25 0.30 0.35")),
)


# Migration (docs/systems/tax_code_schema.md, "Migration"): the rates each vanilla
# 1.14.5 taxation law sets at each native tax level, in NATIVE_LEVELS order. An
# instrument a law leaves out is 0. test_tax_code_migration.py checks this table
# against vanilla_parsed/common/laws.json, so a vanilla patch that moves a rate or
# adds a law to lawgroup_taxation fails until the table is updated.
NATIVE_LEVELS = ("very_low", "low", "medium", "high", "very_high")
CONSUMPTION_LADDER = "0.15 0.20 0.25 0.30 0.35"
MIGRATION = (
    ("law_consumption_based_taxation", {"cons": CONSUMPTION_LADDER}),
    ("law_land_based_taxation", {"land": "0.40 0.55 0.70 0.85 1.00", "cons": CONSUMPTION_LADDER}),
    ("law_per_capita_based_taxation", {"wage": "0.05 0.075 0.10 0.125 0.15",
                                       "land": "0.20 0.275 0.35 0.425 0.50",
                                       "head": "0.40 0.55 0.70 0.85 1.00",
                                       "cons": CONSUMPTION_LADDER}),
    ("law_proportional_taxation", {"wage": "0.10 0.15 0.20 0.25 0.30",
                                   "div": "0.025 0.05 0.10 0.15 0.20",
                                   "cons": CONSUMPTION_LADDER}),
    ("law_graduated_taxation", {"wage": "0.10 0.125 0.15 0.175 0.20",
                                "div": "0.10 0.15 0.20 0.25 0.30",
                                "cons": CONSUMPTION_LADDER}),
)


def migration_indices(instruments=INSTRUMENTS):
    """[(law, level, {key: index})] for every MIGRATION law and native level, 25 in all.

    Raises ValueError if a rate is not index x step for an index in 0..max or is
    not one of the instrument's vanilla values.
    """
    by_key = {instrument.key: instrument for instrument in instruments}
    rows = []
    for law, rates in MIGRATION:
        unknown = set(rates) - set(by_key)
        if unknown:
            raise ValueError(f"{law}: no instrument {sorted(unknown)}")
        for n, level in enumerate(NATIVE_LEVELS):
            indices = {}
            for key, instrument in by_key.items():
                value = Decimal(rates[key].split()[n]) if key in rates else Decimal(0)
                index, remainder = divmod(value, instrument.step)
                if remainder != 0 or not 0 <= index <= instrument.max_idx:
                    raise ValueError(f"{law} {level}: {key} = {value} is not an index x {instrument.step}")
                if value and value not in instrument.vanilla:
                    raise ValueError(f"{law} {level}: {key} = {value} is not a vanilla value of {key}")
                indices[key] = int(index)
            rows.append((law, level, indices))
    return rows


def validate(instruments=INSTRUMENTS):
    """Raise ValueError unless every vanilla value is index x step for some index 1..max."""
    for instrument in instruments:
        for value in instrument.vanilla:
            index, remainder = divmod(value, instrument.step)
            if remainder != 0 or not 1 <= index <= instrument.max_idx:
                raise ValueError(
                    f"{instrument.key}: vanilla value {value} is not index x {instrument.step} "
                    f"for an index in 1..{instrument.max_idx}"
                )
    migration_indices(instruments)


def fmt(value):
    """A Decimal without trailing zeros or an exponent: 0.075, 0.1, 1, 10."""
    return format(value.normalize(), "f")


def rate(instrument, idx):
    return instrument.step * idx


def amendment_key(instrument, idx):
    return f"amendment_te_tax_{instrument.key}_{idx}"


def display(instrument, idx):
    """The rate as the player reads it: 7.5% for a rate, 0.425 for an amount."""
    value = rate(instrument, idx)
    return f"{fmt(value * 100)}%" if instrument.percent else fmt(value)


# ---------------------------------------------------------------------------
# Consumption-goods catalog
# ---------------------------------------------------------------------------

_OPERATORS = {"=", "<", ">", "<=", ">=", "!=", "?=", "=="}


def _plain(node):
    """Drop (operator, value) pairs from parser or vanilla_parsed JSON output."""
    if (isinstance(node, (tuple, list)) and len(node) == 2
            and isinstance(node[0], str) and node[0] in _OPERATORS):
        return _plain(node[1])
    if isinstance(node, dict):
        return {key: _plain(value) for key, value in node.items()}
    if isinstance(node, list):
        return [_plain(item) for item in node]
    return node


def _merged(vanilla_json, mod_glob):
    """Vanilla entries overlaid with the mod's files, as the engine loads them.

    REPLACE:x replaces x; INJECT:x overwrites x's fields and appends its
    `entry` blocks (a pop need's repeated key); a plain key the vanilla
    database already holds is dropped ("Duplicated key").
    """
    with open(os.path.join(REPO, vanilla_json), encoding="utf-8") as handle:
        merged = _plain(json.load(handle))
    for path in sorted(glob.glob(os.path.join(REPO, mod_glob))):
        parser = ParadoxFileParser()
        parser.parse_file(path, apply_directives=False)
        for key, body in _plain(parser.data).items():
            directive, _, name = key.rpartition(":")
            if not isinstance(body, dict):
                continue
            if "REPLACE" in directive or (directive and name not in merged and "OR_CREATE" in directive):
                merged[name] = body
            elif "INJECT" in directive and name in merged:
                injected = {**merged[name], **body}
                if "entry" in merged[name] and "entry" in body:
                    injected["entry"] = _as_list(merged[name]["entry"]) + _as_list(body["entry"])
                merged[name] = injected
            elif not directive and name not in merged:
                merged[name] = body
    return merged


def _as_list(value):
    return value if isinstance(value, list) else [value]


@functools.lru_cache(maxsize=None)
def goods_definitions():
    return {name: body for name, body in _merged(VANILLA_GOODS, MOD_GOODS_GLOB).items()
            if isinstance(body, dict)}


@functools.lru_cache(maxsize=None)
def pop_need_goods():
    """{good: (pop need, ...)} for every good some pop need lists as an entry."""
    used = {}
    for need, body in sorted(_merged(VANILLA_POP_NEEDS, MOD_POP_NEEDS_GLOB).items()):
        entries = body.get("entry", []) if isinstance(body, dict) else []
        for entry in _as_list(entries):
            used.setdefault(entry["goods"], []).append(need)
    return {good: tuple(needs) for good, needs in used.items()}


@functools.lru_cache(maxsize=None)
def consumption_catalog():
    """The goods a code can put on the taxed-goods list: every good a pop need buys, sorted.

    A good with no `consumption_tax_cost` costs the engine default
    (DEFAULT_GOODS_TAX_COST = 100, 1.14.5 00_defines.txt) and is still
    taxable: vanilla history taxes liquor, tobacco, opium and wine, none of
    which sets one, and the local goods services, transportation and
    electricity are taxable too.
    """
    goods = goods_definitions()
    for good in pop_need_goods():
        if good not in goods:
            raise ValueError(f"pop need good {good} has no goods definition")
    return tuple(sorted(pop_need_goods()))


def all_goods():
    """Every good defined by vanilla or the mod, sorted."""
    return tuple(sorted(goods_definitions()))


def stray_goods():
    """Goods outside the catalog: no pop buys them, so no code taxes them.

    te_tax_gen_sync_goods removes a native consumption tax on any of these,
    so the native taxed set always equals the enacted one.
    """
    catalog = set(consumption_catalog())
    return tuple(good for good in all_goods() if good not in catalog)


# ---------------------------------------------------------------------------
# Output registry
# ---------------------------------------------------------------------------

OUTPUTS = {}


def output(path):
    """Register a function returning one output file's bytes under its repo-relative path."""
    def register(function):
        OUTPUTS[path] = function
        return function
    return register


def _txt(text):
    """A brace .txt file's bytes: UTF-8 BOM, LF endings."""
    return text.encode("utf-8-sig")


@output(AMENDMENTS_PATH)
def amendments():
    lines = [
        HEADER,
        "# One amendment per instrument and index: rate = index x step (INSTRUMENTS in the generator).",
        f"# {CARRIER_LAW} collects nothing; the amendment attached to it carries the rate. All five",
        "# tax_modifier_* blocks are identical, so a native tax-level change moves only the",
        "# political static modifier. Nothing sponsors, revokes or repeals these on its own.",
    ]
    for instrument in INSTRUMENTS:
        lines += ["", f"# {instrument.label}: {instrument.modifier}, step {fmt(instrument.step)}, "
                      f"indexes 1..{instrument.max_idx}"]
        for idx in range(1, instrument.max_idx + 1):
            value = fmt(rate(instrument, idx))
            if idx > 1:
                lines.append("")
            lines += [
                f"{amendment_key(instrument, idx)} = {{",
                f"\tparent = {CARRIER_LAW}",
                f"\tallowed_laws = {{ {CARRIER_LAW} }}",
                f"\tpossible = {{ {GATE_TRIGGER} = yes }}",
                "\tcan_repeal = { always = no }",
                "\twould_sponsor = { always = no }",
                "\tai_will_revoke = { always = no }",
            ]
            lines += [f"\t{level} = {{ {instrument.modifier} = {value} }}" for level in LEVELS]
            lines.append("}")
    return _txt("\n".join(lines) + "\n")


@output(VALUES_PATH)
def script_values():
    lines = [
        HEADER,
        "# Index encoding for the legislated tax code: rate = index x te_tax_step_<key>, with",
        "# the index from 0 (not set) to te_tax_max_<key>. A display value is written as",
        "# `value = var:<index variable>` `multiply = te_tax_step_<key>`; te_tax_pct_step_<key>",
        "# is the step in percentage points, for the instruments printed as a percentage.",
    ]
    for instrument in INSTRUMENTS:
        lines += [
            "",
            f"te_tax_step_{instrument.key} = {fmt(instrument.step)}",
            f"te_tax_max_{instrument.key} = {instrument.max_idx}",
        ]
        if instrument.percent:
            lines.append(f"te_tax_pct_step_{instrument.key} = {fmt(instrument.step * 100)}")
    lines += [
        "",
        "# Package slots as the history ring stores them (te_tax_h<n>_slot): none, a, b.",
        "# te_tax_gen_history_write reads te_tax_slot_id_<SLOT>, so callers pass the letter.",
    ]
    lines += [f"te_tax_slot_id_{name} = {value}" for name, value in SLOT_IDS]
    lines += [
        "",
        "# Display values (docs/systems/tax_code_schema.md, \"Display values\"): guarded reads of",
        "# the enacted code for the GUI and loc. Each reads only variables it has just tested",
        "# with has_variable and returns the schema sentinel when one is absent: 0 for an index,",
        "# a rate or a flag, -1 for a month or a successor. _y/_mo split a month index into a",
        "# year and a 1-based month, because the GUI cannot divide. They write nothing.",
    ]
    for instrument in INSTRUMENTS:
        lines += [""] + _instrument_views(instrument)
    lines += ["", "# One per catalog good: 1 if the good is on the enacted taxed-goods list."]
    for good in consumption_catalog():
        lines += _guarded_view(f"te_tax_view_en_g_{good}", f"te_tax_en_g_{good}", 0)
    lines += ["", "# How many catalog goods the enacted code taxes.", "te_tax_view_goods_count = {",
              "\tvalue = 0"]
    for good in consumption_catalog():
        variable = f"te_tax_en_g_{good}"
        lines.append(f"\tif = {{ limit = {{ has_variable = {variable} }} add = var:{variable} }}")
    lines.append("}")
    lines += _panel_views()
    return _txt("\n".join(lines) + "\n")


def _panel_views():
    """The views the Budget > Tax Code tab and the journal entry read (plan Task 7)."""
    lines = [
        "",
        "# The panels' views: the open draft and the bill under debate, the two package",
        "# slots, the newest change to the code and the history ring newest first. A record's",
        "# payload is read only while its own token says it is open: a closed record's payload",
        "# is removed, and a civil war's winner may hold a loser's stale copy.",
    ]
    for record in RECORDS:
        token = f"te_tax_{record}_on"
        lines += _guarded_view(f"te_tax_view_{record}_on", token, 0)
        lines += _month_views(f"te_tax_view_{record}_due", f"te_tax_{record}_due", _is_open(token))
    lines += ["", "# Package slots: on, state (1 awaiting, 2 held_conflict, 3 held_missed), due month."]
    for slot in SLOTS:
        token = f"te_tax_p{slot}_on"
        lines += _guarded_view(f"te_tax_view_p{slot}_on", token, 0)
        lines += _guarded_view(f"te_tax_view_p{slot}_state", f"te_tax_p{slot}_state", 0,
                               condition=_is_open(token))
        lines += _month_views(f"te_tax_view_p{slot}_due", f"te_tax_p{slot}_due", _is_open(token))
    return lines + _last_change_views() + _history_views()


def _is_open(token):
    return f"has_variable = {token} var:{token} = 1"


def _split_month(name, month, guard):
    """`name`_y and `name`_mo: the year and 1-based month of the script value `month`."""
    limit = f"{guard} {month} >= 0"
    return ([f"{name}_y = {{", "\tvalue = -1", "\tif = {", f"\t\tlimit = {{ {limit} }}",
             f"\t\tvalue = {month}", "\t\tdivide = 12", "\t\tfloor = yes", "\t}", "}"]
            + [f"{name}_mo = {{", "\tvalue = -1", "\tif = {", f"\t\tlimit = {{ {limit} }}",
               f"\t\tvalue = {month}", "\t\tdivide = 12", "\t\tfloor = yes", "\t\tmultiply = -12",
               f"\t\tadd = {month}", "\t\tadd = 1", "\t}", "}"])


def _last_change_views():
    """The month the enacted code last changed: the newest history entry of a kind
    that moves te_tax_code_version, or an instrument's operative-since month if the
    ring has rolled past it (`min =` keeps the larger)."""
    kinds = " ".join(f"var:te_tax_h{{n}}_kind = {kind}" for kind in CODE_CHANGE_KINDS)
    lines = ["", "# The newest change to the enacted code (-1 if none is known), and its year and month.",
             "te_tax_view_last_change = {", "\tvalue = -1"]
    for n in range(1, HISTORY_SIZE + 1):
        lines.append(f"\tif = {{ limit = {{ has_variable = te_tax_h{n}_kind has_variable = te_tax_h{n}_month "
                     f"OR = {{ {kinds.format(n=n)} }} }} min = var:te_tax_h{n}_month }}")
    for instrument in INSTRUMENTS:
        since = f"te_tax_en_{instrument.key}_since"
        lines.append(f"\tif = {{ limit = {{ has_variable = {since} }} min = var:{since} }}")
    lines.append("}")
    return lines + _split_month("te_tax_view_last_change", "te_tax_view_last_change",
                                "has_variable = te_tax_schema")


def _history_views():
    """Position i (1 = newest) of the ring is entry n = te_tax_h_head - i + 1, wrapping
    from 1 back to HISTORY_SIZE."""
    lines = ["", "# The history ring newest first: position <i> reads entry te_tax_h<n>_* with",
             "# n = te_tax_h_head - i + 1, wrapping past 1 to 8. kind 0 and month -1 while the",
             "# position is empty. _inst is the instrument a sunset changed (INSTRUMENTS order)."]
    for i in range(1, HISTORY_SIZE + 1):
        for field, default in (("kind", 0), ("inst", 0), ("month", -1)):
            lines += [f"te_tax_view_hist_{i}_{field} = {{", f"\tvalue = {default}"]
            for head in range(1, HISTORY_SIZE + 1):
                variable = f"te_tax_h{(head - i) % HISTORY_SIZE + 1}_{field}"
                opener = "if" if head == 1 else "else_if"
                lines.append(f"\t{opener} = {{ limit = {{ has_variable = te_tax_h_head var:te_tax_h_head = {head} "
                             f"has_variable = {variable} }} value = var:{variable} }}")
            lines.append("}")
        month = f"te_tax_view_hist_{i}_month"
        lines += _split_month(month, month, "has_variable = te_tax_h_head")
    return lines


@output(CUSTOM_LOC_PATH)
def custom_localization():
    lines = [
        HEADER,
        "# The history rows' text (gui/journal_entry_widgets/te_tax_overview_widget.gui,",
        "# te_tax_history_section): one customizable localization per row, newest first, read as",
        "# GetPlayer.GetCustom('te_tax_hist_event_<i>'). Each picks the line for the entry's kind",
        "# (te_tax_view_hist_<i>_kind) and, for a sunset, its instrument (_inst). The triggers read",
        "# only the guarded views, never a variable.",
    ]
    for i in range(1, HISTORY_SIZE + 1):
        kind, inst = f"te_tax_view_hist_{i}_kind", f"te_tax_view_hist_{i}_inst"
        entries = []
        for value in range(1, KIND_RELEASED + 1):
            if value == KIND_SUNSET:
                entries += [(f"{kind} = {KIND_SUNSET} {inst} = {idx}", f"te_tax_hist_kind_sunset_{instrument.key}")
                            for idx, instrument in enumerate(INSTRUMENTS, start=1)]
            else:
                entries.append((f"{kind} = {value}", HISTORY_KIND_KEYS[value]))
        lines += ["", f"te_tax_hist_event_{i} = {{", "\ttype = country", "\trandom_valid = no"]
        for trigger, key in entries:
            lines += ["\ttext = {", f"\t\ttrigger = {{ {trigger} }}", f"\t\tlocalization_key = {key}", "\t}"]
        lines += ["\ttext = {", f"\t\tlocalization_key = {HISTORY_KIND_FALLBACK}", "\t}", "}"]
    return _txt("\n".join(lines) + "\n")


def _guarded_view(name, variable, default, ops=(), condition=""):
    """A te_tax_view_* value: `default`, or var:`variable` (then `ops`) when it exists."""
    limit = f"has_variable = {variable}" + (f" {condition}" if condition else "")
    if not ops:
        return [f"{name} = {{", f"\tvalue = {default}",
                f"\tif = {{ limit = {{ {limit} }} value = var:{variable} }}", "}"]
    return ([f"{name} = {{", f"\tvalue = {default}", "\tif = {", f"\t\tlimit = {{ {limit} }}",
             f"\t\tvalue = var:{variable}"]
            + [f"\t\t{op}" for op in ops] + ["\t}", "}"])


def _month_views(name, variable, condition=""):
    """The month, its year and its 1-based calendar month (all -1 when unset, or
    when `condition`, a further guard, fails)."""
    started = " ".join(part for part in (condition, f"var:{variable} >= 0") if part)
    return (_guarded_view(name, variable, -1, condition=condition)
            + _guarded_view(f"{name}_y", variable, -1, ("divide = 12", "floor = yes"), started)
            + _guarded_view(f"{name}_mo", variable, -1,
                            ("divide = 12", "floor = yes", "multiply = -12",
                             f"add = var:{variable}", "add = 1"), started))


def _instrument_views(instrument):
    key = instrument.key
    index = f"te_tax_en_{key}"
    successor = f"te_tax_en_{key}_succ"
    step = f"multiply = te_tax_step_{key}"
    pct = f"multiply = te_tax_pct_step_{key}"
    lines = [f"# {instrument.label}: enacted index, rate (index x step), operative since, sunset, successor."]
    lines += _guarded_view(f"te_tax_view_en_{key}", index, 0)
    lines += _guarded_view(f"te_tax_view_en_{key}_rate", index, 0, (step,))
    if instrument.percent:
        lines += _guarded_view(f"te_tax_view_en_{key}_pct", index, 0, (pct,))
    lines += _month_views(f"te_tax_view_en_{key}_since", f"te_tax_en_{key}_since")
    lines += _month_views(f"te_tax_view_en_{key}_exp", f"te_tax_en_{key}_exp")
    lines += _guarded_view(f"te_tax_view_en_{key}_succ", successor, -1)
    started = f"var:{successor} >= 0"
    lines += _guarded_view(f"te_tax_view_en_{key}_succ_rate", successor, 0, (step,), started)
    if instrument.percent:
        lines += _guarded_view(f"te_tax_view_en_{key}_succ_pct", successor, 0, (pct,), started)
    return lines


def _guarded_write(variable, value, indent="\t"):
    """The init idiom: write `variable` only if it is absent, so nothing is overwritten."""
    return (f"{indent}if = {{ limit = {{ NOT = {{ has_variable = {variable} }} }} "
            f"set_variable = {{ name = {variable} value = {value} }} }}")


# ---------------------------------------------------------------------------
# Scheduler: package slots, sunsets, history (docs/systems/tax_code_schema.md)
# ---------------------------------------------------------------------------

def schedule_tokens():
    """[(token, sentinel)] the scheduler initialises: clock, slot headers, history ring."""
    tokens = [("te_tax_now", -1)]
    for slot in SLOTS:
        tokens += [(f"te_tax_p{slot}{suffix}", sentinel) for suffix, sentinel in PACKAGE_HEADER]
    tokens.append(("te_tax_h_head", 0))
    for n in range(1, HISTORY_SIZE + 1):
        tokens += [(f"te_tax_h{n}_{field}", sentinel) for field, sentinel in HISTORY_FIELDS]
    return tokens


def _log(event, detail=""):
    """A scheduler debug line: `TE_TAX <event> [detail] month=... date=... country=...`."""
    text = f"TE_TAX {event} {detail}; {LOG_STAMP}" if detail else f"TE_TAX {event} {LOG_STAMP}"
    return f'debug_log = "{text}"'


def _history(kind, slot="none", inst=0):
    return f"te_tax_gen_history_write = {{ KIND = {kind} SLOT = {slot} INST = {inst} }}"


def _other(slot):
    return SLOTS[1 - SLOTS.index(slot)]


def _sunset(instrument, inst):
    key = instrument.key
    en = f"te_tax_en_{key}"
    dropped = _log("sunset_dropped", f"{key}: no successor recorded")
    executed = _log("sunset", key)
    deferred = _log("sunset_deferred", f"{key}: operative only since this month")
    return [
        "",
        f"# {instrument.label}: executes the enacted value's sunset once its month has come",
        "# (rule 2). It runs only when the value has been operative since an earlier month,",
        "# so a package's own sunset can never share its commencement call; otherwise it",
        "# waits for next month. A late sunset catches up. One without a successor is",
        "# dropped, not deferred, so it cannot hold te_tax_next_month in the past.",
        f"te_tax_gen_sunset_{key} = {{",
        "\tif = {",
        "\t\tlimit = {",
        f"\t\t\tvar:{en}_exp >= 0",
        f"\t\t\tvar:{en}_exp <= var:te_tax_now",
        "\t\t}",
        "\t\tif = {",
        f"\t\t\tlimit = {{ var:{en}_succ < 0 }}",
        f"\t\t\tset_variable = {{ name = {en}_exp value = -1 }}",
        f"\t\t\t{dropped}",
        "\t\t}",
        "\t\telse_if = {",
        f"\t\t\tlimit = {{ var:{en}_since < var:te_tax_now }}",
        f"\t\t\tset_variable = {{ name = {en} value = var:{en}_succ }}",
        f"\t\t\tset_variable = {{ name = {en}_since value = var:te_tax_now }}",
        f"\t\t\tset_variable = {{ name = {en}_exp value = -1 }}",
        f"\t\t\tset_variable = {{ name = {en}_succ value = -1 }}",
        "\t\t\tchange_variable = { name = te_tax_code_version add = 1 }",
        f"\t\t\t{_history(KIND_SUNSET, inst=inst)}",
        f"\t\t\t{executed}",
        "\t\t}",
        "\t\telse = {",
        f"\t\t\t{deferred}",
        "\t\t}",
        "\t}",
        "}",
    ]


def _commence(slot):
    p = f"te_tax_p{slot}"
    commenced = _log("commenced", f"slot={slot}")
    conflict = _log("held_conflict", f"slot={slot}: a touched provision changed outside legislation")
    return [
        "",
        f"# Slot {slot}: commences in its due month and in no other (rule 3). The processor runs",
        "# on the 1st, so the package takes effect from the 1st. If a provision it touches was",
        "# changed outside legislation since approval (te_tax_xver_*), the whole package holds",
        "# and collections stay as they are. A due month already past holds it as missed.",
        f"te_tax_gen_commence_{slot} = {{",
        "\tif = {",
        "\t\tlimit = {",
        f"\t\t\tvar:{p}_on = 1",
        f"\t\t\tvar:{p}_state = {STATE_AWAITING}",
        f"\t\t\tvar:{p}_due = var:te_tax_now",
        "\t\t}",
        "\t\tif = {",
        f"\t\t\tlimit = {{ te_tax_gen_package_current_{slot} = yes }}",
        f"\t\t\tte_tax_gen_apply_{slot} = yes",
        "\t\t\tchange_variable = { name = te_tax_code_version add = 1 }",
        f"\t\t\tset_variable = {{ name = {p}_on value = 0 }}",
        f"\t\t\tset_variable = {{ name = {p}_state value = {STATE_EMPTY} }}",
        f"\t\t\t{_history(KIND_COMMENCED, slot)}",
        f"\t\t\t{commenced}",
        "\t\t}",
        "\t\telse = {",
        f"\t\t\tset_variable = {{ name = {p}_state value = {STATE_HELD_CONFLICT} }}",
        f"\t\t\t{_history(KIND_HELD_CONFLICT, slot)}",
        f"\t\t\t{conflict}",
        "\t\t}",
        "\t}",
        "\telse = {",
        f"\t\tte_tax_gen_hold_missed_{slot} = yes",
        "\t}",
        "}",
    ]


def _hold_missed(slot):
    p = f"te_tax_p{slot}"
    missed = _log("held_missed", f"slot={slot}: due month passed without commencement")
    return [
        "",
        f"# Slot {slot}: an awaiting package whose due month has passed holds as missed; it never",
        "# commences late (spec: missed dates need explicit rescheduling). The watchdog calls",
        "# this too, because it fires only once the month has passed.",
        f"te_tax_gen_hold_missed_{slot} = {{",
        "\tif = {",
        "\t\tlimit = {",
        f"\t\t\tvar:{p}_on = 1",
        f"\t\t\tvar:{p}_state = {STATE_AWAITING}",
        f"\t\t\tvar:{p}_due < var:te_tax_now",
        "\t\t}",
        f"\t\tset_variable = {{ name = {p}_state value = {STATE_HELD_MISSED} }}",
        f"\t\t{_history(KIND_HELD_MISSED, slot)}",
        f"\t\t{missed}",
        "\t}",
        "}",
    ]


def _apply(slot):
    p = f"te_tax_p{slot}"
    lines = [
        "",
        f"# Slot {slot}: copies every field the package touches into the enacted code. Only",
        "# te_tax_gen_commence_<slot> calls it, inside the processor, which has set te_tax_now,",
        "# run this month's sunsets first and syncs collection once after every slot.",
        "# Supersession of the enacted provision happens here, at commencement, never at",
        "# approval: the package replaces the value and its sunset. With no sunset of its own",
        "# the change is permanent and clears any pending sunset (_exp and _succ = -1). With",
        "# one, the provision reverts to the underlying permanent rate: a sunset still pending",
        "# now (this month's have run, so it is in the future) keeps its successor; otherwise",
        "# the rate in force is the successor. Both are captured before anything is",
        "# overwritten. The stored te_tax_p<slot>_<key>_succ is only the review's preview and",
        "# is never read here.",
        f"te_tax_gen_apply_{slot} = {{",
    ]
    for instrument in INSTRUMENTS:
        key = instrument.key
        en = f"te_tax_en_{key}"
        lines += [
            "\tif = {",
            f"\t\tlimit = {{ var:{p}_{key} >= 0 }}",
            "\t\tif = {",
            f"\t\t\tlimit = {{ var:{p}_{key}_exp >= 0 }}",
            "\t\t\t# A pending sunset with a successor keeps it; otherwise the rate in force.",
            "\t\t\tif = {",
            "\t\t\t\tlimit = {",
            "\t\t\t\t\tOR = {",
            f"\t\t\t\t\t\tvar:{en}_exp < 0",
            f"\t\t\t\t\t\tvar:{en}_succ < 0",
            "\t\t\t\t\t}",
            "\t\t\t\t}",
            f"\t\t\t\tset_variable = {{ name = {en}_succ value = var:{en} }}",
            "\t\t\t}",
            "\t\t}",
            "\t\telse = {",
            f"\t\t\tset_variable = {{ name = {en}_succ value = -1 }}",
            "\t\t}",
            f"\t\tset_variable = {{ name = {en} value = var:{p}_{key} }}",
            f"\t\tset_variable = {{ name = {en}_since value = var:te_tax_now }}",
            f"\t\tset_variable = {{ name = {en}_exp value = var:{p}_{key}_exp }}",
            "\t}",
        ]
    for good in consumption_catalog():
        lines.append(f"\tif = {{ limit = {{ var:{p}_g_{good} >= 0 }} "
                     f"set_variable = {{ name = te_tax_en_g_{good} value = var:{p}_g_{good} }} }}")
    for field in ("agrel", "regrel"):
        lines.append(f"\tif = {{ limit = {{ var:{p}_{field} >= 0 }} "
                     f"set_variable = {{ name = te_tax_en_{field} value = var:{p}_{field} }} }}")
    lines += [
        "\t# A package that restates regional relief names its whole state set.",
        "\tif = {",
        f"\t\tlimit = {{ var:{p}_regrel_states_set = 1 }}",
        "\t\tevery_scope_state = {",
        "\t\t\tif = {",
        "\t\t\t\tlimit = {",
        f"\t\t\t\t\thas_variable = te_tax_pending_relief_{slot}",
        f"\t\t\t\t\tvar:te_tax_pending_relief_{slot} = 1",
        "\t\t\t\t}",
        "\t\t\t\tset_variable = { name = te_tax_relief_state value = 1 }",
        "\t\t\t}",
        "\t\t\telse_if = {",
        "\t\t\t\tlimit = { has_variable = te_tax_relief_state }",
        "\t\t\t\tset_variable = { name = te_tax_relief_state value = 0 }",
        "\t\t\t}",
        "\t\t}",
        "\t}",
        "\tevery_scope_state = {",
        f"\t\tlimit = {{ has_variable = te_tax_pending_relief_{slot} }}",
        f"\t\tset_variable = {{ name = te_tax_pending_relief_{slot} value = 0 }}",
        "\t}",
        "}",
    ]
    return lines


def _store_successor(slot, key):
    """Lines setting te_tax_p<slot>_<key>_succ, the review's preview of what the sunset restores.

    A forecast at store time by te_tax_gen_apply_<slot>'s rule, the underlying
    permanent rate: the enacted provision's pending successor if it has a sunset (one
    falling before the due month will have run; a later one is still pending), else
    its value; overridden the same way by the other slot's package when that awaiting
    package touches the provision earlier and so commences first. Commencement never
    reads it.
    """
    p, o = f"te_tax_p{slot}", f"te_tax_p{_other(slot)}"
    en = f"te_tax_en_{key}"
    return [
        f"\t\tset_variable = {{ name = {p}_{key}_succ value = var:{en} }}",
        "\t\tif = {",
        "\t\t\tlimit = {",
        f"\t\t\t\tvar:{en}_exp >= 0",
        f"\t\t\t\tvar:{en}_succ >= 0",
        "\t\t\t}",
        f"\t\t\tset_variable = {{ name = {p}_{key}_succ value = var:{en}_succ }}",
        "\t\t}",
        "\t\t# The other slot's payload exists only while it is on, so read it nested.",
        "\t\tif = {",
        "\t\t\tlimit = {",
        f"\t\t\t\tvar:{o}_on = 1",
        f"\t\t\t\tvar:{o}_state = {STATE_AWAITING}",
        f"\t\t\t\tvar:{o}_due < var:te_tax_bl_due",
        "\t\t\t}",
        "\t\t\tif = {",
        f"\t\t\t\tlimit = {{ var:{o}_{key} >= 0 }}",
        f"\t\t\t\tset_variable = {{ name = {p}_{key}_succ value = var:{o}_{key} }}",
        "\t\t\t\tif = {",
        "\t\t\t\t\tlimit = {",
        f"\t\t\t\t\t\tvar:{o}_{key}_exp >= 0",
        f"\t\t\t\t\t\tvar:{o}_{key}_succ >= 0",
        "\t\t\t\t\t}",
        f"\t\t\t\t\tset_variable = {{ name = {p}_{key}_succ value = var:{o}_{key}_succ }}",
        "\t\t\t\t}",
        "\t\t\t}",
        "\t\t}",
    ]


def _store(slot):
    p, o = f"te_tax_p{slot}", f"te_tax_p{_other(slot)}"
    stored = _log("stored", f"slot={slot}")
    lines = [
        "",
        f"# Slot {slot}: writes an approved package from the bill record (te_tax_bl_*). Called",
        "# only through te_tax_store_package, after te_tax_can_store_package and with",
        "# scope:te_tax_country saved. Every payload field is written, so nothing stale from an",
        "# earlier package survives. A sunset is due + offset, written only for an offset of at",
        "# least one month. _succ is a preview for the review only (commencement decides the",
        "# successor then, by te_tax_gen_apply_<slot>'s rule): the underlying permanent rate,",
        "# from the other slot's awaiting package if it touches the provision earlier, else",
        "# from the enacted provision. seq = one above both slots. The slot is switched on last.",
        "# _due0 keeps the approved month and _pver_<group> the planned versions after this",
        "# approval, for te_tax_cmd_package_reschedule: a missed package may move only a few",
        "# months, and only while no later approval has touched what it changes.",
        f"te_tax_gen_store_{slot} = {{",
        f"\tset_variable = {{ name = {p}_due value = var:te_tax_bl_due }}",
        f"\tset_variable = {{ name = {p}_due0 value = var:te_tax_bl_due }}",
        "\tif = {",
        f"\t\tlimit = {{ var:{o}_seq > var:{p}_seq }}",
        f"\t\tset_variable = {{ name = {p}_seq value = var:{o}_seq }}",
        "\t}",
        f"\tchange_variable = {{ name = {p}_seq add = 1 }}",
    ]
    for instrument in INSTRUMENTS:
        key = instrument.key
        lines += [
            f"\tset_variable = {{ name = {p}_{key} value = var:te_tax_bl_{key} }}",
            f"\tset_variable = {{ name = {p}_xver_{key} value = var:te_tax_bl_xver_{key} }}",
            "\tif = {",
            "\t\tlimit = {",
            f"\t\t\tvar:te_tax_bl_{key} >= 0",
            f"\t\t\tvar:te_tax_bl_{key}_sun >= 1",
            "\t\t}",
            f"\t\tset_variable = {{ name = {p}_{key}_exp value = var:te_tax_bl_due }}",
            f"\t\tchange_variable = {{ name = {p}_{key}_exp add = var:te_tax_bl_{key}_sun }}",
        ]
        lines += _store_successor(slot, key)
        lines += [
            "\t}",
            "\telse = {",
            f"\t\tset_variable = {{ name = {p}_{key}_exp value = -1 }}",
            f"\t\tset_variable = {{ name = {p}_{key}_succ value = -1 }}",
            "\t}",
        ]
    lines += [f"\tset_variable = {{ name = {p}_g_{good} value = var:te_tax_bl_g_{good} }}"
              for good in consumption_catalog()]
    lines.append(f"\tset_variable = {{ name = {p}_xver_goods value = var:te_tax_bl_xver_goods }}")
    groups = [instrument.key for instrument in INSTRUMENTS] + ["goods", "relief"]
    lines += [f"\tset_variable = {{ name = {p}_pver_{group} value = var:te_tax_pver_{group} }}" for group in groups]
    lines += [f"\tset_variable = {{ name = {p}_{field} value = var:te_tax_bl_{field} }}"
              for field in PACKAGE_RELIEF_FIELDS]
    lines += [
        "\t# Regional relief: a bill that touches it (te_tax_bl_regrel >= 0) names its whole",
        "\t# state set in te_tax_bl_relief_states, possibly none; commencement moves the marks",
        "\t# to te_tax_relief_state.",
        "\tevery_scope_state = {",
        f"\t\tlimit = {{ has_variable = te_tax_pending_relief_{slot} }}",
        f"\t\tset_variable = {{ name = te_tax_pending_relief_{slot} value = 0 }}",
        "\t}",
        "\tif = {",
        "\t\tlimit = { var:te_tax_bl_regrel >= 0 }",
        f"\t\tset_variable = {{ name = {p}_regrel_states_set value = 1 }}",
        "\t\tif = {",
        "\t\t\tlimit = { has_variable_list = te_tax_bl_relief_states }",
        "\t\t\tevery_in_list = {",
        "\t\t\t\tvariable = te_tax_bl_relief_states",
        "\t\t\t\tlimit = { owner = scope:te_tax_country }",
        f"\t\t\t\tset_variable = {{ name = te_tax_pending_relief_{slot} value = 1 }}",
        "\t\t\t}",
        "\t\t}",
        "\t}",
        "\telse = {",
        f"\t\tset_variable = {{ name = {p}_regrel_states_set value = 0 }}",
        "\t}",
        f"\t{stored}",
        f"\tset_variable = {{ name = {p}_state value = {STATE_AWAITING} }}",
        f"\tset_variable = {{ name = {p}_on value = 1 }}",
        "}",
    ]
    return lines


def _next_month():
    lines = [
        "",
        "# te_tax_next_month: the earliest month with a transition due, -1 if none. Enacted",
        "# sunsets and awaiting packages count; a held package waits for rescheduling and does",
        "# not. A deferred sunset keeps it at the current month until it runs.",
        "te_tax_gen_next_month = {",
        "\tset_variable = { name = te_tax_next_month value = -1 }",
    ]
    candidates = [(f"var:te_tax_en_{instrument.key}_exp >= 0", f"var:te_tax_en_{instrument.key}_exp")
                  for instrument in INSTRUMENTS]
    candidates += [(f"var:te_tax_p{slot}_on = 1\n\t\t\tvar:te_tax_p{slot}_state = {STATE_AWAITING}",
                    f"var:te_tax_p{slot}_due") for slot in SLOTS]
    for condition, month in candidates:
        lines += [
            "\tif = {",
            "\t\tlimit = {",
            f"\t\t\t{condition}",
            "\t\t\tOR = {",
            "\t\t\t\tvar:te_tax_next_month < 0",
            f"\t\t\t\t{month} < var:te_tax_next_month",
            "\t\t\t}",
            "\t\t}",
            f"\t\tset_variable = {{ name = te_tax_next_month value = {month} }}",
            "\t}",
        ]
    lines.append("}")
    return lines


def _history_write():
    lines = [
        "",
        f"# The history ring: {HISTORY_SIZE} entries te_tax_h<n>_*, te_tax_h_head pointing at the newest",
        "# (0 = empty). Advances the head, then overwrites that entry. KIND: the schema doc's",
        "# history kinds; SLOT: none, a or b (stored as te_tax_slot_id_<SLOT>); INST: 1..5 for",
        "# the instrument a sunset executed (INSTRUMENTS order), else 0. Public entry point:",
        "# te_tax_history_push = { KIND SLOT }.",
        "te_tax_gen_history_write = {",
        "\tif = {",
        "\t\tlimit = {",
        "\t\t\tvar:te_tax_h_head >= 1",
        f"\t\t\tvar:te_tax_h_head < {HISTORY_SIZE}",
        "\t\t}",
        "\t\tchange_variable = { name = te_tax_h_head add = 1 }",
        "\t}",
        "\telse = {",
        "\t\tset_variable = { name = te_tax_h_head value = 1 }",
        "\t}",
    ]
    values = (("month", "te_history_month_index"), ("kind", "$KIND$"), ("slot", "te_tax_slot_id_$SLOT$"),
              ("inst", "$INST$"), ("version", "var:te_tax_code_version"))
    for n in range(1, HISTORY_SIZE + 1):
        lines += [f"\t{'if' if n == 1 else 'else_if'} = {{", f"\t\tlimit = {{ var:te_tax_h_head = {n} }}"]
        lines += [f"\t\tset_variable = {{ name = te_tax_h{n}_{field} value = {value} }}" for field, value in values]
        lines.append("\t}")
    lines.append("}")
    return lines


def _scheduler_effects():
    lines = []
    for inst, instrument in enumerate(INSTRUMENTS, start=1):
        lines += _sunset(instrument, inst)
    for slot in SLOTS:
        lines += _commence(slot) + _hold_missed(slot) + _apply(slot) + _store(slot)
    return lines + _next_month() + _history_write()


# ---------------------------------------------------------------------------
# Migration from the vanilla taxation law (docs/systems/tax_code_schema.md, "Migration")
# ---------------------------------------------------------------------------

def _migrate_writes(indices, indent="\t\t"):
    return [f"{indent}set_variable = {{ name = te_tax_en_{instrument.key} value = {indices[instrument.key]} }}"
            for instrument in INSTRUMENTS]


def _migration_effects():
    zeros = {instrument.key: 0 for instrument in INSTRUMENTS}
    carrier = _log("migration_discrepancy",
                   f"holds {CARRIER_LAW} without migration tokens; every rate migrated as 0")
    unknown = _log("migration_discrepancy", "no mapping for the active taxation law; every rate migrated as 0")
    lines = [
        "",
        "# Migration, rates: the enacted indices that reproduce the active vanilla taxation law at",
        "# the country's native tax level, one branch per (law, level) pair (MIGRATION in the",
        "# generator). Every branch writes all five indices. A country already on the carrier",
        "# without tokens (a rebel or a released country that inherited it), or on any other law",
        "# (the probe carrier, another mod's law), migrates as all zeros and is flagged.",
        "# Called only by te_tax_migrate_country.",
        "te_tax_gen_migrate_rates = {",
    ]
    for n, (law, level, indices) in enumerate(migration_indices()):
        lines += [f"\t{'if' if n == 0 else 'else_if'} = {{",
                  f"\t\tlimit = {{ has_law = law_type:{law} tax_level = {level} }}"]
        lines += _migrate_writes(indices)
        lines.append("\t}")
    lines += ["\telse_if = {", f"\t\tlimit = {{ has_law = law_type:{CARRIER_LAW} }}"]
    lines += _migrate_writes(zeros)
    lines += ["\t\tset_variable = { name = te_tax_migration_discrepancy value = 1 }", f"\t\t{carrier}", "\t}"]
    lines.append("\telse = {")
    lines += _migrate_writes(zeros)
    lines += ["\t\tset_variable = { name = te_tax_migration_discrepancy value = 1 }", f"\t\t{unknown}", "\t}"]
    lines += [
        "}",
        "",
        "# Migration, goods: a catalog good is on the enacted list exactly when the country taxes",
        "# it natively. A good outside the catalog is not carried; the first sync removes it.",
        "te_tax_gen_migrate_goods = {",
    ]
    for good in consumption_catalog():
        lines += [
            f"\tif = {{ limit = {{ has_consumption_tax = g:{good} }} "
            f"set_variable = {{ name = te_tax_en_g_{good} value = 1 }} }}",
            f"\telse = {{ set_variable = {{ name = te_tax_en_g_{good} value = 0 }} }}",
        ]
    lines += [
        "\t# A migration is a change made outside legislation.",
        "\tchange_variable = { name = te_tax_xver_goods add = 1 }",
        "}",
        "",
        "# Migration, provisions: a collected instrument is operative from this month; none has",
        "# a sunset or a successor. A migration is a change made outside legislation, so each",
        "# instrument's external-change token moves.",
        "te_tax_gen_migrate_provisions = {",
    ]
    for instrument in INSTRUMENTS:
        en = f"te_tax_en_{instrument.key}"
        lines += [
            "\tif = {",
            f"\t\tlimit = {{ var:{en} > 0 }}",
            f"\t\tset_variable = {{ name = {en}_since value = te_history_month_index }}",
            "\t}",
            "\telse = {",
            f"\t\tset_variable = {{ name = {en}_since value = -1 }}",
            "\t}",
            f"\tset_variable = {{ name = {en}_exp value = -1 }}",
            f"\tset_variable = {{ name = {en}_succ value = -1 }}",
            f"\tchange_variable = {{ name = te_tax_xver_{instrument.key} add = 1 }}",
        ]
    lines.append("}")
    return lines


def _scheduler_triggers():
    lines = []
    for slot in SLOTS:
        p = f"te_tax_p{slot}"
        lines += [
            "",
            f"# Slot {slot}, country scope: the package touches at least one catalog good.",
            f"te_tax_gen_package_touches_goods_{slot} = {{",
            "\tOR = {",
        ]
        lines += [f"\t\tvar:{p}_g_{good} >= 0" for good in consumption_catalog()]
        lines += [
            "\t}",
            "}",
            "",
            f"# Slot {slot}, country scope: every provision group the package touches still has the",
            "# external-change token it had at approval. Only a non-legislative change bumps",
            "# te_tax_xver_*, so expected sunsets and other packages never make it stale.",
            f"te_tax_gen_package_current_{slot} = {{",
        ]
        for instrument in INSTRUMENTS:
            key = instrument.key
            lines += [
                "\tOR = {",
                f"\t\tvar:{p}_{key} < 0",
                f"\t\tvar:{p}_xver_{key} = var:te_tax_xver_{key}",
                "\t}",
            ]
        lines += [
            "\tOR = {",
            f"\t\tNOT = {{ te_tax_gen_package_touches_goods_{slot} = yes }}",
            f"\t\tvar:{p}_xver_goods = var:te_tax_xver_goods",
            "\t}",
            "\tOR = {",
            "\t\tAND = {",
            f"\t\t\tvar:{p}_agrel < 0",
            f"\t\t\tvar:{p}_regrel < 0",
            "\t\t}",
            f"\t\tvar:{p}_xver_relief = var:te_tax_xver_relief",
            "\t}",
            "}",
        ]
    lines += [
        "",
        "# Country scope: every sunset in the bill falls at least one month after commencement.",
        "# te_tax_store_package writes _exp = te_tax_bl_due + te_tax_bl_<key>_sun, so _exp >= _due + 1",
        "# exactly when the offset is at least 1; 0 means no sunset; an untouched provision",
        "# (-1) has none.",
        "te_tax_gen_bill_sunsets_valid = {",
    ]
    for instrument in INSTRUMENTS:
        key = instrument.key
        lines += [
            "\tOR = {",
            f"\t\tvar:te_tax_bl_{key} < 0",
            f"\t\tvar:te_tax_bl_{key}_sun = 0",
            f"\t\tvar:te_tax_bl_{key}_sun >= 1",
            "\t}",
        ]
    lines.append("}")
    return lines


# ---------------------------------------------------------------------------
# Draft, bill and passage (docs/systems/tax_code_schema.md, "Draft, bill and passage")
# ---------------------------------------------------------------------------

def exposure(ig):
    """{key: Decimal} exposure of interest group `ig` to each channel."""
    return dict(zip((instrument.key for instrument in INSTRUMENTS), _values(EXPOSURE[ig])))


def _record_payload(record):
    """[(variable, draft sentinel)] for every per-instrument, per-good and relief field of a record."""
    fields = []
    for instrument in INSTRUMENTS:
        fields += [(f"te_tax_{record}_{instrument.key}{suffix}", sentinel)
                   for suffix, sentinel in RECORD_KEY_FIELDS]
    fields += [(f"te_tax_{record}_g_{good}", -1) for good in consumption_catalog()]
    fields += [(f"te_tax_{record}_goods_pver", -1), (f"te_tax_{record}_agrel", -1),
               (f"te_tax_{record}_regrel", -1)]
    return fields


def _bill_versions():
    """[(bill variable, canonical token)]: the external versions a bill records."""
    pairs = [(f"te_tax_bl_xver_{instrument.key}", f"te_tax_xver_{instrument.key}") for instrument in INSTRUMENTS]
    return pairs + [("te_tax_bl_xver_goods", "te_tax_xver_goods"), ("te_tax_bl_xver_relief", "te_tax_xver_relief")]


def _baseline_slot(record, slot, field, sunsets, indent):
    """Lines overriding the baseline with slot `slot`'s package if it awaits before the record's due month."""
    p, due = f"te_tax_p{slot}_{field}", f"te_tax_{record}_due"
    t = indent
    if not sunsets:
        return [f"{t}if = {{ limit = {{ te_tax_slot_awaits_before = {{ SLOT = {slot} DUE = {due} }} "
                f"has_variable = {p} var:{p} >= 0 }} value = var:{p} }}"]
    lines = [
        f"{t}if = {{",
        f"{t}\tlimit = {{",
        f"{t}\t\tte_tax_slot_awaits_before = {{ SLOT = {slot} DUE = {due} }}",
        f"{t}\t\thas_variable = {p}",
        f"{t}\t\tvar:{p} >= 0",
        f"{t}\t}}",
        f"{t}\tvalue = var:{p}",
    ]
    if sunsets:
        lines += [
            f"{t}\tif = {{",
            f"{t}\t\tlimit = {{",
            f"{t}\t\t\thas_variable = {p}_exp",
            f"{t}\t\t\thas_variable = {p}_succ",
            f"{t}\t\t\tvar:{p}_exp >= 0",
            f"{t}\t\t\tvar:{p}_exp <= var:{due}",
            f"{t}\t\t\tvar:{p}_succ >= 0",
            f"{t}\t\t}}",
            f"{t}\t\tvalue = var:{p}_succ",
            f"{t}\t}}",
        ]
    return lines + [f"{t}}}"]


def _baseline_value(name, record, field, enacted, sunsets):
    """A value: the index (or good flag) in force under existing law in the record's due month."""
    due = f"te_tax_{record}_due"
    lines = [f"{name} = {{", "\tvalue = 0", f"\tif = {{ limit = {{ has_variable = {enacted} }} value = var:{enacted} }}"]
    if sunsets:
        lines += [
            "\t# An enacted sunset falling on or before the due month has run by then.",
            "\tif = {",
            "\t\tlimit = {",
            f"\t\t\thas_variable = {due}",
            f"\t\t\thas_variable = {enacted}_exp",
            f"\t\t\thas_variable = {enacted}_succ",
            f"\t\t\tvar:{enacted}_exp >= 0",
            f"\t\t\tvar:{enacted}_exp <= var:{due}",
            f"\t\t\tvar:{enacted}_succ >= 0",
            "\t\t}",
            f"\t\tvalue = var:{enacted}_succ",
            "\t}",
        ]
    lines += ["\t# Awaiting packages due earlier, in the order they commence.", "\tif = {",
              "\t\tlimit = { te_tax_slot_b_first = yes }"]
    lines += _baseline_slot(record, "b", field, sunsets, "\t\t") + _baseline_slot(record, "a", field, sunsets, "\t\t")
    lines += ["\t}", "\telse = {"]
    lines += _baseline_slot(record, "a", field, sunsets, "\t\t") + _baseline_slot(record, "b", field, sunsets, "\t\t")
    return lines + ["\t}", "}"]


def _clamped(name, terms, weight):
    return ([f"{name} = {{", "\tvalue = 0"] + terms
            + [f"\tmultiply = {weight}", f"\tmin = -{REASON_CAP}", f"\tmax = {REASON_CAP}", "}"])


def _ideology_value(ig):
    lines = [f"te_tax_ideo_p_{ig} = {{", "\tvalue = 0"]
    for law, progressiveness in TAX_LAW_PROGRESSIVENESS:
        if not progressiveness:
            continue
        lines.append(f"\t# {law}, progressiveness {progressiveness}")
        for n, (comparison, stance) in enumerate(STANCE_BRANCHES):
            weight = fmt(Decimal(stance * progressiveness) / 100)
            lines.append(f"\t{'if' if n == 0 else 'else_if'} = {{ limit = {{ ig:ig_{ig} ?= {{ law_stance = "
                         f"{{ law = law_type:{law} {comparison} }} }} }} add = {weight} }}")
    return lines + ["}"]


def _clout_sum(name, committed):
    lines = [f"{name} = {{", "\tvalue = 0"]
    for ig in IGS:
        lines += ["\tif = {", "\t\tlimit = {", f"\t\t\texists = ig:ig_{ig}",
                  f"\t\t\tig:ig_{ig} = {{ ig_counts_as_marginal = no }}"]
        if committed:
            lines += [f"\t\t\thas_variable = te_tax_com_{ig}", f"\t\t\tvar:te_tax_com_{ig} = 1",
                      f"\t\t\thas_variable = te_tax_com_{ig}_rev", "\t\t\thas_variable = te_tax_bl_rev",
                      f"\t\t\tvar:te_tax_com_{ig}_rev = var:te_tax_bl_rev"]
        lines += ["\t\t}", f"\t\tadd = ig:ig_{ig}.ig_clout", "\t}"]
    return lines + ["}"]


@output(SUPPORT_VALUES_PATH)
def support_values():
    keys = [instrument.key for instrument in INSTRUMENTS]
    lines = [
        HEADER,
        "# The legislated tax code's draft, bill and support-model values. Schema and rules:",
        "# docs/systems/tax_code_schema.md, \"Draft, bill and passage\". Country scope. Read by",
        "# te_tax_bill_effects.txt, te_tax_triggers.txt, te_tax_support_values.txt and the support",
        "# refresh (te_tax_gen_refresh_support); every variable read is guarded with has_variable,",
        "# and none writes or iterates anything, so a GUI may read them too.",
        "",
        "# One vanilla tax level per channel, for the support model's delta-levels.",
    ]
    lines += [f"te_tax_level_step_{key} = {fmt(LEVEL_STEPS[key])}" for key in keys]
    lines += [
        "",
        "# te_tax_base_<record>_<key>: the index in force under existing law in the draft's (dr) or",
        "# the bill's (bl) due month: the enacted value, its successor if its sunset falls by then,",
        "# then each awaiting package due earlier (one due on or after it is superseded at",
        "# approval), with that package's own sunset preview. The draft's untouched provisions",
        "# start from it; the bill's support model measures change against it.",
    ]
    for record in RECORDS:
        for key in keys:
            lines += _baseline_value(f"te_tax_base_{record}_{key}", record, key, f"te_tax_en_{key}", True)
    lines += ["", "# te_tax_dr_eff_<key>: the draft's target, or the baseline when the draft leaves it alone."]
    for key in keys:
        lines += [f"te_tax_dr_eff_{key} = {{", f"\tvalue = te_tax_base_dr_{key}",
                  f"\tif = {{ limit = {{ has_variable = te_tax_dr_{key} var:te_tax_dr_{key} >= 0 }} "
                  f"value = var:te_tax_dr_{key} }}", "}"]
    lines += ["", "# te_tax_base_dr_g_<good>: 1 if the good is taxed under existing law in the draft's due month."]
    for good in consumption_catalog():
        lines += _baseline_value(f"te_tax_base_dr_g_{good}", "dr", f"g_{good}", f"te_tax_en_g_{good}", False)
    lines += ["", "# The bill's change per instrument: in index steps (0 if untouched), then in vanilla tax levels."]
    for key in keys:
        lines += [f"te_tax_bl_dstep_{key} = {{", "\tvalue = 0", "\tif = {",
                  f"\t\tlimit = {{ has_variable = te_tax_bl_{key} var:te_tax_bl_{key} >= 0 }}",
                  f"\t\tvalue = var:te_tax_bl_{key}", f"\t\tsubtract = te_tax_base_bl_{key}", "\t}", "}"]
        lines += [f"te_tax_dl_{key} = {{", f"\tvalue = te_tax_bl_dstep_{key}", f"\tmultiply = te_tax_step_{key}",
                  f"\tdivide = te_tax_level_step_{key}", "}"]
    lines += ["", "# Revenue direction: the sum of the changes. Progressivity: income channels minus the rest."]
    lines += ["te_tax_dl_total = {", f"\tvalue = te_tax_dl_{keys[0]}"]
    lines += [f"\tadd = te_tax_dl_{key}" for key in keys[1:]] + ["}"]
    lines += ["te_tax_dl_prog = {", f"\tvalue = te_tax_dl_{keys[0]}"]
    lines += [f"\t{'add' if key in PROGRESSIVE_KEYS else 'subtract'} = te_tax_dl_{key}" for key in keys[1:]]
    lines += ["}", "", "# How many provisions the bill changes.", "te_tax_bl_provisions = {", "\tvalue = 0"]
    lines += [f"\tif = {{ limit = {{ has_variable = te_tax_bl_{key} var:te_tax_bl_{key} >= 0 }} add = 1 }}"
              for key in keys]
    lines += [
        "}",
        "",
        f"# Support reasons per interest group, each clamped to -{REASON_CAP}..{REASON_CAP}. Material:",
        f"# {MATERIAL_WEIGHT} x the exposure-weighted change in tax levels. Ideology: {IDEOLOGY_WEIGHT} x the",
        "# group's fiscal ideology (its stances on the vanilla taxation laws x their progressiveness",
        f"# / 100) x the change in progressivity. Government: +{GOVERNMENT_BONUS} in government.",
    ]
    for ig in IGS:
        terms = [f"\tadd = {{ value = te_tax_dl_{key} multiply = {fmt(weight)} }}"
                 for key, weight in exposure(ig).items() if weight]
        lines += _clamped(f"te_tax_mat_{ig}", terms, MATERIAL_WEIGHT)
        lines += _ideology_value(ig)
        lines += [f"te_tax_ideo_{ig} = {{", f"\tvalue = te_tax_ideo_p_{ig}", "\tmultiply = te_tax_dl_prog",
                  f"\tmultiply = {IDEOLOGY_WEIGHT}", f"\tmin = -{REASON_CAP}", f"\tmax = {REASON_CAP}", "}"]
        lines += [f"te_tax_gov_{ig} = {{", "\tvalue = 0",
                  f"\tif = {{ limit = {{ ig:ig_{ig} ?= {{ is_in_government = yes }} }} value = {GOVERNMENT_BONUS} }}",
                  "}"]
    lines += [
        "",
        "# Clout of the non-marginal interest groups, and of those among them committed to the",
        "# bill's current revision (te_tax_committed_share, te_tax_support_values.txt). A marginal",
        "# group (vanilla's ig_counts_as_marginal) counts in neither; a group the country lacks",
        "# contributes nothing.",
    ]
    lines += _clout_sum("te_tax_eligible_clout", False) + _clout_sum("te_tax_committed_clout", True)
    return _txt("\n".join(lines) + "\n")


def _or_block(conditions, indent="\t"):
    return [f"{indent}OR = {{"] + [f"{indent}\t{condition}" for condition in conditions] + [f"{indent}}}"]


def _bill_triggers():
    keys = [instrument.key for instrument in INSTRUMENTS]
    goods = consumption_catalog()
    lines = [
        "",
        "# Draft, bill and passage (docs/systems/tax_code_schema.md, \"Draft, bill and passage\").",
        "# Country scope. Each reads a record's payload, so callers test te_tax_draft_active /",
        "# te_tax_bill_active (te_tax_triggers.txt) first.",
        "",
        "# The draft changes at least one provision.",
        "te_tax_gen_draft_touches_any = {",
    ]
    lines += _or_block([f"var:te_tax_dr_{key} >= 0" for key in keys]
                       + ["te_tax_gen_draft_touches_goods = yes", "var:te_tax_dr_agrel >= 0",
                          "var:te_tax_dr_regrel >= 0"])
    for record, label in (("dr", "draft"), ("bl", "bill")):
        lines += ["}", "", f"# The {label} changes at least one taxed good.",
                  f"te_tax_gen_{label}_touches_goods = {{"]
        lines += _or_block([f"var:te_tax_{record}_g_{good} >= 0" for good in goods])
    lines += [
        "}",
        "",
        "# Every provision the draft changes still has the planned version it had when first",
        "# touched (te_tax_cmd_draft_rebase acknowledges a change).",
        "te_tax_gen_draft_baseline_current = {",
    ]
    for key in keys:
        lines += _or_block([f"var:te_tax_dr_{key} < 0", f"var:te_tax_dr_{key}_pver = var:te_tax_pver_{key}"])
    lines += _or_block(["NOT = { te_tax_gen_draft_touches_goods = yes }",
                        "var:te_tax_dr_goods_pver = var:te_tax_pver_goods"])
    lines += ["}", "", "# The draft differs from the bill in any field.", "te_tax_gen_draft_differs_from_bill = {"]
    fields = ["due"] + [f"{key}{suffix}" for key in keys for suffix in ("", "_sun")]
    fields += [f"g_{good}" for good in goods] + ["agrel", "regrel"]
    lines += _or_block([f"NOT = {{ var:te_tax_dr_{field} = var:te_tax_bl_{field} }}" for field in fields])
    lines += [
        "}",
        "",
        "# Every provision group the bill touches still has the external version it had when the",
        "# bill was introduced: nothing outside legislation changed it since.",
        "te_tax_gen_bill_current = {",
    ]
    for key in keys:
        lines += _or_block([f"var:te_tax_bl_{key} < 0", f"var:te_tax_bl_xver_{key} = var:te_tax_xver_{key}"])
    lines += _or_block(["NOT = { te_tax_gen_bill_touches_goods = yes }",
                        "var:te_tax_bl_xver_goods = var:te_tax_xver_goods"])
    lines += _or_block(["AND = { var:te_tax_bl_agrel < 0 var:te_tax_bl_regrel < 0 }",
                        "var:te_tax_bl_xver_relief = var:te_tax_xver_relief"])
    lines += ["}", "", "# Every provision the bill changes moves at most two steps from existing law (minor bill).",
              "te_tax_gen_bill_small_steps = {"]
    for key in keys:
        lines += _or_block([f"var:te_tax_bl_{key} < 0",
                            f"AND = {{ te_tax_bl_dstep_{key} <= 2 te_tax_bl_dstep_{key} >= -2 }}"])
    lines.append("}")
    for slot in SLOTS:
        p = f"te_tax_p{slot}"
        lines += ["", f"# Slot {slot}'s package touches a provision the bill touches. Read only while it is on.",
                  f"te_tax_gen_bill_overlaps_{slot} = {{"]
        overlaps = [f"AND = {{ var:te_tax_bl_{key} >= 0 var:{p}_{key} >= 0 }}" for key in keys]
        overlaps += [f"AND = {{ var:te_tax_bl_g_{good} >= 0 var:{p}_g_{good} >= 0 }}" for good in goods]
        overlaps += [f"AND = {{ var:te_tax_bl_{field} >= 0 var:{p}_{field} >= 0 }}" for field in ("agrel", "regrel")]
        lines += _or_block(overlaps)
        lines += [
            "}",
            "",
            f"# Slot {slot}'s package: every provision group it changes still has the planned version",
            "# it had after this package's approval, so no later bill has touched it. Fails closed",
            "# for a package stored before the marks existed.",
            f"te_tax_gen_package_unsuperseded_{slot} = {{",
        ]
        for key in keys:
            mark = f"{p}_pver_{key}"
            lines += _or_block([f"var:{p}_{key} < 0",
                                f"AND = {{ has_variable = {mark} var:{mark} = var:te_tax_pver_{key} }}"])
        lines += _or_block([f"NOT = {{ te_tax_gen_package_touches_goods_{slot} = yes }}",
                            f"AND = {{ has_variable = {p}_pver_goods var:{p}_pver_goods = var:te_tax_pver_goods }}"])
        lines += _or_block([f"AND = {{ var:{p}_agrel < 0 var:{p}_regrel < 0 }}",
                            f"AND = {{ has_variable = {p}_pver_relief var:{p}_pver_relief = var:te_tax_pver_relief }}"])
        lines += ["}", "", f"# Slot {slot}'s package touches nothing (every provision superseded).",
                  f"te_tax_gen_package_empty_{slot} = {{"]
        lines += [f"\tvar:{p}_{key} < 0" for key in keys] + [f"\tvar:{p}_g_{good} < 0" for good in goods]
        lines += [f"\tvar:{p}_agrel < 0", f"\tvar:{p}_regrel < 0", "}"]
    return lines


def _supersede(slot):
    p = f"te_tax_p{slot}"
    superseded = _log("superseded", f"slot={slot}: a later approval replaced provisions due on or after its own")
    withdrawn = _log("superseded", f"slot={slot}: every provision replaced; the slot is free")
    lines = [
        "",
        f"# Slot {slot}: supersession at approval. Called by te_tax_cmd_pass only when the new package",
        f"# goes into the other slot. If slot {slot} holds a package (any state) due on or after the",
        "# bill, every provision, good and relief depth the bill touches is dropped from it, so the",
        "# later-approved law wins. The enacted code and its sunsets are never touched here: the",
        "# enacted provision is superseded when the package commences (te_tax_gen_apply_<slot>).",
        f"# A package left touching nothing is withdrawn. History kind {KIND_SUPERSEDED}.",
        f"te_tax_gen_supersede_{slot} = {{",
        "\tif = {",
        "\t\tlimit = {",
        f"\t\t\tvar:{p}_on = 1",
        f"\t\t\tvar:{p}_due >= var:te_tax_bl_due",
        "\t\t}",
        "\t\t# The payload exists only while the slot is on, so read it nested.",
        "\t\tif = {",
        f"\t\t\tlimit = {{ te_tax_gen_bill_overlaps_{slot} = yes }}",
    ]
    for instrument in INSTRUMENTS:
        key = instrument.key
        lines += [
            "\t\t\tif = {",
            "\t\t\t\tlimit = {",
            f"\t\t\t\t\tvar:te_tax_bl_{key} >= 0",
            f"\t\t\t\t\tvar:{p}_{key} >= 0",
            "\t\t\t\t}",
            f"\t\t\t\tset_variable = {{ name = {p}_{key} value = -1 }}",
            f"\t\t\t\tset_variable = {{ name = {p}_{key}_exp value = -1 }}",
            f"\t\t\t\tset_variable = {{ name = {p}_{key}_succ value = -1 }}",
            "\t\t\t}",
        ]
    lines += [f"\t\t\tif = {{ limit = {{ var:te_tax_bl_g_{good} >= 0 var:{p}_g_{good} >= 0 }} "
              f"set_variable = {{ name = {p}_g_{good} value = -1 }} }}" for good in consumption_catalog()]
    lines += [
        f"\t\t\tif = {{ limit = {{ var:te_tax_bl_agrel >= 0 var:{p}_agrel >= 0 }} "
        f"set_variable = {{ name = {p}_agrel value = -1 }} }}",
        "\t\t\tif = {",
        "\t\t\t\tlimit = {",
        "\t\t\t\t\tvar:te_tax_bl_regrel >= 0",
        f"\t\t\t\t\tvar:{p}_regrel >= 0",
        "\t\t\t\t}",
        f"\t\t\t\tset_variable = {{ name = {p}_regrel value = -1 }}",
        f"\t\t\t\tset_variable = {{ name = {p}_regrel_states_set value = 0 }}",
        "\t\t\t}",
        f"\t\t\tte_tax_history_push = {{ KIND = {KIND_SUPERSEDED} SLOT = {slot} }}",
        f"\t\t\t{superseded}",
        "\t\t\tif = {",
        f"\t\t\t\tlimit = {{ te_tax_gen_package_empty_{slot} = yes }}",
        f"\t\t\t\tset_variable = {{ name = {p}_on value = 0 }}",
        f"\t\t\t\tset_variable = {{ name = {p}_state value = {STATE_EMPTY} }}",
        f"\t\t\t\t{withdrawn}",
        "\t\t\t}",
        "\t\t}",
        "\t}",
        "}",
    ]
    return lines


def _refresh_support():
    lines = [
        "",
        "# The support snapshot (te_tax_refresh_support, while a bill is open): each interest group's",
        "# reasons, its score (their sum, clamped), and its commitment to the bill's current",
        "# revision. A group committed to this revision stays committed; otherwise it commits at",
        "# te_tax_commit_threshold, draws a red line at te_tax_redline_threshold, else is",
        "# persuadable (0). Promises and trust are 0 until Tasks 12-13. A group the country lacks",
        "# is zeroed.",
        "te_tax_gen_refresh_support = {",
    ]
    for ig in IGS:
        sup, com = f"te_tax_sup_{ig}", f"te_tax_com_{ig}"
        sources = {"mat": f"te_tax_mat_{ig}", "ideo": f"te_tax_ideo_{ig}", "fisc": "te_tax_fiscal_reason",
                   "gov": f"te_tax_gov_{ig}", "prom": "0", "trust": "0"}
        lines += ["\tif = {", f"\t\tlimit = {{ exists = ig:ig_{ig} }}"]
        lines += [f"\t\tset_variable = {{ name = te_tax_sr_{ig}_{reason} value = {sources[reason]} }}"
                  for reason in SUPPORT_REASONS]
        lines.append(f"\t\tset_variable = {{ name = {sup} value = var:te_tax_sr_{ig}_mat }}")
        lines += [f"\t\tchange_variable = {{ name = {sup} add = var:te_tax_sr_{ig}_{reason} }}"
                  for reason in SUPPORT_REASONS[1:]]
        lines += [
            f"\t\tclamp_variable = {{ name = {sup} min = -{SCORE_CAP} max = {SCORE_CAP} }}",
            "\t\tif = {",
            f"\t\t\tlimit = {{ NOT = {{ has_variable = {com} }} }}",
            f"\t\t\tset_variable = {{ name = {com} value = 0 }}",
            f"\t\t\tset_variable = {{ name = {com}_rev value = -1 }}",
            "\t\t}",
            "\t\tif = {",
            "\t\t\tlimit = {",
            "\t\t\t\tNOT = {",
            "\t\t\t\t\tAND = {",
            f"\t\t\t\t\t\tvar:{com} = 1",
            f"\t\t\t\t\t\tvar:{com}_rev = var:te_tax_bl_rev",
            "\t\t\t\t\t}",
            "\t\t\t\t}",
            "\t\t\t}",
            f"\t\t\tset_variable = {{ name = {com}_rev value = var:te_tax_bl_rev }}",
            "\t\t\tif = {",
            f"\t\t\t\tlimit = {{ var:{sup} >= te_tax_commit_threshold }}",
            f"\t\t\t\tset_variable = {{ name = {com} value = 1 }}",
            "\t\t\t}",
            "\t\t\telse_if = {",
            f"\t\t\t\tlimit = {{ var:{sup} <= te_tax_redline_threshold }}",
            f"\t\t\t\tset_variable = {{ name = {com} value = -1 }}",
            "\t\t\t}",
            "\t\t\telse = {",
            f"\t\t\t\tset_variable = {{ name = {com} value = 0 }}",
            "\t\t\t}",
            "\t\t}",
            "\t}",
            "\telse = {",
        ]
        lines += [f"\t\tset_variable = {{ name = te_tax_sr_{ig}_{reason} value = 0 }}" for reason in SUPPORT_REASONS]
        lines += [f"\t\tset_variable = {{ name = {sup} value = 0 }}", f"\t\tset_variable = {{ name = {com} value = 0 }}",
                  f"\t\tset_variable = {{ name = {com}_rev value = -1 }}", "\t}"]
    return lines + ["}"]


@output(BILL_EFFECTS_PATH)
def bill_effects():
    keys = [instrument.key for instrument in INSTRUMENTS]
    draft, bill = _record_payload("dr"), _record_payload("bl")
    lines = [
        HEADER,
        "# The legislated tax code's draft and bill records and the passage's per-instrument,",
        "# per-good and per-group parts. Schema and rules: docs/systems/tax_code_schema.md, \"Draft,",
        "# bill and passage\". Country scope; called only by te_tax_bill_effects.txt. Payload is",
        "# removed when its record closes (it is read only while te_tax_dr_on / te_tax_bl_on is 1);",
        "# the two tokens themselves are never removed.",
        "",
        "# A new draft with every field untouched (te_tax_cmd_draft_new sets te_tax_dr_due).",
        "te_tax_gen_draft_init = {",
    ]
    lines += [f"\tset_variable = {{ name = {name} value = {sentinel} }}" for name, sentinel in draft]
    lines += ["}", "", "# A new draft copied from the bill under debate, for its revision.",
              "te_tax_gen_draft_from_bill = {", "\tset_variable = { name = te_tax_dr_due value = var:te_tax_bl_due }"]
    lines += [f"\tset_variable = {{ name = {name} value = var:te_tax_bl_{name[len('te_tax_dr_'):]} }}"
              for name, _ in draft]
    lines += ["}", "", "# Closes the draft's payload (te_tax_dr_on is set to 0 by the caller).",
              "te_tax_gen_draft_clear = {", "\tremove_variable = te_tax_dr_due"]
    lines += [f"\tremove_variable = {name}" for name, _ in draft]
    lines += [
        "}",
        "",
        "# Writes the whole bill record from the draft, every field te_tax_store_package reads, and",
        "# records the external version of each provision group as it stands now. The regional",
        "# relief state list starts empty (Task 11 fills it).",
        "te_tax_gen_bill_from_draft = {",
        "\tset_variable = { name = te_tax_bl_due value = var:te_tax_dr_due }",
    ]
    lines += [f"\tset_variable = {{ name = te_tax_bl_{name[len('te_tax_dr_'):]} value = var:{name} }}"
              for name, _ in draft]
    lines += [f"\tset_variable = {{ name = {name} value = var:{token} }}" for name, token in _bill_versions()]
    lines += ["\tclear_variable_list = te_tax_bl_relief_states", "}", "",
              "# Closes the bill's payload (te_tax_bl_on is set to 0 by the caller).", "te_tax_gen_bill_clear = {"]
    lines += [f"\tremove_variable = te_tax_bl_{field}" for field in ("due", "rev", "day", "minor")]
    lines += [f"\tremove_variable = {name}" for name, _ in bill]
    lines += [f"\tremove_variable = {name}" for name, _ in _bill_versions()]
    lines += ["\tclear_variable_list = te_tax_bl_relief_states", "}"]
    for slot in SLOTS:
        lines += _supersede(slot)
    lines += [
        "",
        "# Planned versions: an approval changes the baseline of every provision group it touches,",
        "# so a draft written against the old one must be rebased before it is introduced.",
        "te_tax_gen_bump_pver = {",
    ]
    for key in keys:
        lines += ["\tif = {", f"\t\tlimit = {{ var:te_tax_bl_{key} >= 0 }}",
                  f"\t\tchange_variable = {{ name = te_tax_pver_{key} add = 1 }}", "\t}"]
    lines += [
        "\tif = {",
        "\t\tlimit = { te_tax_gen_bill_touches_goods = yes }",
        "\t\tchange_variable = { name = te_tax_pver_goods add = 1 }",
        "\t}",
        "\tif = {",
        "\t\tlimit = {",
        "\t\t\tOR = {",
        "\t\t\t\tvar:te_tax_bl_agrel >= 0",
        "\t\t\t\tvar:te_tax_bl_regrel >= 0",
        "\t\t\t}",
        "\t\t}",
        "\t\tchange_variable = { name = te_tax_pver_relief add = 1 }",
        "\t}",
        "}",
        "",
        "# Releases every commitment (a new bill or revision; the bill closing).",
        "te_tax_gen_reset_commitments = {",
    ]
    for ig in IGS:
        lines += [f"\tset_variable = {{ name = te_tax_com_{ig} value = 0 }}",
                  f"\tset_variable = {{ name = te_tax_com_{ig}_rev value = -1 }}"]
    lines.append("}")
    lines += _refresh_support()
    lines += [
        "",
        "# At passage, each group that opposed the bill (score below 0, not committed to this",
        "# revision) disapproves for six months, through the shared ig_approval_effect.",
        "te_tax_gen_oppose_approval = {",
    ]
    for ig in IGS:
        lines += [
            "\tif = {",
            "\t\tlimit = {",
            f"\t\t\thas_variable = te_tax_sup_{ig}",
            f"\t\t\tvar:te_tax_sup_{ig} < 0",
            f"\t\t\thas_variable = te_tax_com_{ig}",
            f"\t\t\tNOT = {{ AND = {{ var:te_tax_com_{ig} = 1 var:te_tax_com_{ig}_rev = var:te_tax_bl_rev }} }}",
            "\t\t}",
            f"\t\tig_approval_effect = {{ IG = ig_{ig} MODIFIER = ig_approval_negative_modifier "
            "DAYS = te_tax_opposed_approval_days }",
            "\t}",
        ]
    lines.append("}")
    return _txt("\n".join(lines) + "\n")


@output(EFFECTS_PATH)
def scripted_effects():
    lines = [
        HEADER,
        "# The legislated tax code's per-instrument and per-good effects. Schema and rules:",
        "# docs/systems/tax_code_schema.md. All country scope.",
        "#",
        "# te_tax_gen_init_*: called by te_tax_init_country (te_tax_state_effects.txt). Each write",
        "# happens only if the variable is absent, so an existing value is never overwritten.",
        "# te_tax_gen_sync_*: called by te_tax_sync_collection (te_tax_collection_effects.txt),",
        "# the only writer of a rule-on country's native tax state, which saves",
        "# scope:te_tax_country and scope:te_tax_sponsor first. Each sync removes what the",
        "# enacted code does not hold and adds what it holds and is missing. Amendment and",
        "# goods changes are not visible later in the same effect, so run each at most once",
        "# per effect execution; a call in a later execution then changes nothing. The",
        "# removal loop never touches the enacted amendment, and the add checks only that one.",
        "# The scheduler's parts follow the syncs: te_tax_gen_sunset_<key>,",
        "# te_tax_gen_commence_<slot>, te_tax_gen_hold_missed_<slot>, te_tax_gen_apply_<slot>,",
        "# te_tax_gen_store_<slot>, te_tax_gen_next_month and te_tax_gen_history_write, called",
        "# by te_tax_schedule_effects.txt. The migration's parts close the file:",
        "# te_tax_gen_migrate_rates, te_tax_gen_migrate_goods and te_tax_gen_migrate_provisions,",
        "# called by te_tax_migrate_country (te_tax_migration_effects.txt).",
        "",
        "# Each instrument's tokens with their sentinels, if absent.",
        "te_tax_gen_init_instruments = {",
    ]
    for instrument in INSTRUMENTS:
        for suffix, sentinel in INSTRUMENT_TOKENS:
            lines.append(_guarded_write(f"te_tax_en_{instrument.key}{suffix}", sentinel))
        for prefix, sentinel in VERSION_TOKENS:
            lines.append(_guarded_write(f"{prefix}{instrument.key}", sentinel))
    lines += ["}", "", "# te_tax_en_g_<good> = 0 for every catalog good, if absent.",
              "te_tax_gen_init_goods = {"]
    lines += [_guarded_write(f"te_tax_en_g_{good}", 0) for good in consumption_catalog()]
    lines.append("}")
    lines += [
        "",
        "# The scheduler's clock, package-slot headers and history ring, if absent. A package's",
        "# payload is not initialised: te_tax_store_package writes all of it, and nothing reads",
        "# it while the slot's te_tax_p<slot>_on is 0.",
        "te_tax_gen_init_schedule = {",
    ]
    lines += [_guarded_write(name, sentinel) for name, sentinel in schedule_tokens()]
    lines.append("}")
    for instrument in INSTRUMENTS:
        key = instrument.key
        lines += [
            "",
            f"# {instrument.label}: leaves exactly amendment_te_tax_{key}_<te_tax_en_{key}> on the",
            "# carrier, and none at index 0.",
            f"te_tax_gen_sync_{key} = {{",
            "\tactive_law:lawgroup_taxation = {",
            "\t\tevery_scope_amendment = {",
            "\t\t\tlimit = {",
            f"\t\t\t\tte_tax_amendment_is_{key} = yes",
            f"\t\t\t\tNOT = {{ te_tax_amendment_matches_{key} = yes }}",
            "\t\t\t}",
            "\t\t\tremove_amendment = yes",
            "\t\t}",
            "\t}",
        ]
        for idx in range(1, instrument.max_idx + 1):
            name = amendment_key(instrument, idx)
            lines += [
                f"\t{'if' if idx == 1 else 'else_if'} = {{",
                f"\t\tlimit = {{ var:te_tax_en_{key} = {idx} }}",
                "\t\tactive_law:lawgroup_taxation = {",
                "\t\t\tif = {",
                f"\t\t\t\tlimit = {{ NOT = {{ has_amendment = amendment_type:{name} }} }}",
                f"\t\t\t\tadd_amendment = {{ type = {name} sponsor = scope:te_tax_sponsor cooldown = 0 }}",
                "\t\t\t}",
                "\t\t}",
                "\t}",
            ]
        lines.append("}")
    lines += [
        "",
        "# Taxed goods: the native consumption-tax list holds a catalog good exactly when",
        "# te_tax_en_g_<good> = 1, and never holds a good outside the catalog, so the native",
        "# taxed set always equals the enacted one.",
        "te_tax_gen_sync_goods = {",
    ]
    for good in consumption_catalog():
        variable = f"var:te_tax_en_g_{good}"
        lines += [
            "\tif = {",
            f"\t\tlimit = {{ {variable} = 1 NOT = {{ has_consumption_tax = g:{good} }} }}",
            f"\t\tadd_taxed_goods = g:{good}",
            "\t}",
            "\telse_if = {",
            f"\t\tlimit = {{ NOT = {{ {variable} = 1 }} has_consumption_tax = g:{good} }}",
            f"\t\tremove_taxed_goods = g:{good}",
            "\t}",
        ]
    lines.append("\t# Goods no pop buys: never on the enacted list, so never natively taxed.")
    lines += [f"\tif = {{ limit = {{ has_consumption_tax = g:{good} }} remove_taxed_goods = g:{good} }}"
              for good in stray_goods()]
    lines.append("}")
    lines += _scheduler_effects() + _migration_effects()
    return _txt("\n".join(lines) + "\n")


@output(TRIGGERS_PATH)
def scripted_triggers():
    lines = [
        HEADER,
        "# Amendment-scope triggers over the generated rate amendments, in the form the tax",
        "# probe used in game (te_debug_tax_effects.txt: `type = amendment_type:<key>`).",
        "# te_tax_amendment_is_<key>: the amendment is one of that instrument's family.",
        "# te_tax_amendment_matches_<key>: it is the one the country's enacted index names.",
        "# The match reads scope:te_tax_country, which the caller saves first",
        "# (te_tax_sync_collection does).",
    ]
    for instrument in INSTRUMENTS:
        key = instrument.key
        names = [amendment_key(instrument, idx) for idx in range(1, instrument.max_idx + 1)]
        lines += ["", f"te_tax_amendment_is_{key} = {{", "\tOR = {"]
        lines += [f"\t\ttype = amendment_type:{name}" for name in names]
        lines += ["\t}", "}", "", f"te_tax_amendment_matches_{key} = {{", "\tOR = {"]
        lines += [f"\t\tAND = {{ type = amendment_type:{name} scope:te_tax_country.var:te_tax_en_{key} = {idx} }}"
                  for idx, name in enumerate(names, start=1)]
        lines += ["\t}", "}"]
    lines += _scheduler_triggers() + _bill_triggers()
    return _txt("\n".join(lines) + "\n")


@output(LOC_PATH)
def localization():
    entries = {}
    for instrument in INSTRUMENTS:
        for idx in range(1, instrument.max_idx + 1):
            key = amendment_key(instrument, idx)
            shown = display(instrument, idx)
            entries[key] = f'0 "{instrument.label.title()} {shown}"'
            entries[f"{key}_desc"] = f'0 "Taxes {instrument.payer} at {shown}."'
    return _render_loc_file([(section_label(LOC_CATEGORY), entries)])


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def render_all():
    validate()
    return {path: function() for path, function in OUTPUTS.items()}


def drifted(root, rendered):
    """The repo-relative paths whose file under `root` is missing or differs."""
    changed = []
    for path, expected in rendered.items():
        try:
            with open(os.path.join(root, path), "rb") as handle:
                actual = handle.read()
        except FileNotFoundError:
            actual = None
        if actual != expected:
            changed.append(path)
    return changed


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--check", action="store_true",
        help="write nothing; exit 1 and list the files that differ from the generator's output",
    )
    parser.add_argument("--root", default=REPO, help="tree to read or write (default: this repo)")
    args = parser.parse_args(argv)

    rendered = render_all()
    changed = drifted(args.root, rendered)
    if args.check:
        if changed:
            print("gen_tax_code.py: generated files differ from the generator's output:")
            for path in changed:
                print(f"  {path}")
            print("Edit the generator and run `python3 scripts/generators/gen_tax_code.py`; "
                  "never edit a generated file by hand.")
            return 1
        print(f"gen_tax_code.py: {len(rendered)} generated files match.")
        return 0
    for path in changed:
        target = os.path.join(args.root, path)
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "wb") as handle:
            handle.write(rendered[path])
        print(f"wrote {path}")
    if not changed:
        print(f"gen_tax_code.py: {len(rendered)} generated files already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
