#!/usr/bin/env python3
"""Write the growth probe's per-building and per-pop mortality reads (TEMPORARY, branch probe/demographics-growth).

    python3 scripts/generators/gen_growth_probe_reads.py

Writes common/scripted_effects/te_debug_growth_reads_generated.txt:
  te_pg_pop_reads             THIS = a pop: adds its curve deaths times each read into te_pg_line's locals.
  te_pg_building_sum_<type>   THIS = a building (a <type> pop's workplace): sums, over every engine building
                              group the building is in (the group itself or any of its descendants, from
                              vanilla's and the mod's building_groups), the group-wide and <type> mortality
                              modifiers it reads into a local, and the working_conditions table's value.
Buildings hold no variables, so nothing is stored on them.

The 69 groups are the ones whose building_group_<group>_mortality_mult keys the engine lists
(modifiers.log); the mod's own groups have no listed keys and are covered through their ancestors.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
import path_constants  # noqa: E402

OUT = ROOT / "common" / "scripted_effects" / "te_debug_growth_reads_generated.txt"
KEYS_OUT = ROOT / "common" / "static_modifiers" / "te_debug_growth_keys_generated.txt"
CARRIER = "0.00001"   # the smallest five-place literal: a key with no source anywhere reads as 'none' and logs
TYPES = ["academics", "aristocrats", "bureaucrats", "capitalists", "clergymen", "clerks", "engineers", "farmers",
         "laborers", "machinists", "officers", "peasants", "shopkeepers", "slaves", "soldiers"]
TABLE_TYPES = ["laborers", "machinists", "engineers", "slaves"]


def registered():
    """Mortality modifier types registered in vanilla's and the mod's modifier_type_definitions. Only these can
    appear in a modifier or be read: modifiers.log lists ~1,100 engine keys, but an unregistered one fails at load
    ("Unknown modifier type") and reads as 'none' on every pop (the v4 run's second flood). Nothing can set an
    unregistered key, so it is 0 everywhere and the probe skips it."""
    reg = set()
    van = Path(path_constants.base_game_path) / "game" / "common" / "modifier_type_definitions"
    for d in (van, ROOT / "common" / "modifier_type_definitions"):
        for f in sorted(d.glob("*.txt")):
            reg |= set(re.findall(r"^(?:INJECT:|REPLACE:)?([a-z_]*mortality[a-z_]*)\s*=\s*\{",
                                  f.read_text(encoding="utf-8-sig", errors="replace"), re.M))
    return reg


def engine_groups():
    log = Path(path_constants.vanilla_docs_path) / "modifiers.log"
    keys = re.findall(r"^building_group_(bg_\w+?)_mortality_mult:", log.read_text(encoding="utf-8", errors="replace"), re.M)
    return sorted(k for k in keys if not any(k.endswith("_" + t) for t in TYPES))


def hierarchy():
    parents = {}
    van = Path(path_constants.base_game_path) / "game" / "common" / "building_groups"
    for d in (van, ROOT / "common" / "building_groups"):
        for f in sorted(d.glob("*.txt")):
            s = re.sub(r"#[^\n]*", "", f.read_text(encoding="utf-8-sig", errors="replace"))
            for m in re.finditer(r"^(?:INJECT:|REPLACE:)?(bg_\w+|te_\w+)\s*=\s*\{(.*?)^\}", s, re.M | re.S):
                p = re.search(r"parent_group\s*=\s*(\w+)", m.group(2))
                parents[m.group(1)] = p.group(1) if p else None
    return parents


def descendants(group, parents):
    out, frontier = [], [group]
    while frontier:
        g = frontier.pop()
        kids = sorted(k for k, p in parents.items() if p == g)
        out += kids
        frontier += kids
    return out


def working_conditions():
    van = Path(path_constants.base_game_path) / "game" / "common" / "static_modifiers" / "00_code_static_modifiers.txt"
    block = re.search(r"^working_conditions\s*=\s*\{(.*?)^\}", van.read_text(encoding="utf-8-sig"), re.M | re.S).group(1)
    rows = []
    for key, val in re.findall(r"building_group_(bg_\w+)_mortality_mult\s*=\s*(-?[\d.]+)", block):
        t = next(t for t in TABLE_TYPES if key.endswith("_" + t))
        rows.append((key[: -len(t) - 1], t, val))
    return rows


def member(group, parents):
    groups = [group] + descendants(group, parents)
    if len(groups) == 1:
        return f"is_building_group = {group}"
    return "OR = { " + " ".join(f"is_building_group = {g}" for g in groups) + " }"


def main():
    reg = registered()
    parents, table = hierarchy(), working_conditions()
    all_groups = engine_groups()
    assert len(all_groups) >= 60, len(all_groups)
    groups = [g for g in all_groups
              if f"building_group_{g}_mortality_mult" in reg or any(f"building_group_{g}_{t}_mortality_mult" in reg for t in TYPES)]
    r = lambda key: key in reg  # noqa: E731
    out = ["# AUTO-GENERATED by scripts/generators/gen_growth_probe_reads.py (temporary growth probe); do not edit.",
           f"# Registered mortality keys only ({len(reg)}); {len(groups)} building groups carry one. working_conditions: {len(table)} rows.",
           "# Buildings hold no variables (scripting_best_practices.md), so the group reads run per pop inside its",
           "# workplace's scope and add into te_pg_line's locals.", ""]
    out.append("# THIS = a pop, inside te_pg_line's walk. ed = its curve deaths a month x 100,000.")
    out.append("te_pg_pop_reads = {")
    out.append("\tchange_local_variable = { name = te_pg_eddn add = { value = te_demog_pop_engine_deaths multiply = dependents divide = { value = total_size min = 1 } } }")
    out.append("\tchange_local_variable = { name = te_pg_edw add = { value = te_demog_pop_engine_deaths multiply = wealth multiply = state.modifier:state_mortality_wealth_mult } }")
    for i, t in enumerate(TYPES):
        out.append(f"\t{'if' if i == 0 else 'else_if'} = {{")
        out.append(f"\t\tlimit = {{ is_pop_type = {t} }}")
        if r(f"state_{t}_mortality_mult"):
            out.append(f"\t\tchange_local_variable = {{ name = te_pg_edcls add = {{ value = te_demog_pop_engine_deaths multiply = state.modifier:state_{t}_mortality_mult }} }}")
        out.append("\t\tif = {")
        out.append("\t\t\tlimit = {")
        out.append("\t\t\t\tis_employed = yes")
        out.append("\t\t\t\texists = workplace")
        out.append("\t\t\t}")
        out.append("\t\t\tchange_local_variable = { name = te_pg_edemp add = te_demog_pop_engine_deaths }")
        if r(f"building_{t}_mortality_mult"):
            out.append(f"\t\t\tchange_local_variable = {{ name = te_pg_edbld add = {{ value = te_demog_pop_engine_deaths multiply = workplace.modifier:building_{t}_mortality_mult }} }}")
        out.append("\t\t\tset_local_variable = { name = te_pg_bsum value = 0 }")
        out.append("\t\t\tset_local_variable = { name = te_pg_btab value = 0 }")
        out.append(f"\t\t\tworkplace = {{ te_pg_building_sum_{t} = yes }}")
        out.append("\t\t\tchange_local_variable = { name = te_pg_edbg add = { value = te_demog_pop_engine_deaths multiply = local_var:te_pg_bsum } }")
        out.append("\t\t\tchange_local_variable = { name = te_pg_edwc add = { value = te_demog_pop_engine_deaths multiply = local_var:te_pg_btab } }")
        out.append("\t\t}")
        out.append("\t}")
    out.append("}")
    out.append("")
    for t in TYPES:
        out.append(f"# THIS = a building, a {t} pop's workplace: its groups' group-wide and {t} mortality reads into")
        out.append("# te_pg_bsum, and the working_conditions table's value into te_pg_btab.")
        out.append(f"te_pg_building_sum_{t} = {{")
        for g in groups:
            terms = [k for k in (f"building_group_{g}_mortality_mult", f"building_group_{g}_{t}_mortality_mult") if r(k)]
            if not terms:
                continue
            out.append("\tif = {")
            out.append(f"\t\tlimit = {{ {member(g, parents)} }}")
            body = " add = ".join(f"modifier:{k}" for k in terms)
            out.append(f"\t\tchange_local_variable = {{ name = te_pg_bsum add = {{ value = {body} }} }}")
            out.append("\t}")
        for g, tt, val in table:
            if tt == t:
                out.append("\tif = {")
                out.append(f"\t\tlimit = {{ {member(g, parents)} }}")
                out.append(f"\t\tchange_local_variable = {{ name = te_pg_btab add = {val} }}")
                out.append("\t}")
        out.append("}")
        out.append("")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8-sig")
    keys = re.findall(r"modifier:(\w+)", "\n".join(out))
    keys += ["state_non_homeland_mortality_mult", "state_mortality_turmoil_mult", "state_mortality_wealth_mult"]
    keys = sorted(set(keys))
    assert all(k in reg for k in keys), sorted(k for k in keys if k not in reg)
    car = ["# AUTO-GENERATED by scripts/generators/gen_growth_probe_reads.py (temporary growth probe); do not edit.",
           "# On every country while the probe runs (te_pg_start): every mortality key the probe reads, at "
           + CARRIER + ".",
           "# Registered keys only: an unregistered key fails at load and reads 'none' on every pop. A registered key",
           "# with no source in a scope may also read 'none', so every country carries each one. Country modifiers",
           "# reach states (probe results Q5) and buildings (the v3 run's working_conditions reads on mines).",
           "te_pg_keys = {",
           "\ticon = gfx/interface/icons/timed_modifier_icons/modifier_gear_positive.dds"]
    car += [f"\t{k} = {CARRIER}" for k in keys]
    car.append("}")
    KEYS_OUT.write_text("\n".join(car) + "\n", encoding="utf-8-sig")
    print(f"wrote {KEYS_OUT.relative_to(ROOT)}: {len(keys)} keys")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(groups)} groups with registered keys, {len(table)} table rows, {len(out)} lines")


if __name__ == "__main__":
    main()
