#!/usr/bin/env python3
"""Write te_region_area_generated.txt: every land state region's area in km².

Script cannot iterate a state's provinces, so the Settlement Authority's
frontier test (docs/superpowers/specs/2026-09-26-internal-resettlement-design.md
§6) reads an area stored on the state region. This counts each province's
pixels in the game's map_data/provinces.png, weights every pixel by its map
row, and sums each region's provinces.

The map is close to equal-area between about 50°N and 50°S (14.5 km² a pixel)
and stretched toward the poles. The row weights below were fitted against
Hokkaido, Île-de-France, Montana, Iceland, Kola, Alaska, Ceylon and New
Zealand's South Island (all within 12%; test_region_area.py pins six).

Needs the Victoria 3 install (provinces.png is not in the repo) and Pillow and
NumPy (system python3 has both; the repo .venv does not). Re-run after a vanilla
map change, and bump VERSION so old saves re-read the table:

    python3 scripts/generators/gen_region_area.py [--png PATH]
"""
import argparse
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO)

VERSION = 1
OUT = os.path.join(REPO, "common", "scripted_effects", "te_region_area_generated.txt")
STATE_REGIONS = os.path.join(REPO, "map_data", "state_regions")
SEA_FILE = "99_seas.txt"

KM2_PER_PIXEL = 14.5       # between about 50°N and 50°S
EQUATOR_ROW = 2040         # the row the stretch is symmetric about
FLAT_HALF_WIDTH = 990      # rows either side of the equator row before the stretch starts
SLOPE_PER_ROW = 0.012      # km² a pixel lost per row beyond that
MIN_KM2_PER_PIXEL = 4.0

BLOCK_RE = re.compile(r"^﻿?(STATE_[A-Z0-9_]+)\s*=\s*\{(.*?)^\}", re.S | re.M)
PROVINCES_RE = re.compile(r"provinces\s*=\s*\{([^}]*)\}")
HEX_RE = re.compile(r'\bx([0-9A-Fa-f]{6})\b')  # quoted or bare — both are valid Paradox script


def land_regions(state_regions_dir=STATE_REGIONS):
    """{region: [province colour as int]} for every land state region."""
    out = {}
    for name in sorted(os.listdir(state_regions_dir)):
        if not name.endswith(".txt") or name == SEA_FILE:
            continue
        with open(os.path.join(state_regions_dir, name), encoding="utf-8-sig") as f:
            text = f.read()
        for m in BLOCK_RE.finditer(text):
            p = PROVINCES_RE.search(m.group(2))
            out[m.group(1)] = [int(h, 16) for h in HEX_RE.findall(p.group(1))] if p else []
    return out


def row_weights(height):
    import numpy as np
    rows = np.arange(height)
    w = KM2_PER_PIXEL - SLOPE_PER_ROW * np.maximum(0, np.abs(rows - EQUATOR_ROW) - FLAT_HALF_WIDTH)
    return np.maximum(w, MIN_KM2_PER_PIXEL)


def province_areas(png_path):
    """{province colour as int: km²}."""
    import numpy as np
    from PIL import Image
    Image.MAX_IMAGE_PIXELS = None
    img = np.asarray(Image.open(png_path).convert("RGB"), dtype=np.uint32)
    height, width, _ = img.shape
    packed = ((img[:, :, 0] << 16) | (img[:, :, 1] << 8) | img[:, :, 2]).ravel()
    weights = np.repeat(row_weights(height), width)
    colours, inverse = np.unique(packed, return_inverse=True)
    sums = np.bincount(inverse, weights=weights)
    return dict(zip(colours.tolist(), sums.tolist()))


def render(areas):
    lines = [
        "# AUTO-GENERATED by scripts/generators/gen_region_area.py — do not edit manually.",
        "# Every land state region's area in km² (row-weighted pixel count of",
        "# map_data/provinces.png). Read by te_region_area_km2",
        "# (common/script_values/resettlement_values.txt). te_region_area_on_action",
        "# runs te_set_region_areas_if_stale; bump VERSION in the generator when the",
        "# table changes so old saves re-read it.",
        "",
        "te_set_region_areas_if_stale = {",
        "\tif = {",
        "\t\tlimit = { NOT = { has_global_variable = te_region_area_version } }",
        "\t\tte_set_region_areas = yes",
        "\t}",
        "\telse_if = {",
        f"\t\tlimit = {{ NOT = {{ global_var:te_region_area_version = {VERSION} }} }}",
        "\t\tte_set_region_areas = yes",
        "\t}",
        "}",
        "",
        "te_set_region_areas = {",
    ]
    for region in sorted(areas):
        lines.append(f"\ts:{region} = {{ set_variable = {{ name = te_region_area value = {areas[region]} }} }}")
    lines.append(f"\tset_global_variable = {{ name = te_region_area_version value = {VERSION} }}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--png", help="path to provinces.png (default: the game install's)")
    args = parser.parse_args()
    png = args.png
    if not png:
        from path_constants import base_game_path
        png = os.path.join(base_game_path, "game", "map_data", "provinces.png")
    by_colour = province_areas(png)
    areas = {}
    for region, colours in land_regions().items():
        areas[region] = max(1, round(sum(by_colour.get(c, 0.0) for c in colours)))
    with open(OUT, "w", encoding="utf-8-sig", newline="\n") as f:
        f.write(render(areas))
    print(f"wrote {len(areas)} regions to {os.path.relpath(OUT, REPO)}")


if __name__ == "__main__":
    main()
