#!/usr/bin/env python3
"""Generate the legislated tax code's rate amendments, script values and loc.

The tax code (docs/superpowers/specs/2026-09-29-legislated-tax-code-design.md)
holds each tax instrument as an integer index: rate = index x step. The carrier
law `law_te_tax_code` collects nothing; one generated amendment per instrument
and index carries the rate, identical in all five native tax levels so that a
level change moves only the political static modifier. INSTRUMENTS below is the
single source of truth for that table.

Outputs (each is registered in OUTPUTS and written byte for byte):

  common/amendments/te_tax_amendments_generated.txt
      amendment_te_tax_<key>_<idx> for every instrument and every idx 1..max.
  common/script_values/te_tax_generated_values.txt
      te_tax_step_<key>, te_tax_max_<key> and te_tax_pct_step_<key> constants.
  localization/english/te_tax_generated_l_english.yml
      A name and a _desc per amendment. organize_loc.py files these keys here
      (category TAX_GENERATED) and renders the file itself, so this script
      renders through organize_loc and the two always agree.
  common/scripted_effects/te_tax_generated_effects.txt
      The collection writer's per-instrument and per-good parts
      (te_tax_gen_sync_<key>, te_tax_gen_sync_goods) and the initialiser's
      (te_tax_gen_init_instruments, te_tax_gen_init_goods).
  common/scripted_triggers/te_tax_generated_triggers.txt
      Amendment-scope family and match triggers the syncs filter on.

The script-value file also carries the guarded te_tax_view_* display values
for every instrument and every catalog good. The consumption-goods catalog is
derived from the pop needs (vanilla_parsed/common/pop_needs.json plus the mod's
common/pop_needs/*.txt) and the goods definitions (vanilla_parsed/common/
goods.json plus common/goods/*.txt), always read from this repo, never --root.
Schema and catalog rule: docs/systems/tax_code_schema.md.

Later tasks register more outputs the same way: write a function returning the
file's bytes and decorate it with @output("<repo-relative path>").

Usage (repo root, system python3; standard library plus the repo's own
organize_loc and paradox_file_parser):

    python3 scripts/generators/gen_tax_code.py            # write the outputs
    python3 scripts/generators/gen_tax_code.py --check    # write nothing; exit 1 on drift
    python3 scripts/generators/gen_tax_code.py --root DIR # another tree (tests)
"""

import argparse
import functools
import glob
import json
import os
import sys
from decimal import Decimal
from typing import NamedTuple

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO)

from organize_loc import _render_loc_file, section_label  # noqa: E402
from paradox_file_parser import ParadoxFileParser  # noqa: E402

HEADER = "# AUTO-GENERATED by scripts/generators/gen_tax_code.py — do not edit manually"
CARRIER_LAW = "law_te_tax_code"
GATE_TRIGGER = "te_tax_code_on"
LOC_CATEGORY = "TAX_GENERATED"
LEVELS = (
    "tax_modifier_very_low", "tax_modifier_low", "tax_modifier_medium",
    "tax_modifier_high", "tax_modifier_very_high",
)

AMENDMENTS_PATH = "common/amendments/te_tax_amendments_generated.txt"
VALUES_PATH = "common/script_values/te_tax_generated_values.txt"
LOC_PATH = "localization/english/te_tax_generated_l_english.yml"
EFFECTS_PATH = "common/scripted_effects/te_tax_generated_effects.txt"
TRIGGERS_PATH = "common/scripted_triggers/te_tax_generated_triggers.txt"

# Catalog inputs, read from REPO (never --root).
VANILLA_POP_NEEDS = "vanilla_parsed/common/pop_needs.json"
VANILLA_GOODS = "vanilla_parsed/common/goods.json"
MOD_POP_NEEDS_GLOB = "common/pop_needs/*.txt"
MOD_GOODS_GLOB = "common/goods/*.txt"

# Per-instrument schema tokens (docs/systems/tax_code_schema.md) and their
# sentinels: te_tax_en_<key><suffix>, then the two version tokens.
INSTRUMENT_TOKENS = (("", 0), ("_since", -1), ("_exp", -1), ("_succ", -1))
VERSION_TOKENS = (("te_tax_pver_", 0), ("te_tax_xver_", 0))


class Instrument(NamedTuple):
    key: str            # short name used in every generated identifier
    modifier: str       # the native tax modifier the amendment carries
    step: Decimal       # rate per index
    max_idx: int        # highest index that gets an amendment
    label: str          # shown to the player (title-cased in loc)
    payer: str          # who pays, as it reads in "Taxes <payer> at <rate>."
    percent: bool       # printed as a percentage (else as a bare amount)
    vanilla: tuple      # every value the five vanilla taxation laws set


def _values(text):
    return tuple(Decimal(value) for value in text.split())


INSTRUMENTS = (
    Instrument("wage", "tax_income_add", Decimal("0.025"), 20, "Wage tax",
               "the wages of employed pops", True,
               _values("0.05 0.075 0.10 0.125 0.15 0.175 0.20 0.25 0.30")),
    Instrument("div", "tax_dividends_add", Decimal("0.025"), 20, "Dividend tax",
               "dividends paid to pops who own private buildings", True,
               _values("0.025 0.05 0.10 0.15 0.20 0.25 0.30")),
    Instrument("land", "tax_land_add", Decimal("0.025"), 48, "Rural assessment",
               "peasants and farmers working agricultural buildings, who then pay no head tax",
               False, _values("0.20 0.275 0.35 0.40 0.425 0.50 0.55 0.70 0.85 1.00")),
    Instrument("head", "tax_per_capita_add", Decimal("0.05"), 30, "Head tax",
               "working adults who pay no rural assessment", False,
               _values("0.40 0.55 0.70 0.85 1.00")),
    Instrument("cons", "tax_consumption_add", Decimal("0.05"), 12, "Consumption tax rate",
               "goods on the taxed-goods list when pops buy them", True,
               _values("0.15 0.20 0.25 0.30 0.35")),
)


def validate(instruments=INSTRUMENTS):
    """Raise ValueError unless every vanilla value is index x step for some index 1..max."""
    for instrument in instruments:
        for value in instrument.vanilla:
            index, remainder = divmod(value, instrument.step)
            if remainder != 0 or not 1 <= index <= instrument.max_idx:
                raise ValueError(
                    f"{instrument.key}: vanilla value {value} is not index x {instrument.step} "
                    f"for an index in 1..{instrument.max_idx}"
                )


def fmt(value):
    """A Decimal without trailing zeros or an exponent: 0.075, 0.1, 1, 10."""
    return format(value.normalize(), "f")


def rate(instrument, idx):
    return instrument.step * idx


def amendment_key(instrument, idx):
    return f"amendment_te_tax_{instrument.key}_{idx}"


def display(instrument, idx):
    """The rate as the player reads it: 7.5% for a rate, 0.425 for an amount."""
    value = rate(instrument, idx)
    return f"{fmt(value * 100)}%" if instrument.percent else fmt(value)


# ---------------------------------------------------------------------------
# Consumption-goods catalog
# ---------------------------------------------------------------------------

_OPERATORS = {"=", "<", ">", "<=", ">=", "!=", "?=", "=="}


def _plain(node):
    """Drop (operator, value) pairs from parser or vanilla_parsed JSON output."""
    if (isinstance(node, (tuple, list)) and len(node) == 2
            and isinstance(node[0], str) and node[0] in _OPERATORS):
        return _plain(node[1])
    if isinstance(node, dict):
        return {key: _plain(value) for key, value in node.items()}
    if isinstance(node, list):
        return [_plain(item) for item in node]
    return node


def _merged(vanilla_json, mod_glob):
    """Vanilla entries overlaid with the mod's files, as the engine loads them.

    REPLACE:x replaces x; INJECT:x overwrites x's fields and appends its
    `entry` blocks (a pop need's repeated key); a plain key the vanilla
    database already holds is dropped ("Duplicated key").
    """
    with open(os.path.join(REPO, vanilla_json), encoding="utf-8") as handle:
        merged = _plain(json.load(handle))
    for path in sorted(glob.glob(os.path.join(REPO, mod_glob))):
        parser = ParadoxFileParser()
        parser.parse_file(path, apply_directives=False)
        for key, body in _plain(parser.data).items():
            directive, _, name = key.rpartition(":")
            if not isinstance(body, dict):
                continue
            if "REPLACE" in directive or (directive and name not in merged and "OR_CREATE" in directive):
                merged[name] = body
            elif "INJECT" in directive and name in merged:
                injected = {**merged[name], **body}
                if "entry" in merged[name] and "entry" in body:
                    injected["entry"] = _as_list(merged[name]["entry"]) + _as_list(body["entry"])
                merged[name] = injected
            elif not directive and name not in merged:
                merged[name] = body
    return merged


def _as_list(value):
    return value if isinstance(value, list) else [value]


@functools.lru_cache(maxsize=None)
def goods_definitions():
    return {name: body for name, body in _merged(VANILLA_GOODS, MOD_GOODS_GLOB).items()
            if isinstance(body, dict)}


@functools.lru_cache(maxsize=None)
def pop_need_goods():
    """{good: (pop need, ...)} for every good some pop need lists as an entry."""
    used = {}
    for need, body in sorted(_merged(VANILLA_POP_NEEDS, MOD_POP_NEEDS_GLOB).items()):
        entries = body.get("entry", []) if isinstance(body, dict) else []
        for entry in _as_list(entries):
            used.setdefault(entry["goods"], []).append(need)
    return {good: tuple(needs) for good, needs in used.items()}


@functools.lru_cache(maxsize=None)
def consumption_catalog():
    """The goods a code can put on the taxed-goods list: every good a pop need buys, sorted.

    A good with no `consumption_tax_cost` costs the engine default
    (DEFAULT_GOODS_TAX_COST = 100, 1.14.5 00_defines.txt) and is still
    taxable: vanilla history taxes liquor, tobacco, opium and wine, none of
    which sets one, and the local goods services, transportation and
    electricity are taxable too.
    """
    goods = goods_definitions()
    for good in pop_need_goods():
        if good not in goods:
            raise ValueError(f"pop need good {good} has no goods definition")
    return tuple(sorted(pop_need_goods()))


def all_goods():
    """Every good defined by vanilla or the mod, sorted."""
    return tuple(sorted(goods_definitions()))


def stray_goods():
    """Goods outside the catalog: no pop buys them, so no code taxes them.

    te_tax_gen_sync_goods removes a native consumption tax on any of these,
    so the native taxed set always equals the enacted one.
    """
    catalog = set(consumption_catalog())
    return tuple(good for good in all_goods() if good not in catalog)


# ---------------------------------------------------------------------------
# Output registry
# ---------------------------------------------------------------------------

OUTPUTS = {}


def output(path):
    """Register a function returning one output file's bytes under its repo-relative path."""
    def register(function):
        OUTPUTS[path] = function
        return function
    return register


def _txt(text):
    """A brace .txt file's bytes: UTF-8 BOM, LF endings."""
    return text.encode("utf-8-sig")


@output(AMENDMENTS_PATH)
def amendments():
    lines = [
        HEADER,
        "# One amendment per instrument and index: rate = index x step (INSTRUMENTS in the generator).",
        f"# {CARRIER_LAW} collects nothing; the amendment attached to it carries the rate. All five",
        "# tax_modifier_* blocks are identical, so a native tax-level change moves only the",
        "# political static modifier. Nothing sponsors, revokes or repeals these on its own.",
    ]
    for instrument in INSTRUMENTS:
        lines += ["", f"# {instrument.label}: {instrument.modifier}, step {fmt(instrument.step)}, "
                      f"indexes 1..{instrument.max_idx}"]
        for idx in range(1, instrument.max_idx + 1):
            value = fmt(rate(instrument, idx))
            if idx > 1:
                lines.append("")
            lines += [
                f"{amendment_key(instrument, idx)} = {{",
                f"\tparent = {CARRIER_LAW}",
                f"\tallowed_laws = {{ {CARRIER_LAW} }}",
                f"\tpossible = {{ {GATE_TRIGGER} = yes }}",
                "\tcan_repeal = { always = no }",
                "\twould_sponsor = { always = no }",
                "\tai_will_revoke = { always = no }",
            ]
            lines += [f"\t{level} = {{ {instrument.modifier} = {value} }}" for level in LEVELS]
            lines.append("}")
    return _txt("\n".join(lines) + "\n")


@output(VALUES_PATH)
def script_values():
    lines = [
        HEADER,
        "# Index encoding for the legislated tax code: rate = index x te_tax_step_<key>, with",
        "# the index from 0 (not set) to te_tax_max_<key>. A display value is written as",
        "# `value = var:<index variable>` `multiply = te_tax_step_<key>`; te_tax_pct_step_<key>",
        "# is the step in percentage points, for the instruments printed as a percentage.",
    ]
    for instrument in INSTRUMENTS:
        lines += [
            "",
            f"te_tax_step_{instrument.key} = {fmt(instrument.step)}",
            f"te_tax_max_{instrument.key} = {instrument.max_idx}",
        ]
        if instrument.percent:
            lines.append(f"te_tax_pct_step_{instrument.key} = {fmt(instrument.step * 100)}")
    lines += [
        "",
        "# Display values (docs/systems/tax_code_schema.md, \"Display values\"): guarded reads of",
        "# the enacted code for the GUI and loc. Each reads only variables it has just tested",
        "# with has_variable and returns the schema sentinel when one is absent: 0 for an index,",
        "# a rate or a flag, -1 for a month or a successor. _y/_mo split a month index into a",
        "# year and a 1-based month, because the GUI cannot divide. They write nothing.",
    ]
    for instrument in INSTRUMENTS:
        lines += [""] + _instrument_views(instrument)
    lines += ["", "# One per catalog good: 1 if the good is on the enacted taxed-goods list."]
    for good in consumption_catalog():
        lines += _guarded_view(f"te_tax_view_en_g_{good}", f"te_tax_en_g_{good}", 0)
    lines += ["", "# How many catalog goods the enacted code taxes.", "te_tax_view_goods_count = {",
              "\tvalue = 0"]
    for good in consumption_catalog():
        variable = f"te_tax_en_g_{good}"
        lines.append(f"\tif = {{ limit = {{ has_variable = {variable} }} add = var:{variable} }}")
    lines.append("}")
    return _txt("\n".join(lines) + "\n")


def _guarded_view(name, variable, default, ops=(), condition=""):
    """A te_tax_view_* value: `default`, or var:`variable` (then `ops`) when it exists."""
    limit = f"has_variable = {variable}" + (f" {condition}" if condition else "")
    if not ops:
        return [f"{name} = {{", f"\tvalue = {default}",
                f"\tif = {{ limit = {{ {limit} }} value = var:{variable} }}", "}"]
    return ([f"{name} = {{", f"\tvalue = {default}", "\tif = {", f"\t\tlimit = {{ {limit} }}",
             f"\t\tvalue = var:{variable}"]
            + [f"\t\t{op}" for op in ops] + ["\t}", "}"])


def _month_views(name, variable):
    """The month, its year and its 1-based calendar month (all -1 when unset)."""
    started = f"var:{variable} >= 0"
    return (_guarded_view(name, variable, -1)
            + _guarded_view(f"{name}_y", variable, -1, ("divide = 12", "floor = yes"), started)
            + _guarded_view(f"{name}_mo", variable, -1,
                            ("divide = 12", "floor = yes", "multiply = -12",
                             f"add = var:{variable}", "add = 1"), started))


def _instrument_views(instrument):
    key = instrument.key
    index = f"te_tax_en_{key}"
    successor = f"te_tax_en_{key}_succ"
    step = f"multiply = te_tax_step_{key}"
    pct = f"multiply = te_tax_pct_step_{key}"
    lines = [f"# {instrument.label}: enacted index, rate (index x step), operative since, sunset, successor."]
    lines += _guarded_view(f"te_tax_view_en_{key}", index, 0)
    lines += _guarded_view(f"te_tax_view_en_{key}_rate", index, 0, (step,))
    if instrument.percent:
        lines += _guarded_view(f"te_tax_view_en_{key}_pct", index, 0, (pct,))
    lines += _month_views(f"te_tax_view_en_{key}_since", f"te_tax_en_{key}_since")
    lines += _month_views(f"te_tax_view_en_{key}_exp", f"te_tax_en_{key}_exp")
    lines += _guarded_view(f"te_tax_view_en_{key}_succ", successor, -1)
    started = f"var:{successor} >= 0"
    lines += _guarded_view(f"te_tax_view_en_{key}_succ_rate", successor, 0, (step,), started)
    if instrument.percent:
        lines += _guarded_view(f"te_tax_view_en_{key}_succ_pct", successor, 0, (pct,), started)
    return lines


def _guarded_write(variable, value, indent="\t"):
    """The init idiom: write `variable` only if it is absent, so nothing is overwritten."""
    return (f"{indent}if = {{ limit = {{ NOT = {{ has_variable = {variable} }} }} "
            f"set_variable = {{ name = {variable} value = {value} }} }}")


@output(EFFECTS_PATH)
def scripted_effects():
    lines = [
        HEADER,
        "# The legislated tax code's per-instrument and per-good effects. Schema and rules:",
        "# docs/systems/tax_code_schema.md. All country scope.",
        "#",
        "# te_tax_gen_init_*: called by te_tax_init_country (te_tax_state_effects.txt). Each write",
        "# happens only if the variable is absent, so an existing value is never overwritten.",
        "# te_tax_gen_sync_*: called by te_tax_sync_collection (te_tax_collection_effects.txt),",
        "# the only writer of a rule-on country's native tax state, which saves",
        "# scope:te_tax_country and scope:te_tax_sponsor first. Each sync removes what the",
        "# enacted code does not hold and adds what it holds and is missing. Amendment and",
        "# goods changes are not visible later in the same effect, so run each at most once",
        "# per effect execution; a call in a later execution then changes nothing. The",
        "# removal loop never touches the enacted amendment, and the add checks only that one.",
        "",
        "# Each instrument's tokens with their sentinels, if absent.",
        "te_tax_gen_init_instruments = {",
    ]
    for instrument in INSTRUMENTS:
        for suffix, sentinel in INSTRUMENT_TOKENS:
            lines.append(_guarded_write(f"te_tax_en_{instrument.key}{suffix}", sentinel))
        for prefix, sentinel in VERSION_TOKENS:
            lines.append(_guarded_write(f"{prefix}{instrument.key}", sentinel))
    lines += ["}", "", "# te_tax_en_g_<good> = 0 for every catalog good, if absent.",
              "te_tax_gen_init_goods = {"]
    lines += [_guarded_write(f"te_tax_en_g_{good}", 0) for good in consumption_catalog()]
    lines.append("}")
    for instrument in INSTRUMENTS:
        key = instrument.key
        lines += [
            "",
            f"# {instrument.label}: leaves exactly amendment_te_tax_{key}_<te_tax_en_{key}> on the",
            "# carrier, and none at index 0.",
            f"te_tax_gen_sync_{key} = {{",
            "\tactive_law:lawgroup_taxation = {",
            "\t\tevery_scope_amendment = {",
            "\t\t\tlimit = {",
            f"\t\t\t\tte_tax_amendment_is_{key} = yes",
            f"\t\t\t\tNOT = {{ te_tax_amendment_matches_{key} = yes }}",
            "\t\t\t}",
            "\t\t\tremove_amendment = yes",
            "\t\t}",
            "\t}",
        ]
        for idx in range(1, instrument.max_idx + 1):
            name = amendment_key(instrument, idx)
            lines += [
                f"\t{'if' if idx == 1 else 'else_if'} = {{",
                f"\t\tlimit = {{ var:te_tax_en_{key} = {idx} }}",
                "\t\tactive_law:lawgroup_taxation = {",
                "\t\t\tif = {",
                f"\t\t\t\tlimit = {{ NOT = {{ has_amendment = amendment_type:{name} }} }}",
                f"\t\t\t\tadd_amendment = {{ type = {name} sponsor = scope:te_tax_sponsor cooldown = 0 }}",
                "\t\t\t}",
                "\t\t}",
                "\t}",
            ]
        lines.append("}")
    lines += [
        "",
        "# Taxed goods: the native consumption-tax list holds a catalog good exactly when",
        "# te_tax_en_g_<good> = 1, and never holds a good outside the catalog, so the native",
        "# taxed set always equals the enacted one.",
        "te_tax_gen_sync_goods = {",
    ]
    for good in consumption_catalog():
        variable = f"var:te_tax_en_g_{good}"
        lines += [
            "\tif = {",
            f"\t\tlimit = {{ {variable} = 1 NOT = {{ has_consumption_tax = g:{good} }} }}",
            f"\t\tadd_taxed_goods = g:{good}",
            "\t}",
            "\telse_if = {",
            f"\t\tlimit = {{ NOT = {{ {variable} = 1 }} has_consumption_tax = g:{good} }}",
            f"\t\tremove_taxed_goods = g:{good}",
            "\t}",
        ]
    lines.append("\t# Goods no pop buys: never on the enacted list, so never natively taxed.")
    lines += [f"\tif = {{ limit = {{ has_consumption_tax = g:{good} }} remove_taxed_goods = g:{good} }}"
              for good in stray_goods()]
    lines.append("}")
    return _txt("\n".join(lines) + "\n")


@output(TRIGGERS_PATH)
def scripted_triggers():
    lines = [
        HEADER,
        "# Amendment-scope triggers over the generated rate amendments, in the form the tax",
        "# probe used in game (te_debug_tax_effects.txt: `type = amendment_type:<key>`).",
        "# te_tax_amendment_is_<key>: the amendment is one of that instrument's family.",
        "# te_tax_amendment_matches_<key>: it is the one the country's enacted index names.",
        "# The match reads scope:te_tax_country, which the caller saves first",
        "# (te_tax_sync_collection does).",
    ]
    for instrument in INSTRUMENTS:
        key = instrument.key
        names = [amendment_key(instrument, idx) for idx in range(1, instrument.max_idx + 1)]
        lines += ["", f"te_tax_amendment_is_{key} = {{", "\tOR = {"]
        lines += [f"\t\ttype = amendment_type:{name}" for name in names]
        lines += ["\t}", "}", "", f"te_tax_amendment_matches_{key} = {{", "\tOR = {"]
        lines += [f"\t\tAND = {{ type = amendment_type:{name} scope:te_tax_country.var:te_tax_en_{key} = {idx} }}"
                  for idx, name in enumerate(names, start=1)]
        lines += ["\t}", "}"]
    return _txt("\n".join(lines) + "\n")


@output(LOC_PATH)
def localization():
    entries = {}
    for instrument in INSTRUMENTS:
        for idx in range(1, instrument.max_idx + 1):
            key = amendment_key(instrument, idx)
            shown = display(instrument, idx)
            entries[key] = f'0 "{instrument.label.title()} {shown}"'
            entries[f"{key}_desc"] = f'0 "Taxes {instrument.payer} at {shown}."'
    return _render_loc_file([(section_label(LOC_CATEGORY), entries)])


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def render_all():
    validate()
    return {path: function() for path, function in OUTPUTS.items()}


def drifted(root, rendered):
    """The repo-relative paths whose file under `root` is missing or differs."""
    changed = []
    for path, expected in rendered.items():
        try:
            with open(os.path.join(root, path), "rb") as handle:
                actual = handle.read()
        except FileNotFoundError:
            actual = None
        if actual != expected:
            changed.append(path)
    return changed


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--check", action="store_true",
        help="write nothing; exit 1 and list the files that differ from the generator's output",
    )
    parser.add_argument("--root", default=REPO, help="tree to read or write (default: this repo)")
    args = parser.parse_args(argv)

    rendered = render_all()
    changed = drifted(args.root, rendered)
    if args.check:
        if changed:
            print("gen_tax_code.py: generated files differ from the generator's output:")
            for path in changed:
                print(f"  {path}")
            print("Edit the generator and run `python3 scripts/generators/gen_tax_code.py`; "
                  "never edit a generated file by hand.")
            return 1
        print(f"gen_tax_code.py: {len(rendered)} generated files match.")
        return 0
    for path in changed:
        target = os.path.join(args.root, path)
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "wb") as handle:
            handle.write(rendered[path])
        print(f"wrote {path}")
    if not changed:
        print(f"gen_tax_code.py: {len(rendered)} generated files already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
