#!/usr/bin/env python3
"""Write the demographics script that mirrors scripts/analysis/demographics_model.py.

Usage:
    python3 scripts/generators/gen_demographics.py            # write the two files
    python3 scripts/generators/gen_demographics.py --check    # exit 1 if either is stale

Spec: docs/superpowers/specs/2026-10-08-demographics-design.md; plan:
docs/superpowers/plans/2026-10-08-demographics-phases-0-1.md (Task 6). Inputs:
scripts/analysis/demographics_params.py (every rate, weight and table),
common/defines/extra_defines.txt (the engine's growth curves, through pop_growth.py),
common/buy_packages/00_buy_packages.txt (spending per head by wealth) and the land-reform
laws (vanilla_parsed/common/laws.json and common/laws/, for variants' parents). Not a post-load
regenerator: run it after changing any of those; test_gen_demographics.py fails CI when
the committed files are stale.

What it writes (the hand-written logic is in te_demog_effects.txt / te_demog_values.txt):
    common/scripted_effects/te_demog_generated_effects.txt
        te_demog_sweep, te_demog_seed_sweep     the ring in age order, two guarded passes
        te_demog_enter_group                    a group's death rates, fertility, next start
        te_demog_flush_band, te_demog_flush_class
        te_demog_enter_class                    a migrant class's gain and loss shares (reads te_dg_acls,
                                                te_dg_mig_in/_out, te_dg_pf<c>/pm<c>, var:te_dg_cf<c>/cm<c>;
                                                writes te_dg_mig_gain_f/_m, te_dg_mig_frac_f/_m)
        te_demog_life_table, te_demog_set_growth_factor
        te_demog_add_bands_to_root, te_demog_reset_country_bands, te_demog_scale_bands
        te_demog_debug_log_ring_before / _after  (Task 15's replay lines)
    common/script_values/te_demog_generated_values.txt
        per-pop engine curves, wealth TFR and income; per-state cause multipliers,
        women's work share, the means and the land-tenure term; te_demog_k_* constants;
        per-slot debug shares
"""

import argparse
import sys
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts" / "analysis"))
sys.path.insert(0, str(ROOT))

import demographics_model as M  # noqa: E402
import demographics_params as P  # noqa: E402
import pop_growth as G  # noqa: E402

EFFECTS = Path("common/scripted_effects/te_demog_generated_effects.txt")
VALUES = Path("common/script_values/te_demog_generated_values.txt")
BUY_PACKAGES = Path("common/buy_packages/00_buy_packages.txt")
HEADER = ("# AUTO-GENERATED by scripts/generators/gen_demographics.py - do not edit manually.\n"
          "# docs/superpowers/specs/2026-10-08-demographics-design.md; parameters in\n"
          "# scripts/analysis/demographics_params.py.\n")
N = P.RING_YEARS
INCOME_KNOTS = [1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
NRR_KNOTS = [round(0.2 + 0.1 * i, 1) for i in range(39)]          # 0.2 .. 4.0
CAUSES = ("infection", "work", "external", "maternal", "chronic")


def lit(x):
    """A script literal: at most five decimals, no trailing zeros."""
    d = Decimal(repr(float(x))).quantize(Decimal("0.00001"), rounding=ROUND_HALF_UP)
    text = format(d.normalize(), "f")
    return "0" if text in ("-0", "") else text


class Out:
    """Tab-indented text that matches scripts/format_paradox_tabs.py."""

    def __init__(self):
        self.lines = []
        self.depth = 0

    def __call__(self, text=""):
        for raw in text.split("\n"):
            line = raw.strip()
            if not line:
                self.lines.append("")
                continue
            if line.startswith("}"):
                self.depth -= 1
            self.lines.append("\t" * self.depth + line)
            self.depth += line.count("{") - line.count("}") + (1 if line.startswith("}") else 0)

    def text(self):
        assert self.depth == 0, self.depth
        return "\n".join(self.lines).rstrip("\n") + "\n"


def tree(o, var, lo, hi, leaf):
    """A balanced if/else tree on local_var:<var> over lo..hi; leaf(o, i) writes branch i."""
    if lo == hi:
        leaf(o, lo)
        return
    mid = (lo + hi) // 2
    o("if = {")
    o(f"limit = {{ local_var:{var} <= {mid} }}")
    tree(o, var, lo, mid, leaf)
    o("}")
    o("else = {")
    tree(o, var, mid + 1, hi, leaf)
    o("}")


# ---- effects ------------------------------------------------------------------------

def sweeps(o):
    o("# The yearly step's sweep: pass 1 visits slots open-1 .. 0 (ages 1 .. open), pass 2")
    o("# slots 149 .. open (ages open+1 .. 150), so te_demog_slot sees ages in order.")
    o("te_demog_sweep = {")
    for k in range(N - 1, -1, -1):
        o(f"te_demog_slot_p1 = {{ S = {k} }}")
    for k in range(N - 1, -1, -1):
        o(f"te_demog_slot_p2 = {{ S = {k} }}")
    o("}")
    o("")
    o("# The seed's sweep: ages 0 .. open, then open+1 .. 149.")
    o("te_demog_seed_sweep = {")
    for k in range(N - 1, -1, -1):
        o(f"te_demog_seed_p1 = {{ S = {k} }}")
    for k in range(N - 1, -1, -1):
        o(f"te_demog_seed_p2 = {{ S = {k} }}")
    o("}")
    o("")


def _rate(o, name, terms):
    terms = [(m, v) for m, v in terms if v]
    o("set_local_variable = {")
    o(f"name = {name}")
    if not terms:
        o("value = 0")
    else:
        o("value = {")
        (m0, v0), rest = terms[0], terms[1:]
        o(f"value = local_var:{m0}")
        o(f"multiply = {lit(v0)}")
        for m, v in rest:
            o("add = {")
            o(f"value = local_var:{m}")
            o(f"multiply = {lit(v)}")
            o("}")
        o("max = 100000")
        o("}")
    o("}")


def enter_group(o):
    o("# THIS = a state. local_var:te_dg_g = the age group (demographics_params.GROUPS); sets")
    o("# te_dg_qf / te_dg_qm (death probability a year per 100,000), te_dg_asfr (share of a")
    o("# lifetime's births at each single age, per 100,000) and te_dg_next_group (the next")
    o("# group's first age) from the cause multipliers te_dg_m_inf, te_dg_m_work_f,")
    o("# te_dg_m_work_m, te_dg_m_ext and te_dg_m_chr (te_demog_prepare).")
    o("te_demog_enter_group = {")

    def leaf(o, g):
        _rate(o, "te_dg_qf", [("te_dg_m_inf", P.INFECTION["f"][g]), ("te_dg_m_work_f", P.WORK_BASE[g]),
                              ("te_dg_m_ext", P.EXTERNAL["f"][g]), ("te_dg_m_chr", P.CHRONIC["f"][g])])
        _rate(o, "te_dg_qm", [("te_dg_m_inf", P.INFECTION["m"][g]), ("te_dg_m_work_m", P.WORK_BASE[g]),
                              ("te_dg_m_ext", P.EXTERNAL["m"][g]), ("te_dg_m_chr", P.CHRONIC["m"][g])])
        start = P.GROUPS[g][0]
        o(f"set_local_variable = {{ name = te_dg_asfr value = {lit(M.asfr_shape(start))} }}")
        nxt = P.GROUPS[g + 1][0] if g + 1 < len(P.GROUPS) else 999
        o(f"set_local_variable = {{ name = te_dg_next_group value = {nxt} }}")

    tree(o, "te_dg_g", 0, len(P.GROUPS) - 1, leaf)
    o("}")
    o("")


def bands_and_classes(o):
    o("# THIS = a state. Writes the running band sums into band local_var:te_dg_band.")
    o("te_demog_flush_band = {")
    tree(o, "te_dg_band", 0, P.BANDS - 1, lambda o, b: (
        o(f"set_variable = {{ name = te_dg_bf{b} value = local_var:te_dg_acc_bf }}"),
        o(f"set_variable = {{ name = te_dg_bm{b} value = local_var:te_dg_acc_bm }}")))
    o("}")
    o("")
    o("# THIS = a state. Writes the running class sums into class local_var:te_dg_cls.")
    o("te_demog_flush_class = {")
    tree(o, "te_dg_cls", 0, len(P.MIGRANT_CLASSES) - 1, lambda o, c: (
        o(f"set_variable = {{ name = te_dg_cf{c} value = local_var:te_dg_acc_cf }}"),
        o(f"set_variable = {{ name = te_dg_cm{c} value = local_var:te_dg_acc_cm }}")))
    o("}")
    o("")
    o("# THIS = a state. On entering the migrant class of local_var:te_dg_acls (the class of the")
    o("# RATE age, a - 1): the share of the class's arrivals (te_dg_mig_gain_f / _m) and departures")
    o("# (te_dg_mig_frac_f / _m) that falls on one cohort of it, from the profile (te_dg_pf<c> /")
    o("# te_dg_pm<c>), te_dg_mig_in / te_dg_mig_out and last year's class sums. Both are zero for a")
    o("# class whose last-year sum is under one person.")
    o("te_demog_enter_class = {")

    def leaf(o, c):
        for sex, prof, last in (("f", f"te_dg_pf{c}", f"te_dg_cf{c}"), ("m", f"te_dg_pm{c}", f"te_dg_cm{c}")):
            share = f"divide = {{ value = var:{last} min = 1 }}"
            o(f"set_local_variable = {{ name = te_dg_mig_gain_{sex} value = 0 }}")
            o(f"set_local_variable = {{ name = te_dg_mig_frac_{sex} value = 0 }}")
            o("if = {")
            o(f"limit = {{ var:{last} >= 1 }}")
            o("set_local_variable = {")
            o(f"name = te_dg_mig_gain_{sex}")
            o(f"value = {{ value = local_var:te_dg_mig_in multiply = local_var:{prof} {share} }}")
            o("}")
            o("set_local_variable = {")
            o(f"name = te_dg_mig_frac_{sex}")
            o(f"value = {{ value = local_var:te_dg_mig_out multiply = local_var:{prof} {share} }}")
            o("}")
            o("}")
    tree(o, "te_dg_acls", 0, len(P.MIGRANT_CLASSES) - 1, leaf)
    o("}")
    o("")


def life_table(o):
    o("# THIS = a state. The life table over the age groups in order (demographics_model.life_table),")
    o("# plus the NRR's survival-weighted fertility sum. Needs te_dg_m_* (te_demog_prepare).")
    o("te_demog_life_table = {")
    o("set_local_variable = { name = te_dg_lf value = 100000 }")
    o("set_local_variable = { name = te_dg_lm value = 100000 }")
    o("set_local_variable = { name = te_dg_pyf value = 0 }")
    o("set_local_variable = { name = te_dg_pym value = 0 }")
    o("set_local_variable = { name = te_dg_nrr_sum value = 0 }")
    for g, (start, width) in enumerate(P.GROUPS):
        o(f"set_local_variable = {{ name = te_dg_g value = {g} }}")
        o("te_demog_enter_group = yes")
        if start == 65:
            o("set_local_variable = { name = te_dg_l65f value = local_var:te_dg_lf }")
            o("set_local_variable = { name = te_dg_l65m value = local_var:te_dg_lm }")
            o("set_local_variable = { name = te_dg_py65f value = local_var:te_dg_pyf }")
            o("set_local_variable = { name = te_dg_py65m value = local_var:te_dg_pym }")
        if g == 0:
            o("set_variable = { name = te_dg_imr value = { value = local_var:te_dg_qf add = local_var:te_dg_qm "
              "divide = 200 } }")
        fertile = 15 <= start <= 45
        o(f"te_demog_lt_group = {{ N = {width} FERTILE = {'yes' if fertile else 'no'} }}")
    o("te_demog_lt_finish = yes")
    o("}")
    o("")


def growth_factor(o):
    o("# THIS = a state. local_var:te_dg_nrr -> local_var:te_dg_d = NRR^(-1/29), the stable")
    o("# population's yearly factor (demographics_model.growth_factor), linear between knots.")
    o("te_demog_set_growth_factor = {")
    o("if = {")
    o(f"limit = {{ local_var:te_dg_nrr <= {NRR_KNOTS[0]} }}")
    o(f"set_local_variable = {{ name = te_dg_d value = {lit(M.growth_factor(NRR_KNOTS[0]))} }}")
    o("}")
    o("else_if = {")
    o(f"limit = {{ local_var:te_dg_nrr >= {NRR_KNOTS[-1]} }}")
    o(f"set_local_variable = {{ name = te_dg_d value = {lit(M.growth_factor(NRR_KNOTS[-1]))} }}")
    o("}")
    o("else = {")
    o("set_local_variable = {")
    o("name = te_dg_knot")
    o(f"value = {{ value = local_var:te_dg_nrr subtract = {NRR_KNOTS[0]} multiply = 10 floor = yes }}")
    o("}")

    def leaf(o, i):
        x0, x1 = NRR_KNOTS[i], NRR_KNOTS[i + 1]
        d0, d1 = M.growth_factor(x0), M.growth_factor(x1)
        o("set_local_variable = {")
        o("name = te_dg_d")
        o(f"value = {{ value = local_var:te_dg_nrr subtract = {x0} multiply = {lit((d1 - d0) / (x1 - x0))} "
          f"add = {lit(d0)} }}")
        o("}")
    tree(o, "te_dg_knot", 0, len(NRR_KNOTS) - 2, leaf)
    o("}")
    o("}")
    o("")


def country_bands(o):
    o("# THIS = a state, ROOT = its owner on the yearly country pulse: add the state's bands.")
    o("te_demog_add_bands_to_root = {")
    for b in range(P.BANDS):
        for s in ("f", "m"):
            o(f"set_local_variable = {{ name = te_dg_t value = var:te_dg_b{s}{b} }}")
            o(f"root = {{ change_variable = {{ name = te_dg_cb{s}{b} add = local_var:te_dg_t }} }}")
    o("}")
    o("")
    o("# THIS = a country: zero its band sums before the states add theirs.")
    o("te_demog_reset_country_bands = {")
    for b in range(P.BANDS):
        o(f"set_variable = {{ name = te_dg_cbf{b} value = 0 }}")
        o(f"set_variable = {{ name = te_dg_cbm{b} value = 0 }}")
    o("}")
    o("")
    o("# THIS = a state: multiply the bands and class sums by local_var:te_dg_new_scale.")
    o("te_demog_scale_bands = {")
    for b in range(P.BANDS):
        for s in ("f", "m"):
            o(f"change_variable = {{ name = te_dg_b{s}{b} multiply = local_var:te_dg_new_scale }}")
    for c in range(len(P.MIGRANT_CLASSES)):
        for s in ("f", "m"):
            o(f"change_variable = {{ name = te_dg_c{s}{c} multiply = local_var:te_dg_new_scale }}")
    o("}")
    o("")


def debug_ring(o):
    for when in ("before", "after"):
        o(f"# THIS = a state: the ring as TE_DEMOG_REPLAY {when} lines (demographics_harness.format_replay).")
        o(f"te_demog_debug_log_ring_{when} = {{")
        for first in range(0, N, 10):
            f = ",".join(f"[THIS.ScriptValue('te_demog_dbg_f{k}')|5]" for k in range(first, first + 10))
            m = ",".join(f"[THIS.ScriptValue('te_demog_dbg_m{k}')|5]" for k in range(first, first + 10))
            extra = ""
            if first == 0:
                extra = (" pool_f=[THIS.ScriptValue('te_demog_dbg_pool_f')|5]"
                         " pool_m=[THIS.ScriptValue('te_demog_dbg_pool_m')|5]"
                         " pool_age=[THIS.Var('te_dg_pa').GetValue|5]")
            o(f'debug_log = "TE_DEMOG_REPLAY {when} from={first} f={f} m={m}{extra}"')
        o("}")
        o("")


def profile(o):
    o("# THIS = a state. The migrant profile (demographics_model.migrant_profile): from the kinds'")
    o("# weights te_dg_labour, te_dg_family, te_dg_refugee and labour's women's share")
    o("# te_dg_labour_f, each class's share for women (te_dg_pf<c>) and men (te_dg_pm<c>).")
    o("te_demog_set_profile = {")
    for c in range(len(P.MIGRANT_CLASSES)):
        lw = P.MIGRANT_PROFILE["labour"]["weights"][c]
        fw = P.MIGRANT_PROFILE["family"]["weights"][c]
        rw = P.MIGRANT_PROFILE["refugee"]["weights"][c]
        both = (f"add = {{ value = local_var:te_dg_family multiply = {lit(fw * 0.5)} }} "
                f"add = {{ value = local_var:te_dg_refugee multiply = {lit(rw * 0.5)} }}")
        o(f"set_local_variable = {{ name = te_dg_pf{c} value = {{ value = local_var:te_dg_labour "
          f"multiply = {lit(lw)} multiply = local_var:te_dg_labour_f {both} }} }}")
        o(f"set_local_variable = {{ name = te_dg_pm{c} value = {{ value = 1 subtract = local_var:te_dg_labour_f "
          f"multiply = local_var:te_dg_labour multiply = {lit(lw)} {both} }} }}")
    o("}")
    o("")


def band_figures(o):
    young = range(0, 3)
    working = range(3, 13)
    o("# THIS = a state or a country; $B$ = the band variables' prefix (te_dg_b or te_dg_cb).")
    o("# Sets locals te_dg_total, te_dg_young, te_dg_working, te_dg_old (0-14, 15-64, 65+),")
    o("# te_dg_w1549 (women 15-49), te_dg_w2059 and te_dg_m2059 (20-59), then te_dg_median.")
    o("te_demog_band_figures = {")
    for name in ("total", "young", "working", "old", "w1549", "w2059", "m2059"):
        o(f"set_local_variable = {{ name = te_dg_{name} value = 0 }}")
    for b in range(P.BANDS):
        o(f"set_local_variable = {{ name = te_dg_t value = {{ value = var:$B$f{b} add = var:$B$m{b} }} }}")
        o("change_local_variable = { name = te_dg_total add = local_var:te_dg_t }")
        group = "young" if b in young else "working" if b in working else "old"
        o(f"change_local_variable = {{ name = te_dg_{group} add = local_var:te_dg_t }}")
        if 3 <= b <= 9:
            o(f"change_local_variable = {{ name = te_dg_w1549 add = var:$B$f{b} }}")
        if 4 <= b <= 11:
            o(f"change_local_variable = {{ name = te_dg_w2059 add = var:$B$f{b} }}")
            o(f"change_local_variable = {{ name = te_dg_m2059 add = var:$B$m{b} }}")
    o("# the median: the band where the running sum passes half, interpolated inside it")
    o("set_local_variable = { name = te_dg_half value = { value = local_var:te_dg_total multiply = 0.5 } }")
    o("set_local_variable = { name = te_dg_run value = 0 }")
    o("set_local_variable = { name = te_dg_median value = -1 }")
    for b in range(P.BANDS):
        width = P.BAND_WIDTH if b < P.BANDS - 1 else 15
        o("if = {")
        o("limit = { local_var:te_dg_median < 0 }")
        o(f"set_local_variable = {{ name = te_dg_t value = {{ value = var:$B$f{b} add = var:$B$m{b} }} }}")
        o("set_local_variable = { name = te_dg_run2 value = { value = local_var:te_dg_run add = local_var:te_dg_t } }")
        o("if = {")
        o("limit = { local_var:te_dg_run2 >= local_var:te_dg_half }")
        o(f"set_local_variable = {{ name = te_dg_median value = {{ value = local_var:te_dg_half "
          f"subtract = local_var:te_dg_run divide = {{ value = local_var:te_dg_t min = 0.00001 }} "
          f"multiply = {width} add = {b * P.BAND_WIDTH} }} }}")
        o("}")
        o("change_local_variable = { name = te_dg_run add = local_var:te_dg_t }")
        o("}")
    o("}")
    o("")


def projection(o):
    """Twenty years ahead in four five-year steps on the bands (spec 10's outline)."""
    o("# THIS = a country (the player's). From the country's band sums te_dg_cb* and its average")
    o("# rates (te_dg_m_* locals, local_var:te_dg_tfr): te_dg_pjf<b> / te_dg_pjm<b>, the bands")
    o("# twenty years ahead. Five-year survival per band from its age group; births from women")
    o("# 15-49 at their group's fertility. A display outline, not the model's step.")
    o("te_demog_project = {")
    for b in range(P.BANDS):
        start = b * P.BAND_WIDTH
        g = P.group_of(start) if b > 0 else 1
        o(f"set_local_variable = {{ name = te_dg_g value = {g} }}")
        o("te_demog_enter_group = yes")
        for s in ("f", "m"):
            o(f"set_local_variable = {{ name = te_dg_s{s}{b} value = {{ value = 1 subtract = "
              f"{{ value = local_var:te_dg_q{s} divide = 100000 }} }} }}")
            o(f"set_local_variable = {{ name = te_dg_t value = local_var:te_dg_s{s}{b} }}")
            o(f"while = {{ count = 4 change_local_variable = {{ name = te_dg_s{s}{b} multiply = local_var:te_dg_t }} }}")
        o(f"set_local_variable = {{ name = te_dg_fert{b} value = {{ value = local_var:te_dg_asfr multiply = 5 "
          f"divide = 100000 multiply = local_var:te_dg_tfr }} }}")
        o(f"set_local_variable = {{ name = te_dg_xf{b} value = var:te_dg_cbf{b} }}")
        o(f"set_local_variable = {{ name = te_dg_xm{b} value = var:te_dg_cbm{b} }}")
    last = P.BANDS - 1
    for _step in range(4):
        o("set_local_variable = { name = te_dg_births value = 0 }")
        for b in range(P.BANDS):
            o(f"change_local_variable = {{ name = te_dg_births add = {{ value = local_var:te_dg_xf{b} "
              f"multiply = local_var:te_dg_fert{b} }} }}")
        for s in ("f", "m"):
            o(f"set_local_variable = {{ name = te_dg_x{s}{last} value = {{ value = local_var:te_dg_x{s}{last} "
              f"multiply = local_var:te_dg_s{s}{last} add = {{ value = local_var:te_dg_x{s}{last - 1} "
              f"multiply = local_var:te_dg_s{s}{last - 1} }} }} }}")
            for b in range(last - 1, 0, -1):
                o(f"set_local_variable = {{ name = te_dg_x{s}{b} value = {{ value = local_var:te_dg_x{s}{b - 1} "
                  f"multiply = local_var:te_dg_s{s}{b - 1} }} }}")
        o(f"set_local_variable = {{ name = te_dg_xf0 value = {{ value = local_var:te_dg_births "
          f"multiply = {lit(P.FEMALE_BIRTH_PER_100K / 100000)} multiply = local_var:te_dg_sf0 }} }}")
        o(f"set_local_variable = {{ name = te_dg_xm0 value = {{ value = local_var:te_dg_births "
          f"multiply = {lit(P.MALE_BIRTH_PER_100K / 100000)} multiply = local_var:te_dg_sm0 }} }}")
    for b in range(P.BANDS):
        o(f"set_variable = {{ name = te_dg_pjf{b} value = local_var:te_dg_xf{b} }}")
        o(f"set_variable = {{ name = te_dg_pjm{b} value = local_var:te_dg_xm{b} }}")
    o("}")
    o("")


def render_effects():
    o = Out()
    o(HEADER.rstrip("\n"))
    o("")
    sweeps(o)
    enter_group(o)
    bands_and_classes(o)
    life_table(o)
    growth_factor(o)
    country_bands(o)
    profile(o)
    band_figures(o)
    projection(o)
    debug_ring(o)
    return o.text()


# ---- values -------------------------------------------------------------------------

def _piecewise_sol(o, name, comment, points, scale=1.0):
    """A per-pop value: total_size x a piecewise-linear function of standard_of_living."""
    o(f"# {comment}")
    o(f"{name} = {{")
    o("value = total_size")
    o("multiply = {")
    o(f"value = {lit(points[0][1] * scale)}")
    for (x0, y0), (x1, y1) in zip(points, points[1:]):
        slope = (y1 - y0) / (x1 - x0) * scale
        o("if = {")
        o(f"limit = {{ standard_of_living > {lit(x0)} }}")
        o(f"value = {{ value = standard_of_living subtract = {lit(x0)} multiply = {lit(slope)} "
          f"add = {lit(y0 * scale)} }}")
        o("}")
    o("if = {")
    o(f"limit = {{ standard_of_living >= {lit(points[-1][0])} }}")
    o(f"value = {lit(points[-1][1] * scale)}")
    o("}")
    o("}")
    o("}")
    o("")


def engine_curves(o, d):
    b = [(0, G.monthly_birthrate(0, d)), (d.transition_sol, G.monthly_birthrate(d.transition_sol, d)),
         (d.stable_sol, G.monthly_birthrate(d.stable_sol, d))]
    m = [(0, G.monthly_mortality(0, d)), (d.equilibrium_sol, G.monthly_mortality(d.equilibrium_sol, d)),
         (d.max_sol, G.monthly_mortality(d.max_sol, d)), (d.stable_sol, G.monthly_mortality(d.stable_sol, d))]
    _piecewise_sol(o, "te_demog_pop_engine_births",
                   "Pop scope: the engine's births a month x 100,000 at this pop's SoL (extra_defines.txt), x size.",
                   b, 100000)
    _piecewise_sol(o, "te_demog_pop_engine_deaths",
                   "Pop scope: the engine's deaths a month x 100,000 at this pop's SoL, x size.", m, 100000)
    _piecewise_sol(o, "te_demog_pop_wealth_tfr",
                   "Pop scope: children per woman from wealth alone at this pop's SoL (spec 2.3), x size.",
                   [(0, P.WEALTH_TFR_LOW), (P.WEALTH_TFR_LOW_SOL, P.WEALTH_TFR_LOW),
                    (P.WEALTH_TFR_HIGH_SOL, P.WEALTH_TFR_HIGH)])


def buy_package_costs(root):
    import re
    text = (root / BUY_PACKAGES).read_text(encoding="utf-8-sig")
    out = {}
    for m in re.finditer(r"^wealth_(\d+) = \{(.*?)^\}", text, re.S | re.M):
        goods = re.search(r"goods = \{[^\n]*\n(.*?)\n\t\}", m.group(2), re.S)
        out[int(m.group(1))] = sum(float(v) for v in re.findall(r"= ([0-9.]+)", goods.group(1)))
    return out


def income(o, costs):
    o("# Pop scope: spending per head at this pop's wealth (buy packages / 100, capped at wealth")
    o(f"# {P.INCOME_WEALTH_CAP}), the stand-in for income in the Gini (spec 4.1), x size.")
    o("te_demog_pop_income = {")
    o("value = total_size")
    o("multiply = {")
    o(f"value = {lit(costs[INCOME_KNOTS[0]] / 100)}")
    for x0, x1 in zip(INCOME_KNOTS, INCOME_KNOTS[1:]):
        y0, y1 = costs[x0] / 100, costs[x1] / 100
        o("if = {")
        o(f"limit = {{ wealth > {x0} }}")
        o(f"value = {{ value = wealth subtract = {x0} multiply = {lit((y1 - y0) / (x1 - x0))} add = {lit(y0)} }}")
        o("}")
    o("if = {")
    o(f"limit = {{ wealth >= {INCOME_KNOTS[-1]} }}")
    o(f"value = {lit(costs[INCOME_KNOTS[-1]] / 100)}")
    o("}")
    o("}")
    o("}")
    o("")


def multipliers(o):
    for cause in CAUSES:
        o(f"# State scope: the {cause} cause's multiplier (demographics_model.cause_multipliers).")
        o(f"te_demog_mult_{cause} = {{")
        o("value = 1")
        for tech, m in P.TECH_MULT.get(cause, {}).items():
            o(f"if = {{ limit = {{ owner = {{ has_technology_researched = {tech} }} }} multiply = {lit(m)} }}")
        for law, m in P.LAW_MULT.get(cause, {}).items():
            o(f"if = {{ limit = {{ owner = {{ has_law = law_type:{law} }} }} multiply = {lit(m)} }}")
        for inst, m in P.INSTITUTION_MULT.get(cause, {}).items():
            for level in range(5, 0, -1):
                kw = "if" if level == 5 else "else_if"
                o(f"{kw} = {{")
                o(f"limit = {{ owner = {{ institution_investment_level = {{ institution = {inst} value >= {level} }} }} }}")
                o(f"multiply = {lit(m ** level)}")
                o("}")
        if cause == "infection":
            o("multiply = {")
            o(f"value = var:te_dg_sol subtract = {P.WEALTH_TFR_LOW_SOL} "
              f"divide = {P.WEALTH_TFR_HIGH_SOL - P.WEALTH_TFR_LOW_SOL} min = 0 max = 1")
            o(f"multiply = {lit(P.SOL_INFECTION_AT_HIGH - 1)} add = 1")
            o("}")
            o(f"multiply = {{ value = var:te_dg_lit multiply = {lit(-P.LITERACY_INFECTION_WEIGHT)} add = 1 }}")
            o("if = {")
            o("limit = {")
            o("has_modifier = migration_crowding")
            o("owner = { NOT = { institution_investment_level = { institution = institution_ministry_of_urban_planning "
              "value >= 1 } } }")
            o("}")
            o(f"multiply = {lit(P.CROWDING_INFECTION_MULT)}")
            o("}")
        if cause == "chronic":
            o("multiply = {")
            o(f"value = var:te_dg_sol subtract = {P.WEALTH_TFR_LOW_SOL} "
              f"divide = {P.WEALTH_TFR_HIGH_SOL - P.WEALTH_TFR_LOW_SOL} min = 0 max = 1")
            o(f"multiply = {lit(P.SOL_CHRONIC_AT_HIGH - 1)} add = 1")
            o("}")
        if cause == "maternal":
            o(f"multiply = {P.MATERNAL_PER_100K_BIRTHS}")
        o("}")
        o("")
    o("# State scope: women's share of the workforce by the owner's women's-rights law.")
    o("te_demog_female_work_share = {")
    o(f"value = {lit(P.FEMALE_WORK_SHARE_DEFAULT)}")
    for law, share in P.FEMALE_WORK_SHARE.items():
        o(f"if = {{ limit = {{ owner = {{ has_law = law_type:{law} }} }} value = {lit(share)} }}")
    o("}")
    o("")
    o("# State scope: the share of the gap to desired fertility a population can close (spec 2.3).")
    o("te_demog_means = {")
    tiers = sorted(P.MEANS_TIERS, key=lambda t: t[1])
    o(f"value = {lit(tiers[0][1])}")
    for tech, value in tiers[1:]:
        o(f"if = {{ limit = {{ owner = {{ has_technology_researched = {tech} }} }} value = {lit(value)} }}")
    o("multiply = { value = var:te_dg_lit multiply = 0.7 add = 0.3 }")
    for law, shift in P.MEANS_LAW_SHIFT.items():
        o(f"if = {{ limit = {{ owner = {{ has_law = law_type:{law} }} }} add = {lit(shift)} }}")
    o("# history, events and measures: Family Limitation and its kin (country_fertility_means_add)")
    o("add = owner.modifier:country_fertility_means_add")
    o(f"max = {lit(P.MEANS_CAP)}")
    o("min = 0")
    o("}")
    o("")


def land_tenure_values(root):
    """{law: Wealth Concentration term} for every land-reform law, variants at their parent's value."""
    import json
    from paradox_file_parser import ParadoxFileParser

    def field(body, key):
        v = body.get(key) if isinstance(body, dict) else None
        v = v[-1] if isinstance(v, (list, tuple)) else v
        return v[-1] if isinstance(v, (list, tuple)) else v

    laws = {}
    data = json.loads((root / "vanilla_parsed" / "common" / "laws.json").read_text(encoding="utf-8"))
    for name, body in data.get("data", data).items():
        laws[name] = body[1] if isinstance(body, list) and len(body) == 2 and body[0] == "=" else body
    for path in sorted((root / "common" / "laws").glob("*.txt")):
        parser = ParadoxFileParser()
        parser.parse_file(str(path), apply_directives=False)
        for name, body in parser.data.items():
            if ":" in name and not name.startswith("REPLACE:"):
                continue   # INJECT: adds fields to a vanilla law; its group and parent stay vanilla's
            laws[name.split(":")[-1]] = body[1] if isinstance(body, tuple) else body
    out = {}
    for name, body in sorted(laws.items()):
        if field(body, "group") != "lawgroup_land_reform":
            continue
        base = field(body, "parent") or name
        if base not in P.LAND_TENURE:
            raise KeyError(f"{name}: no LAND_TENURE value for {base} (demographics_params.py)")
        out[name] = P.LAND_TENURE[base]
    return out


def land_term(o, root):
    o("# State scope: the land-tenure term of Wealth Concentration's target (spec 4.2), weighted by")
    o("# the state's agrarian share. Variant laws take their parent's value.")
    o("te_demog_wc_land_term = {")
    o("value = 0")
    for law, value in land_tenure_values(root).items():
        if value:
            o(f"if = {{ limit = {{ owner = {{ has_law = law_type:{law} }} }} value = {lit(value)} }}")
    o("multiply = var:te_dg_agr_share")
    o("}")
    o("")


def constants(o):
    o("# Constants the hand-written script reads (demographics_params.py).")
    k = {
        "female_births_per_100k": P.FEMALE_BIRTH_PER_100K, "male_births_per_100k": P.MALE_BIRTH_PER_100K,
        "education_weight": P.EDUCATION_WEIGHT, "survival_weight": P.SURVIVAL_WEIGHT,
        "urban_weight": P.URBAN_WEIGHT, "war_male_share": P.WAR_DEAD_MALE_SHARE,
        "residual_noise_share": P.RESIDUAL_NOISE_SHARE, "gini_floor": P.GINI_FLOOR, "gini_scale": P.GINI_SCALE,
        "labour_female_min": P.LABOUR_FEMALE_SHARE_MIN, "labour_female_max": P.LABOUR_FEMALE_SHARE_MAX,
        "family_base": P.FAMILY_BASE, "family_rights_weight": P.FAMILY_RIGHTS_WEIGHT,
        "full_female_work_share": P.FULL_FEMALE_WORK_SHARE, "chain_step": P.CHAIN_STEP, "chain_cap": P.CHAIN_CAP,
        "crisis_at_war": P.CRISIS_AT_WAR,
    }
    for name, value in k.items():
        o(f"te_demog_k_{name} = {{ value = {lit(value)} }}")
    for kind, spec in P.MIGRANT_PROFILE.items():
        for c, w in enumerate(spec["weights"]):
            o(f"te_demog_k_{kind}_{c} = {{ value = {lit(w)} }}")
    o("# State scope: the family share's transport term (owner technology).")
    o("te_demog_family_transport = {")
    o("value = 0")
    for tech, v in P.FAMILY_TRANSPORT_TECHS.items():
        o(f"if = {{ limit = {{ owner = {{ has_technology_researched = {tech} }} }} add = {lit(v)} }}")
    o("}")
    o("")


def debug_values(o):
    o("# State scope: each slot as per mille of the state's people, for the replay lines (Task 15).")
    for s in ("f", "m"):
        for k in range(N):
            o(f"te_demog_dbg_{s}{k} = {{ value = 0 if = {{ limit = {{ has_variable = te_dg_{s}{k} }} "
              f"value = var:te_dg_{s}{k} multiply = te_demog_dbg_unit }} }}")
    o("te_demog_dbg_pool_f = { value = var:te_dg_pf multiply = te_demog_dbg_unit }")
    o("te_demog_dbg_pool_m = { value = var:te_dg_pm multiply = te_demog_dbg_unit }")
    o("te_demog_dbg_unit = { value = var:te_dg_scale multiply = 1000 divide = { value = var:te_dg_people min = 1 } }")
    o("")


def render_values(root):
    o = Out()
    o(HEADER.rstrip("\n"))
    o("")
    engine_curves(o, G.read_defines(root / "common" / "defines" / "extra_defines.txt"))
    income(o, buy_package_costs(root))
    multipliers(o)
    land_term(o, root)
    constants(o)
    debug_values(o)
    return o.text()


def plan_outputs(root=ROOT):
    return {EFFECTS: render_effects(), VALUES: render_values(root)}


def regenerate(root=ROOT, dry_run=False):
    changed = []
    for rel, text in plan_outputs(root).items():
        target = root / rel
        expected = text.encode("utf-8-sig")
        if not target.exists() or target.read_bytes() != expected:
            changed.append(str(rel))
            if not dry_run:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(expected)
    return {"changed": bool(changed), "changed_files": changed}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if a committed file is stale")
    args = ap.parse_args(argv)
    result = regenerate(dry_run=args.check)
    for rel in result["changed_files"]:
        print(("stale: " if args.check else "wrote: ") + rel)
    return 1 if (args.check and result["changed"]) else 0


if __name__ == "__main__":
    sys.exit(main())
