#!/usr/bin/env python3
"""Generate the legislated tax code's rate amendments, script values and loc.

The tax code (docs/superpowers/specs/2026-09-29-legislated-tax-code-design.md)
holds each tax instrument as an integer index: rate = index x step. The carrier
law `law_te_tax_code` collects nothing; one generated amendment per instrument
and index carries the rate, identical in all five native tax levels so that a
level change moves only the political static modifier. INSTRUMENTS below is the
single source of truth for that table.

Outputs (each is registered in OUTPUTS and written byte for byte):

  common/amendments/te_tax_amendments_generated.txt
      amendment_te_tax_<key>_<idx> for every instrument and every idx 1..max.
  common/script_values/te_tax_generated_values.txt
      te_tax_step_<key>, te_tax_max_<key> and te_tax_pct_step_<key> constants.
  localization/english/te_tax_generated_l_english.yml
      A name and a _desc per amendment. organize_loc.py files these keys here
      (category TAX_GENERATED) and renders the file itself, so this script
      renders through organize_loc and the two always agree.

Later tasks register more outputs the same way: write a function returning the
file's bytes and decorate it with @output("<repo-relative path>").

Usage (repo root, system python3, standard library only):

    python3 scripts/generators/gen_tax_code.py            # write the outputs
    python3 scripts/generators/gen_tax_code.py --check    # write nothing; exit 1 on drift
    python3 scripts/generators/gen_tax_code.py --root DIR # another tree (tests)
"""

import argparse
import os
import sys
from decimal import Decimal
from typing import NamedTuple

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO)

from organize_loc import _render_loc_file, section_label  # noqa: E402

HEADER = "# AUTO-GENERATED by scripts/generators/gen_tax_code.py — do not edit manually"
CARRIER_LAW = "law_te_tax_code"
GATE_TRIGGER = "te_tax_code_on"
LOC_CATEGORY = "TAX_GENERATED"
LEVELS = (
    "tax_modifier_very_low", "tax_modifier_low", "tax_modifier_medium",
    "tax_modifier_high", "tax_modifier_very_high",
)

AMENDMENTS_PATH = "common/amendments/te_tax_amendments_generated.txt"
VALUES_PATH = "common/script_values/te_tax_generated_values.txt"
LOC_PATH = "localization/english/te_tax_generated_l_english.yml"


class Instrument(NamedTuple):
    key: str            # short name used in every generated identifier
    modifier: str       # the native tax modifier the amendment carries
    step: Decimal       # rate per index
    max_idx: int        # highest index that gets an amendment
    label: str          # shown to the player (title-cased in loc)
    payer: str          # who pays, as it reads in "Taxes <payer> at <rate>."
    percent: bool       # printed as a percentage (else as a bare amount)
    vanilla: tuple      # every value the five vanilla taxation laws set


def _values(text):
    return tuple(Decimal(value) for value in text.split())


INSTRUMENTS = (
    Instrument("wage", "tax_income_add", Decimal("0.025"), 20, "Wage tax",
               "the wages of employed pops", True,
               _values("0.05 0.075 0.10 0.125 0.15 0.175 0.20 0.25 0.30")),
    Instrument("div", "tax_dividends_add", Decimal("0.025"), 20, "Dividend tax",
               "dividends paid to pops who own private buildings", True,
               _values("0.025 0.05 0.10 0.15 0.20 0.25 0.30")),
    Instrument("land", "tax_land_add", Decimal("0.025"), 48, "Rural assessment",
               "peasants and farmers working agricultural buildings, who then pay no head tax",
               False, _values("0.20 0.275 0.35 0.40 0.425 0.50 0.55 0.70 0.85 1.00")),
    Instrument("head", "tax_per_capita_add", Decimal("0.05"), 30, "Head tax",
               "working adults who pay no rural assessment", False,
               _values("0.40 0.55 0.70 0.85 1.00")),
    Instrument("cons", "tax_consumption_add", Decimal("0.05"), 12, "Consumption tax rate",
               "goods on the taxed-goods list when pops buy them", True,
               _values("0.15 0.20 0.25 0.30 0.35")),
)


def validate(instruments=INSTRUMENTS):
    """Raise ValueError unless every vanilla value is index x step for some index 1..max."""
    for instrument in instruments:
        for value in instrument.vanilla:
            index, remainder = divmod(value, instrument.step)
            if remainder != 0 or not 1 <= index <= instrument.max_idx:
                raise ValueError(
                    f"{instrument.key}: vanilla value {value} is not index x {instrument.step} "
                    f"for an index in 1..{instrument.max_idx}"
                )


def fmt(value):
    """A Decimal without trailing zeros or an exponent: 0.075, 0.1, 1, 10."""
    return format(value.normalize(), "f")


def rate(instrument, idx):
    return instrument.step * idx


def amendment_key(instrument, idx):
    return f"amendment_te_tax_{instrument.key}_{idx}"


def display(instrument, idx):
    """The rate as the player reads it: 7.5% for a rate, 0.425 for an amount."""
    value = rate(instrument, idx)
    return f"{fmt(value * 100)}%" if instrument.percent else fmt(value)


# ---------------------------------------------------------------------------
# Output registry
# ---------------------------------------------------------------------------

OUTPUTS = {}


def output(path):
    """Register a function returning one output file's bytes under its repo-relative path."""
    def register(function):
        OUTPUTS[path] = function
        return function
    return register


def _txt(text):
    """A brace .txt file's bytes: UTF-8 BOM, LF endings."""
    return text.encode("utf-8-sig")


@output(AMENDMENTS_PATH)
def amendments():
    lines = [
        HEADER,
        "# One amendment per instrument and index: rate = index x step (INSTRUMENTS in the generator).",
        f"# {CARRIER_LAW} collects nothing; the amendment attached to it carries the rate. All five",
        "# tax_modifier_* blocks are identical, so a native tax-level change moves only the",
        "# political static modifier. Nothing sponsors, revokes or repeals these on its own.",
    ]
    for instrument in INSTRUMENTS:
        lines += ["", f"# {instrument.label}: {instrument.modifier}, step {fmt(instrument.step)}, "
                      f"indexes 1..{instrument.max_idx}"]
        for idx in range(1, instrument.max_idx + 1):
            value = fmt(rate(instrument, idx))
            if idx > 1:
                lines.append("")
            lines += [
                f"{amendment_key(instrument, idx)} = {{",
                f"\tparent = {CARRIER_LAW}",
                f"\tallowed_laws = {{ {CARRIER_LAW} }}",
                f"\tpossible = {{ {GATE_TRIGGER} = yes }}",
                "\tcan_repeal = { always = no }",
                "\twould_sponsor = { always = no }",
                "\tai_will_revoke = { always = no }",
            ]
            lines += [f"\t{level} = {{ {instrument.modifier} = {value} }}" for level in LEVELS]
            lines.append("}")
    return _txt("\n".join(lines) + "\n")


@output(VALUES_PATH)
def script_values():
    lines = [
        HEADER,
        "# Index encoding for the legislated tax code: rate = index x te_tax_step_<key>, with",
        "# the index from 0 (not set) to te_tax_max_<key>. A display value is written as",
        "# `value = var:<index variable>` `multiply = te_tax_step_<key>`; te_tax_pct_step_<key>",
        "# is the step in percentage points, for the instruments printed as a percentage.",
    ]
    for instrument in INSTRUMENTS:
        lines += [
            "",
            f"te_tax_step_{instrument.key} = {fmt(instrument.step)}",
            f"te_tax_max_{instrument.key} = {instrument.max_idx}",
        ]
        if instrument.percent:
            lines.append(f"te_tax_pct_step_{instrument.key} = {fmt(instrument.step * 100)}")
    return _txt("\n".join(lines) + "\n")


@output(LOC_PATH)
def localization():
    entries = {}
    for instrument in INSTRUMENTS:
        for idx in range(1, instrument.max_idx + 1):
            key = amendment_key(instrument, idx)
            shown = display(instrument, idx)
            entries[key] = f'0 "{instrument.label.title()} {shown}"'
            entries[f"{key}_desc"] = f'0 "Taxes {instrument.payer} at {shown}."'
    return _render_loc_file([(section_label(LOC_CATEGORY), entries)])


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def render_all():
    validate()
    return {path: function() for path, function in OUTPUTS.items()}


def drifted(root, rendered):
    """The repo-relative paths whose file under `root` is missing or differs."""
    changed = []
    for path, expected in rendered.items():
        try:
            with open(os.path.join(root, path), "rb") as handle:
                actual = handle.read()
        except FileNotFoundError:
            actual = None
        if actual != expected:
            changed.append(path)
    return changed


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--check", action="store_true",
        help="write nothing; exit 1 and list the files that differ from the generator's output",
    )
    parser.add_argument("--root", default=REPO, help="tree to read or write (default: this repo)")
    args = parser.parse_args(argv)

    rendered = render_all()
    changed = drifted(args.root, rendered)
    if args.check:
        if changed:
            print("gen_tax_code.py: generated files differ from the generator's output:")
            for path in changed:
                print(f"  {path}")
            print("Edit the generator and run `python3 scripts/generators/gen_tax_code.py`; "
                  "never edit a generated file by hand.")
            return 1
        print(f"gen_tax_code.py: {len(rendered)} generated files match.")
        return 0
    for path in changed:
        target = os.path.join(args.root, path)
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "wb") as handle:
            handle.write(rendered[path])
        print(f"wrote {path}")
    if not changed:
        print(f"gen_tax_code.py: {len(rendered)} generated files already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
