"""Regenerate carbon-accounting data from production-method recipes.

Writes synthetic-fuel credits, covered buildings' fuel emissions and direct
air capture's removal modifier, plus source-capture methods, groups, building
membership, localization and a coverage report.
Synthetic credits use shared factors at runtime. PM display values are derived
from merged recipes or the independent removal-capacity parameter and shared
factors/display scale, so their coefficients are never maintained by hand.

Run ``python3 gen_carbon_capture_pms.py [--dry-run | --check]``. No game install
or running server is required. Full server reloads call ``regenerate``.
"""

from __future__ import annotations

import argparse
from decimal import Decimal
from pathlib import Path

from paradox_file_parser import ParadoxFileParser
import pm_emissions
import pm_carbon_capture
import household_emissions

ROOT = Path(__file__).resolve().parent
OUTPUT = Path("common/script_values/carbon_capture_generated_values.txt")
SYNTHETIC_METHODS = pm_emissions.SYNTHETIC_CREDITS


def unwrap(value):
    """Unwrap the parser's (operator, value) representation."""
    if isinstance(value, tuple) and len(value) == 2 and value[0] == "=":
        return value[1]
    return value


def load_synthetic_methods(root: Path) -> dict:
    """Read the mod-owned recipes without loading vanilla or unrelated data.

    These methods are defined by the mod, so INJECT cannot amend them. Fail
    rather than quietly retaining a stale recipe if that ownership changes.
    """
    methods = {}
    for path in sorted((root / "common/production_methods").glob("*.txt")):
        parser = ParadoxFileParser()
        parser.parse_file(str(path), apply_directives=False)
        for key, value in parser.data.items():
            directive, name = parser._split_directive(key)
            if name not in SYNTHETIC_METHODS:
                continue
            if directive == "INJECT":
                raise ValueError(f"{path}: synthetic recipe {name} cannot use INJECT")
            if name in methods:
                raise ValueError(f"Duplicate synthetic recipe {name} in {path}")
            methods[name] = value
    return methods


def build_synthetic_values(methods: dict) -> str:
    lines = [
        "# AUTO-GENERATED by gen_carbon_capture_pms.py; do not edit.",
        "# Negative credits per staffed level in internal emissions units.",
        "# Inputs: synthetic PM outputs; factors: gw_emission_factor_coal/oil.",
        "",
    ]
    for name, fuel in SYNTHETIC_METHODS.items():
        method = unwrap(methods[name])
        building = unwrap(method["building_modifiers"])
        workforce = unwrap(building["workforce_scaled"])
        output = Decimal(unwrap(workforce[f"goods_output_{fuel}_add"]))
        if not output.is_finite() or output <= 0:
            raise ValueError(f"{name}: expected positive finite {fuel} output, got {output}")
        lines.extend([
            f"gw_{name.removeprefix('pm_')}_capture_per_level = {{",
            f"\tvalue = {-output:f}",
            f"\tmultiply = gw_emission_factor_{fuel}",
            "\tdivide = 10000",
            "}",
            "",
        ])
    return "\n".join(lines)


def regenerate(mod_state=None, *, root: Path = ROOT, dry_run: bool = False):
    if mod_state is None:
        mod_state = pm_emissions.load_state(root)
    methods = mod_state.mod_parsers["PMs"].data
    content = build_synthetic_values(methods)
    outputs, fuel_methods = pm_emissions.plan_outputs(mod_state, root)
    capture_outputs, capture_counts = pm_carbon_capture.plan_outputs(mod_state, root)
    outputs.update(capture_outputs)
    outputs.update(household_emissions.plan_outputs(mod_state))
    outputs[OUTPUT] = content
    changed_files = []
    for relative, text in outputs.items():
        target = root / relative
        expected = text.encode("utf-8" if relative.suffix == ".md" else "utf-8-sig")
        if not target.exists() or target.read_bytes() != expected:
            changed_files.append(str(relative))
            if not dry_run:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(expected)
    return {"changed": bool(changed_files), "output": str(OUTPUT),
            "changed_files": changed_files, "fuel_methods": fuel_methods, **capture_counts}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--dry-run", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    result = regenerate(root=args.root, dry_run=args.dry_run or args.check)
    print(f"{result['output']}: {'changed' if result['changed'] else 'current'}")
    print(f"{result['fuel_methods']} fuel methods; {len(result['changed_files'])} files need updating")
    print(f"{result['capture_buildings']} capture buildings; {result['capture_groups']} groups; "
          f"{result['capture_variants']} tier variants")
    return int(args.check and result["changed"])


if __name__ == "__main__":
    raise SystemExit(main())
