"""Generate the wealth/heating curve used by household climate accounting.

This is an explicit estimate, not a market-sales measurement. Heating demand
comes from merged buy packages at average state wealth. Fossil shares follow
weighted market supply, with absent fuels contributing nothing; peasants buy
only their pop type's consumption fraction. This remains an approximation.
"""

from decimal import Decimal
from pathlib import Path

from pm_emissions import unwrap as u

OUTPUT = Path("common/script_values/household_emissions_generated_values.txt")
POP_PACKAGE = Decimal(10000)
CONSUMPTION_EQUIVALENT = Decimal("0.25") + Decimal("0.75") * Decimal("0.5")
FUELS = ("coal", "oil")


def heating_curve(state):
    packages = state.mod_parsers["Buy Packages"].data
    points = []
    for level in range(1, 100):
        goods = u(u(packages[f"wealth_{level}"])["goods"])
        heating = Decimal(u(goods.get("popneed_heating", 0)))
        if not heating.is_finite() or heating < 0:
            raise ValueError(f"Invalid heating demand at wealth {level}: {heating}")
        points.append((level, heating))
    return points


def segments(points):
    """Combine adjacent intervals with the same slope without changing the curve."""
    result = []
    for (x0, y0), (x1, y1) in zip(points, points[1:]):
        slope = (y1 - y0) / (x1 - x0)
        if result and result[-1][3] == slope:
            result[-1] = (*result[-1][:2], x1, slope)
        else:
            result.append((x0, y0, x1, slope))
    return result


def plan_outputs(state):
    points = heating_curve(state)
    lines = ["# AUTO-GENERATED by gen_carbon_capture_pms.py (household_emissions.py); do not edit.",
             "# Heating budget per 10,000 consumption-equivalent people, at base prices.",
             "# Linearly interpolate merged buy packages using average state wealth.", "",
             "gw_household_average_wealth = {", "\tvalue = average_sol", "\tmin = 1", "\tmax = 99", "}", "",
             "gw_household_heating_budget = {", "\tvalue = 0"]
    for index, (x0, y0, x1, slope) in enumerate(segments(points)):
        lines.extend(["\t" + ("if" if index == 0 else "else_if") + " = {",
                      f"\t\tlimit = {{ gw_household_average_wealth < {x1} }}", f"\t\tvalue = {y0:f}"])
        if slope:
            lines.extend(["\t\tadd = {", "\t\t\tvalue = gw_household_average_wealth",
                          f"\t\t\tsubtract = {x0}", f"\t\t\tmultiply = {slope:f}", "\t\t}"])
        lines.append("\t}")
    lines.extend([f"\telse = {{ value = {points[-1][1]:f} }}", "}", "",
                  f"gw_household_pop_package = {POP_PACKAGE:f}",
                  f"gw_household_consumption_equivalent = {CONSUMPTION_EQUIVALENT:f}"])
    goods = state.mod_parsers["Goods"].data
    for fuel in FUELS:
        price = Decimal(u(u(goods[fuel])["cost"]))
        if not price.is_finite() or price <= 0:
            raise ValueError(f"Invalid {fuel} base price: {price}")
        lines.append(f"gw_household_{fuel}_base_price = {price:f}")
    peasants = u(state.mod_parsers["Pop Types"].data["peasants"])
    fraction = Decimal(u(peasants["consumption_mult"]))
    if not fraction.is_finite() or not 0 <= fraction <= 1:
        raise ValueError(f"Invalid peasant consumption fraction: {fraction}")
    lines.extend([f"gw_household_peasant_consumption = {fraction:f}", ""])
    need = u(state.mod_parsers["Pop Needs"].data["popneed_heating"])
    entries = need["entry"]
    entries = entries if isinstance(entries, list) else [entries]
    weights = {}
    caps = {}
    for entry in entries:
        entry = u(entry)
        good = u(entry["goods"])
        weight = Decimal(u(entry["weight"]))
        cap = Decimal(u(entry.get("max_supply_share", 1)))
        if not weight.is_finite() or weight < 0 or not cap.is_finite() or not 0 <= cap <= 1:
            raise ValueError(f"Invalid heating supply weight/cap for {good}")
        weights[good] = weight
        caps[good] = cap
    lines.extend(["# Market scope: a weighted supply estimate, not exact pop sales.",
                  "gw_household_weighted_heating_supply = {", "\tvalue = 0"])
    for good, weight in weights.items():
        lines.extend([f"\tmg:{good} = {{", f"\t\tadd = {{ value = market_goods_sell_orders multiply = {weight:f} min = 0 }}", "\t}"])
    lines.extend(["}", ""])
    for fuel in FUELS:
        lines.extend([f"gw_household_{fuel}_heating_share = {{", "\tvalue = 0", "\towner = {", "\t\tmarket = {",
                      f"\t\t\tmg:{fuel} = {{ value = market_goods_sell_orders multiply = {weights[fuel]:f} min = 0 }}",
                      "\t\t\tdivide = { value = gw_household_weighted_heating_supply min = 1 }",
                      f"\t\t\tmax = {caps[fuel]:f}", "\t\t}", "\t}", "}", ""])
    return {OUTPUT: "\n".join(lines)}
