"""Unit tests for localization_accessor_audit.

Mirrors the structure of test_event_magnitude_audit.py:
- CatalogTests: catalog parsing
- ChainExtractionTests: regex/extractor edge cases
- ContextClassificationTests: key-pattern → context inference
- ValidationTests: chain walk, success and failure modes
- SuppressionTests: # REVIEWED comment parsing
- EndToEndTests: tempdir audit + report rendering
- VanillaCleanTests: zero unreviewed flags on vanilla loc (skipUnless installed)
"""
import os
import tempfile
import unittest

from localization_accessor_audit import (
    AuditFlag,
    Chain,
    _GLOBAL_FUNCTIONS,
    _MAGIC_SCOPES_BY_CONTEXT,
    _load_engine_catalog,
    _split_chain,
    _strip_format_modifier,
    audit,
    classify_context,
    extract_chains,
    parse_reviewed_comment,
    read_loc_file,
    regenerate,
    render_report,
    validate_chain,
)


VANILLA_LOC_PATH = (
    "/mnt/c/Program Files (x86)/Steam/steamapps/common/Victoria 3/game/localization/english/"
)


class CatalogTests(unittest.TestCase):
    def test_load_engine_catalog_merges_with_builtins(self):
        # The mod's docs/engine/event_targets_summary.txt is generated by
        # the live engine; we point the loader at it.
        catalog = _load_engine_catalog("docs/engine")
        # Built-in country accessors should be present
        self.assertIn("country", catalog)
        self.assertIn("GetName", catalog["country"])
        # Some engine-derived accessors should also be present
        self.assertIn("active_law", catalog.get("country", {}))

    def test_load_engine_catalog_missing_dir_returns_builtins_only(self):
        catalog = _load_engine_catalog("/nonexistent/path/12345")
        self.assertIn("country", catalog)  # builtins still loaded
        self.assertIn("GetName", catalog["country"])

    def test_load_engine_catalog_handles_multi_scope_lines(self):
        """Lines like `country,front,state_region|every_scope_state|...`
        should spread the accessor across each named scope type."""
        with tempfile.TemporaryDirectory() as td:
            path = os.path.join(td, "event_targets_summary.txt")
            with open(path, "w", encoding="utf-8") as f:
                f.write(
                    "# header\n"
                    "country,front|every_scope_state|country|something\n"
                )
            catalog = _load_engine_catalog(td)
            self.assertEqual(catalog["country"]["every_scope_state"], "country")
            self.assertEqual(catalog["front"]["every_scope_state"], "country")


class ChainExtractionTests(unittest.TestCase):
    def test_extract_simple_chain(self):
        chains = extract_chains("Hello [TARGET_COUNTRY.GetName] world")
        self.assertEqual(len(chains), 1)
        self.assertEqual(chains[0].steps, ["TARGET_COUNTRY", "GetName"])

    def test_extract_multiple_chains(self):
        text = "[COUNTRY.GetName] vs [TARGET_COUNTRY.GetName]"
        chains = extract_chains(text)
        self.assertEqual(len(chains), 2)

    def test_extract_strips_format_modifier(self):
        chains = extract_chains("[JournalEntry.GetGoalProgressValue|D]")
        self.assertEqual(chains[0].steps, ["JournalEntry", "GetGoalProgressValue"])

    def test_extract_handles_function_call_step(self):
        text = "[SCOPE.sCountry('owner_country').GetAdjective]"
        chains = extract_chains(text)
        self.assertEqual(len(chains), 1)
        self.assertEqual(chains[0].steps[0], "SCOPE")
        self.assertEqual(chains[0].steps[1], "sCountry('owner_country')")
        self.assertEqual(chains[0].steps[2], "GetAdjective")

    def test_extract_skips_concept_references(self):
        chains = extract_chains("Concept ref: [concept_power_bloc] here")
        self.assertEqual(chains, [])

    def test_extract_skips_variable_substitution(self):
        chains = extract_chains("Substitution: [$DETAILS$] here")
        self.assertEqual(chains, [])

    def test_extract_keeps_concept_function_call(self):
        chains = extract_chains("[Concept('concept_x', '$fallback$')]")
        self.assertEqual(len(chains), 1)
        # Concept(...) is one step, name is "Concept"
        self.assertEqual(chains[0].steps[0].split("(")[0], "Concept")

    def test_strip_format_modifier_outside_parens(self):
        self.assertEqual(_strip_format_modifier("X.Y|D"), "X.Y")
        self.assertEqual(_strip_format_modifier("X.Y|0%"), "X.Y")
        # Bar inside parens shouldn't be treated as modifier
        self.assertEqual(_strip_format_modifier("X.sFn('a|b').Y"), "X.sFn('a|b').Y")

    def test_split_chain_respects_parens(self):
        steps = _split_chain("SCOPE.sCountry('a.b.c').GetName")
        self.assertEqual(steps, ["SCOPE", "sCountry('a.b.c')", "GetName"])


class ContextClassificationTests(unittest.TestCase):
    def test_event_namespace(self):
        self.assertEqual(classify_context("irredentism.1.t"), "events")
        self.assertEqual(classify_context("foo_events.123.a"), "events")

    def test_war_goal(self):
        self.assertEqual(classify_context("war_goal_te_reunify_country"), "war_goals")
        self.assertEqual(classify_context("war_goal_te_reunify_country_desc"), "war_goals")

    def test_journal_entry(self):
        self.assertEqual(classify_context("je_reunify_china"), "journal_entries")

    def test_diplomatic_action(self):
        action_keys = {"voluntary_union"}
        self.assertEqual(
            classify_context("voluntary_union", diplo_action_keys=action_keys),
            "diplomatic_actions",
        )
        self.assertEqual(
            classify_context("voluntary_union_desc", diplo_action_keys=action_keys),
            "diplomatic_actions",
        )
        self.assertEqual(
            classify_context(
                "voluntary_union_action_propose_name", diplo_action_keys=action_keys
            ),
            "diplomatic_actions",
        )

    def test_unclassified_falls_back_to_permissive(self):
        self.assertEqual(classify_context("some_random_key"), "permissive")


class ValidationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.catalog = _load_engine_catalog("docs/engine")

    def _validate(self, text, ctx):
        chains = extract_chains(text)
        self.assertEqual(len(chains), 1)
        return validate_chain(chains[0], ctx, self.catalog)

    def test_target_country_in_diplo_action(self):
        self.assertIsNone(
            self._validate("[TARGET_COUNTRY.GetName]", "diplomatic_actions")
        )

    def test_country_in_diplo_action(self):
        self.assertIsNone(
            self._validate("[COUNTRY.GetName]", "diplomatic_actions")
        )

    def test_war_goal_draft_in_war_goals(self):
        self.assertIsNone(
            self._validate("[WAR_GOAL_DRAFT.GetTarget.GetName]", "war_goals")
        )

    def test_scope_named_country_accessor_in_events(self):
        self.assertIsNone(
            self._validate(
                "[SCOPE.sCountry('irr_unifier').GetAdjective]", "events"
            )
        )

    def test_root_dot_get_country_in_events(self):
        # ROOT in events resolves to country; .GetName terminal works.
        self.assertIsNone(self._validate("[ROOT.GetName]", "events"))

    def test_invalid_accessor_on_known_type_flagged(self):
        # The exact bug class that bit the irredentism work.
        reason = self._validate(
            "[SCOPE.GetRootScope.GetTargetCountry.GetName]", "diplomatic_actions"
        )
        self.assertIsNotNone(reason)
        self.assertIn("GetTargetCountry", reason)
        self.assertIn("scope_object", reason)

    def test_unknown_first_step_silent(self):
        """Unknown first step is silent (treated as 'unknown' and accepted) —
        matches engine's silent-fallback behavior. The audit's value is in
        catching wrong-accessor-on-known-type, not in dictionary-checking
        every magic scope."""
        self.assertIsNone(
            self._validate("[NoSuchMagicScope.GetName]", "permissive")
        )

    def test_format_modifier_does_not_affect_validation(self):
        self.assertIsNone(
            self._validate("[ROOT.GetName|U]", "events")
        )


class SuppressionTests(unittest.TestCase):
    def test_parse_reviewed_full(self):
        out = parse_reviewed_comment(
            '# REVIEWED 2026-05-08: testing the suppression flow'
        )
        self.assertEqual(out, {"date": "2026-05-08", "rationale": "testing the suppression flow"})

    def test_parse_reviewed_missing_date(self):
        # Date must be YYYY-MM-DD; bare REVIEWED rejects.
        self.assertIsNone(parse_reviewed_comment("# REVIEWED: drive-by"))

    def test_parse_reviewed_missing_rationale(self):
        # No colon means no rationale, rejects.
        self.assertIsNone(parse_reviewed_comment("# REVIEWED 2026-05-08"))

    def test_parse_reviewed_none_input(self):
        self.assertIsNone(parse_reviewed_comment(None))

    def test_audit_partitions_suppressed_flags(self):
        with tempfile.TemporaryDirectory() as td:
            loc_dir = os.path.join(td, "loc")
            os.makedirs(loc_dir)
            yml = os.path.join(loc_dir, "test_l_english.yml")
            with open(yml, "w", encoding="utf-8") as f:
                f.write("﻿" + "l_english:\n")
                # Unsuppressed bug
                f.write(
                    ' bad_key:0 "Hello [SCOPE.GetTargetCountry.GetName]"\n'
                )
                # Same bug, suppressed
                f.write(
                    ' suppressed_key:0 "Hello [SCOPE.GetTargetCountry.GetName]"'
                    "  # REVIEWED 2026-05-08: testing\n"
                )
            result = audit(loc_dir, engine_docs_dir="docs/engine")
            unrev = [f for f in result.flags if not f.exemption]
            exemp = [f for f in result.flags if f.exemption]
            self.assertEqual(len(unrev), 1)
            self.assertEqual(len(exemp), 1)
            self.assertEqual(unrev[0].key, "bad_key")
            self.assertEqual(exemp[0].key, "suppressed_key")


class EndToEndTests(unittest.TestCase):
    def test_clean_loc_returns_zero_flags(self):
        with tempfile.TemporaryDirectory() as td:
            loc_dir = os.path.join(td, "loc")
            os.makedirs(loc_dir)
            yml = os.path.join(loc_dir, "clean_l_english.yml")
            with open(yml, "w", encoding="utf-8") as f:
                f.write("﻿" + "l_english:\n")
                f.write(' my_key:0 "Hello [TARGET_COUNTRY.GetName]"\n')
                f.write(' your_key:0 "World [COUNTRY.GetAdjective]"\n')
            result = audit(loc_dir, engine_docs_dir="docs/engine")
            self.assertEqual(len(result.flags), 0)
            self.assertEqual(result.coverage["files_audited"], 1)
            self.assertEqual(result.coverage["chains_scanned"], 2)

    def test_render_report_clean(self):
        with tempfile.TemporaryDirectory() as td:
            loc_dir = os.path.join(td, "loc")
            os.makedirs(loc_dir)
            yml = os.path.join(loc_dir, "clean_l_english.yml")
            with open(yml, "w", encoding="utf-8") as f:
                f.write("﻿" + "l_english:\n")
                f.write(' my_key:0 "Hello [ROOT.GetName]"\n')
            result = audit(loc_dir, engine_docs_dir="docs/engine")
            text = render_report(result)
            self.assertIn("# Localization accessor audit report", text)
            self.assertIn("## Unreviewed Flags", text)
            self.assertIn("_None._", text)
            self.assertIn("- files_audited: 1", text)


@unittest.skipUnless(
    os.path.isdir(VANILLA_LOC_PATH),
    "vanilla loc dir not present; install Vic3 to run vanilla calibration test",
)
class VanillaCleanTests(unittest.TestCase):
    def test_vanilla_loc_has_minimal_unreviewed_flags(self):
        """Vanilla loc is engine-validated by definition. The catalog has been
        bootstrapped against it so this should produce ~0 unreviewed flags
        (one known vanilla bug — `sCharacter('...').GetHerselfHimself` with a
        missing `.` separator — counts; we tolerate it as a known vanilla typo)."""
        result = audit(VANILLA_LOC_PATH, engine_docs_dir="docs/engine")
        unrev = [f for f in result.flags if not f.exemption]
        # Allow up to 5 vanilla flags as a buffer for cross-version drift.
        # Currently 1 (a real vanilla typo bug). If this number grows, the
        # catalog is missing accessors — re-run the bootstrap.
        self.assertLessEqual(
            len(unrev),
            5,
            f"vanilla loc has {len(unrev)} unreviewed flags; "
            f"the catalog likely needs more accessors. "
            f"First few: {[(f.key, f.chain, f.reason) for f in unrev[:5]]}",
        )


if __name__ == "__main__":
    unittest.main()
