"""The legislated tax code's generated rate amendments, script values and loc.

`scripts/generators/gen_tax_code.py` owns three files. This pins the instrument
table (index x step = rate), that every vanilla rate is an exact index, that each
amendment is rate-only and identical across the five native tax levels (a level
change then moves nothing but the political static modifier), and that
`--check` notices drift.

Run: python3 -m unittest test_tax_code_generated -v
"""

import importlib.util
import json
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from decimal import Decimal
from pathlib import Path

from test_tax_code_rule import LEVELS, VANILLA_TAX_LAWS, load, plain

ROOT = Path(__file__).resolve().parent
GENERATOR = ROOT / "scripts" / "generators" / "gen_tax_code.py"

AMENDMENTS = "common/amendments/te_tax_amendments_generated.txt"
VALUES = "common/script_values/te_tax_generated_values.txt"
LOC = "localization/english/te_tax_generated_l_english.yml"
HEADER = "# AUTO-GENERATED by scripts/generators/gen_tax_code.py — do not edit manually"

_spec = importlib.util.spec_from_file_location("gen_tax_code", GENERATOR)
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)

# The brief's instrument table, kept here independently of the generator's copy:
# key -> (modifier, step, max index, label, vanilla values it must represent).
TABLE = {
    "wage": ("tax_income_add", "0.025", 20, "Wage tax",
             "0.05 0.075 0.10 0.125 0.15 0.175 0.20 0.25 0.30"),
    "div": ("tax_dividends_add", "0.025", 20, "Dividend tax",
            "0.025 0.05 0.10 0.15 0.20 0.25 0.30"),
    "land": ("tax_land_add", "0.025", 48, "Rural assessment",
             "0.20 0.275 0.35 0.40 0.425 0.50 0.55 0.70 0.85 1.00"),
    "head": ("tax_per_capita_add", "0.05", 30, "Head tax",
             "0.40 0.55 0.70 0.85 1.00"),
    "cons": ("tax_consumption_add", "0.05", 12, "Consumption tax rate",
             "0.15 0.20 0.25 0.30 0.35"),
}
PERCENT_KEYS = ("wage", "div", "cons")


def run_generator(*args):
    return subprocess.run(
        [sys.executable, str(GENERATOR), *args],
        cwd=ROOT, capture_output=True, text=True, timeout=120,
    )


def read_loc(path):
    """{key: text} of one loc file, quotes stripped."""
    entries = {}
    for line in Path(path).read_text(encoding="utf-8-sig").splitlines():
        match = re.match(r'^ ([\w.\-]+):\d+ "(.*)"$', line)
        if match:
            entries[match.group(1)] = match.group(2)
    return entries


class InstrumentTableTest(unittest.TestCase):
    def test_generator_table_matches_the_brief(self):
        self.assertEqual([i.key for i in gen.INSTRUMENTS], list(TABLE))
        for instrument in gen.INSTRUMENTS:
            modifier, step, max_idx, label, vanilla = TABLE[instrument.key]
            with self.subTest(key=instrument.key):
                self.assertEqual(instrument.modifier, modifier)
                self.assertEqual(instrument.step, Decimal(step))
                self.assertEqual(instrument.max_idx, max_idx)
                self.assertEqual(instrument.label, label)
                self.assertEqual(instrument.vanilla, tuple(Decimal(v) for v in vanilla.split()))

    def test_every_vanilla_value_is_an_exact_index(self):
        for key, (_, step, max_idx, _, vanilla) in TABLE.items():
            for value in vanilla.split():
                with self.subTest(key=key, value=value):
                    index, remainder = divmod(Decimal(value), Decimal(step))
                    self.assertEqual(remainder, 0)
                    self.assertTrue(1 <= index <= max_idx)

    def test_table_vanilla_values_are_what_the_five_laws_carry(self):
        # The snapshot is vanilla 1.14.5: the table's "must represent exactly"
        # column is the union of what the five laws set, level by level.
        with open(ROOT / "vanilla_parsed" / "common" / "laws.json", encoding="utf-8") as handle:
            laws = plain(json.load(handle))
        for key, (modifier, _, _, _, vanilla) in TABLE.items():
            carried = set()
            for law in VANILLA_TAX_LAWS:
                for level in LEVELS:
                    value = laws[law][level].get(modifier)
                    if value is not None:
                        carried.add(Decimal(value))
            with self.subTest(key=key):
                self.assertEqual(carried, {Decimal(v) for v in vanilla.split()})

    def test_validate_rejects_a_value_that_is_not_an_index(self):
        bad = gen.Instrument("x", "tax_income_add", Decimal("0.05"), 20, "X", "payer", True,
                             (Decimal("0.075"),))
        with self.assertRaises(ValueError):
            gen.validate((bad,))


class AmendmentTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.text = (ROOT / AMENDMENTS).read_text(encoding="utf-8-sig")
        cls.amendments = load(AMENDMENTS)

    def test_every_index_up_to_the_maximum_has_exactly_one_amendment(self):
        keys = re.findall(r"^(amendment_\w+) = \{", self.text, re.M)
        self.assertEqual(len(keys), len(set(keys)), "a key is defined twice")
        expected = [
            f"amendment_te_tax_{key}_{idx}"
            for key, (_, _, max_idx, _, _) in TABLE.items()
            for idx in range(1, max_idx + 1)
        ]
        self.assertEqual(sorted(keys), sorted(expected))
        self.assertEqual(set(self.amendments), set(expected))

    def test_five_levels_identical_and_carry_only_the_instrument_at_index_times_step(self):
        for key, (modifier, step, max_idx, _, _) in TABLE.items():
            for idx in range(1, max_idx + 1):
                name = f"amendment_te_tax_{key}_{idx}"
                body = self.amendments[name]
                want = Decimal(idx) * Decimal(step)
                with self.subTest(name=name):
                    blocks = [body[level] for level in LEVELS]
                    self.assertTrue(all(block == blocks[0] for block in blocks))
                    self.assertEqual(list(blocks[0]), [modifier])
                    # Decimals, not floats: 0.025 * 3 is 0.07500000000000001 as a float.
                    self.assertEqual(Decimal(blocks[0][modifier]), want)

    def test_every_vanilla_value_is_some_amendments_rate(self):
        for key, (modifier, _, _, _, vanilla) in TABLE.items():
            rates = {
                Decimal(body[LEVELS[0]][modifier])
                for name, body in self.amendments.items()
                if name.startswith(f"amendment_te_tax_{key}_")
            }
            for value in vanilla.split():
                with self.subTest(key=key, value=value):
                    self.assertIn(Decimal(value), rates)

    def test_values_print_without_trailing_zeros_or_exponents(self):
        values = re.findall(r"tax_\w+_add = (\S+)", self.text)
        self.assertGreater(len(values), 600)
        for value in values:
            with self.subTest(value=value):
                self.assertRegex(value, r"^\d+(\.\d*[1-9])?$")
        self.assertIn("tax_income_add = 0.075", self.text)
        self.assertIn("tax_income_add = 0.1 }", self.text)
        self.assertIn("tax_land_add = 1 }", self.text)

    def test_amendment_fields(self):
        for name, body in self.amendments.items():
            with self.subTest(name=name):
                self.assertEqual(body["parent"], "law_te_tax_code")
                self.assertEqual(body["allowed_laws"], ["law_te_tax_code"])
                self.assertEqual(body["possible"], {"te_tax_code_on": "yes"})
                for field in ("would_sponsor", "can_repeal", "ai_will_revoke"):
                    self.assertEqual(body[field], {"always": "no"})
                self.assertEqual(
                    set(body),
                    {"parent", "allowed_laws", "possible", "would_sponsor", "can_repeal",
                     "ai_will_revoke", *LEVELS},
                )

    def test_template_matches_the_brief_byte_for_byte(self):
        want = (
            "amendment_te_tax_wage_3 = {\n"
            "\tparent = law_te_tax_code\n"
            "\tallowed_laws = { law_te_tax_code }\n"
            "\tpossible = { te_tax_code_on = yes }\n"
            "\tcan_repeal = { always = no }\n"
            "\twould_sponsor = { always = no }\n"
            "\tai_will_revoke = { always = no }\n"
            "\ttax_modifier_very_low = { tax_income_add = 0.075 }\n"
            "\ttax_modifier_low = { tax_income_add = 0.075 }\n"
            "\ttax_modifier_medium = { tax_income_add = 0.075 }\n"
            "\ttax_modifier_high = { tax_income_add = 0.075 }\n"
            "\ttax_modifier_very_high = { tax_income_add = 0.075 }\n"
            "}\n"
        )
        self.assertIn(want, self.text)


class GeneratedFileFormatTest(unittest.TestCase):
    def test_files_carry_bom_header_lf_and_tab_indent(self):
        for path in (AMENDMENTS, VALUES, LOC):
            raw = (ROOT / path).read_bytes()
            with self.subTest(path=path):
                self.assertTrue(raw.startswith(b"\xef\xbb\xbf"), "missing UTF-8 BOM")
                self.assertNotIn(b"\r", raw)
                self.assertTrue(raw.endswith(b"\n"))
                if path != LOC:
                    self.assertNotRegex(raw.decode("utf-8-sig"), r"(?m)^ +\S", "space indent")
        for path in (AMENDMENTS, VALUES):
            first = (ROOT / path).read_text(encoding="utf-8-sig").splitlines()[:5]
            with self.subTest(path=path):
                self.assertIn(HEADER, first)

    def test_loc_file_header_and_section(self):
        text = (ROOT / LOC).read_text(encoding="utf-8-sig")
        self.assertTrue(text.startswith("l_english:\n"))

    def test_tab_formatter_leaves_the_txt_outputs_alone(self):
        sys.path.insert(0, str(ROOT / "scripts"))
        try:
            import format_paradox_tabs
        finally:
            sys.path.pop(0)
        for path in (AMENDMENTS, VALUES):
            text = (ROOT / path).read_text(encoding="utf-8-sig")
            with self.subTest(path=path):
                self.assertEqual(format_paradox_tabs.format_text(text), text)


class ScriptValueTest(unittest.TestCase):
    def test_step_max_and_percent_step_constants(self):
        # The file also carries the te_tax_view_* display values (pinned in
        # test_tax_code_state.py), the interest-group cards' te_tax_disp_ig_*
        # values (test_tax_code_sguis.py) and the estimates' te_tax_est_* helpers
        # (test_tax_code_estimates.py) and the customs schedule's market reads
        # te_tax_cu_native_* (test_tax_code_customs.py); every other entry is one
        # of these constants.
        values = {k: v for k, v in load(VALUES).items()
                  if not k.startswith(("te_tax_view_", "te_tax_disp_ig_", "te_tax_est_", "te_tax_cu_"))}
        want = {}
        for key, (_, step, max_idx, _, _) in TABLE.items():
            want[f"te_tax_step_{key}"] = Decimal(step)
            want[f"te_tax_max_{key}"] = Decimal(max_idx)
            if key in PERCENT_KEYS:
                want[f"te_tax_pct_step_{key}"] = Decimal(step) * 100
        # The relief bands' maximum (Task 11): 0 none, 1 = -25%, 2 = -50%.
        want["te_tax_max_agrel"] = want["te_tax_max_regrel"] = Decimal(2)
        # The scheduler's history-ring slot ids (test_tax_code_scheduler.py).
        for name, value in (("none", 0), ("a", 1), ("b", 2)):
            want[f"te_tax_slot_id_{name}"] = Decimal(value)
        # The interest groups as an obligation stores its beneficiary (Task 12).
        for idx, ig in enumerate(gen.IGS, start=1):
            want[f"te_tax_ig_id_{ig}"] = Decimal(idx)
        self.assertEqual({k: Decimal(v) for k, v in values.items()}, want)


class LocTest(unittest.TestCase):
    def test_every_amendment_has_a_name_and_a_desc(self):
        loc = read_loc(ROOT / LOC)
        amendments = load(AMENDMENTS)
        for name in amendments:
            with self.subTest(name=name):
                self.assertTrue(loc.get(name), "no name")
                self.assertTrue(loc.get(f"{name}_desc"), "no desc")
        # Plus Task 13's view bands and staple offer lines (test_tax_code_offers.py).
        task13 = {f"te_tax_ig_view_{ig}_{band}{suffix}" for ig in gen.IGS for band, _ in gen.VIEW_BANDS
                  for suffix in ("", "_desc")}
        task13 |= {f"te_tax{tt}_offer_untax_{good}" for good in gen.staple_order() for tt in ("", "_tt")}
        self.assertEqual(set(loc), set(amendments) | {f"{n}_desc" for n in amendments} | task13)

    def test_names_and_descs(self):
        loc = read_loc(ROOT / LOC)
        self.assertEqual(loc["amendment_te_tax_wage_3"], "Wage Tax 7.5%")
        self.assertEqual(
            loc["amendment_te_tax_wage_3_desc"], "Taxes the wages of employed pops at 7.5%."
        )
        self.assertEqual(loc["amendment_te_tax_wage_4"], "Wage Tax 10%")
        self.assertEqual(loc["amendment_te_tax_land_17"], "Rural Assessment 0.425")
        self.assertEqual(loc["amendment_te_tax_head_8"], "Head Tax 0.4")
        self.assertEqual(loc["amendment_te_tax_cons_3"], "Consumption Tax Rate 15%")
        self.assertEqual(loc["amendment_te_tax_div_1"], "Dividend Tax 2.5%")

    def test_each_desc_names_its_payer(self):
        loc = read_loc(ROOT / LOC)
        payers = {
            "wage": "the wages of employed pops",
            "div": "dividends paid to pops who own private buildings",
            "land": "peasants and farmers working agricultural buildings, who then pay no head tax",
            "head": "working adults who pay no rural assessment",
            "cons": "goods on the taxed-goods list when pops buy them",
        }
        for key, payer in payers.items():
            with self.subTest(key=key):
                self.assertIn(payer, loc[f"amendment_te_tax_{key}_1_desc"])

    def test_percent_sign_only_on_the_rate_instruments(self):
        loc = read_loc(ROOT / LOC)
        for key, (_, _, max_idx, _, _) in TABLE.items():
            for idx in (1, max_idx):
                name = loc[f"amendment_te_tax_{key}_{idx}"]
                with self.subTest(key=key, idx=idx):
                    self.assertEqual(name.endswith("%"), key in PERCENT_KEYS)

    def test_no_square_bracket_markup(self):
        for text in read_loc(ROOT / LOC).values():
            self.assertNotIn("[b]", text)


class GeneratorCliTest(unittest.TestCase):
    def test_check_passes_on_the_committed_outputs(self):
        result = run_generator("--check")
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_write_into_an_empty_root_reproduces_the_committed_files(self):
        with tempfile.TemporaryDirectory() as tmp:
            result = run_generator("--root", tmp)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            for path in (AMENDMENTS, VALUES, LOC):
                with self.subTest(path=path):
                    self.assertEqual((Path(tmp) / path).read_bytes(), (ROOT / path).read_bytes())
            self.assertEqual(run_generator("--check", "--root", tmp).returncode, 0)

    def test_check_names_every_drifted_file_and_writes_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            for path in (AMENDMENTS, VALUES, LOC):
                target = Path(tmp) / path
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(ROOT / path, target)
            edited = Path(tmp) / AMENDMENTS
            edited.write_bytes(edited.read_bytes().replace(b"0.075", b"0.076", 1))
            (Path(tmp) / VALUES).unlink()
            before = edited.read_bytes()
            result = run_generator("--check", "--root", tmp)
            self.assertEqual(result.returncode, 1)
            self.assertIn(AMENDMENTS, result.stdout + result.stderr)
            self.assertIn(VALUES, result.stdout + result.stderr)
            self.assertNotIn(LOC, result.stdout + result.stderr)
            self.assertEqual(edited.read_bytes(), before)
            self.assertFalse((Path(tmp) / VALUES).exists())

    def test_generator_runs_on_system_python_without_third_party_modules(self):
        # organize_loc and paradox_file_parser are the repo's own, standard-library-only modules.
        source = GENERATOR.read_text(encoding="utf-8")
        imports = set(re.findall(r"^(?:from|import) (\w+)", source, re.M))
        third_party = imports - set(sys.stdlib_module_names) - {"organize_loc", "paradox_file_parser"}
        self.assertEqual(third_party, set())
        parser_source = (ROOT / "paradox_file_parser.py").read_text(encoding="utf-8")
        parser_imports = set(re.findall(r"^(?:from|import) (\w+)", parser_source, re.M))
        self.assertEqual(parser_imports - set(sys.stdlib_module_names), set())


class OrganizeLocAgreementTest(unittest.TestCase):
    """organize_loc deletes and rewrites every loc file; it must reproduce these two."""

    @classmethod
    def setUpClass(cls):
        import contextlib
        import io

        import organize_loc

        cls.organize_loc = organize_loc
        with contextlib.redirect_stdout(io.StringIO()):
            cls.plan = organize_loc.build_output_plan(str(ROOT))

    def test_generated_loc_is_what_organize_loc_writes(self):
        rendered = self.organize_loc._render_loc_file(self.plan["te_tax_generated_l_english.yml"])
        self.assertEqual(rendered, (ROOT / LOC).read_bytes())

    def test_hand_written_tax_loc_stays_in_its_own_file(self):
        rendered = self.organize_loc._render_loc_file(self.plan["te_tax_l_english.yml"])
        self.assertEqual(rendered, (ROOT / "localization/english/te_tax_l_english.yml").read_bytes())


if __name__ == "__main__":
    unittest.main()
