"""The generated land-area table (te_region_area_generated.txt) against the map.

The Settlement Authority's frontier test divides a region's population by its
area in km² (docs/superpowers/specs/2026-09-26-internal-resettlement-design.md
§6). Script cannot count provinces, so scripts/generators/gen_region_area.py
writes the area of every land state region into a scripted effect. A region
missing from it can never be a frontier; a stale version never re-runs in old
saves. This file pins both, and a few areas against the real world.

Run: python3 -m unittest test_region_area -v
"""
import importlib.util
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent
GENERATED = ROOT / "common/scripted_effects/te_region_area_generated.txt"
ON_ACTIONS = ROOT / "common/on_actions/te_region_area_on_actions.txt"

_spec = importlib.util.spec_from_file_location(
    "gen_region_area", ROOT / "scripts/generators/gen_region_area.py")
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)

ENTRY_RE = re.compile(
    r"s:(STATE_[A-Z0-9_]+) = \{ set_variable = \{ name = te_region_area value = (\d+) \} \}")

# Real-world areas (km²) of regions whose map outline matches the real unit.
# The pixel method lands within about 10%; 12% leaves room for map outlines.
REAL_KM2 = {
    "STATE_HOKKAIDO": 83424,
    "STATE_KANSAS": 213100,
    "STATE_ICELAND": 103000,
    "STATE_ILE_DE_FRANCE": 12012,
    "STATE_CEYLON": 65610,
    "STATE_SOUTH_ISLAND": 150437,
}


def _areas():
    return {m.group(1): int(m.group(2))
            for m in ENTRY_RE.finditer(GENERATED.read_text(encoding="utf-8-sig"))}


class RegionAreaTests(unittest.TestCase):
    def test_every_land_region_has_one_positive_area(self):
        text = GENERATED.read_text(encoding="utf-8-sig")
        land = set(gen.land_regions())
        areas = _areas()
        self.assertEqual(set(areas), land)
        for region in land:
            self.assertEqual(len(re.findall(rf"s:{region} = ", text)), 1, region)
            self.assertGreater(areas[region], 0, region)

    def test_no_sea_region_is_listed(self):
        seas = (ROOT / "map_data/state_regions/99_seas.txt").read_text(encoding="utf-8-sig")
        sea_names = set(re.findall(r"(?m)^﻿?(STATE_[A-Z0-9_]+)\s*=", seas))
        self.assertFalse(sea_names & set(_areas()))

    def test_areas_match_the_real_world(self):
        areas = _areas()
        for region, real in REAL_KM2.items():
            ratio = areas[region] / real
            self.assertTrue(0.88 <= ratio <= 1.12, f"{region}: {areas[region]} vs {real} ({ratio:.2f})")

    def test_header_and_version_guard(self):
        text = GENERATED.read_text(encoding="utf-8-sig")
        self.assertTrue(text.startswith("# AUTO-GENERATED by scripts/generators/gen_region_area.py"))
        self.assertIn(f"NOT = {{ global_var:te_region_area_version = {gen.VERSION} }}", text)
        self.assertIn(f"set_global_variable = {{ name = te_region_area_version value = {gen.VERSION} }}", text)

    def test_runs_at_game_start_and_monthly(self):
        text = ON_ACTIONS.read_text(encoding="utf-8-sig")
        for hook in ("on_game_started", "on_monthly_pulse"):
            m = re.search(hook + r"\s*=\s*\{\s*on_actions\s*=\s*\{([^}]*)\}", text)
            self.assertIsNotNone(m, hook)
            self.assertIn("te_region_area_on_action", m.group(1))
        self.assertIn("te_set_region_areas_if_stale = yes", text)


if __name__ == "__main__":
    unittest.main()
