#!/usr/bin/env python3
"""Nightly mod audit target selector.

Runs as the first step of every Claude Code Routine invocation. Picks ~2500
lines of mod content across <=8 files, weights by recency + light random jitter,
and writes a tailored audit prompt + targets manifest to
docs/audits/nightly/<date>/.

Stdlib only. See docs/audits/nightly_audit_README.md for the full design.
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import os
import random
import re
import sys
from datetime import date as Date, datetime
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parent.parent
STATE_FILE = REPO_ROOT / "docs/audits/.nightly_coverage.json"
OUT_DIR_BASE = REPO_ROOT / "docs/audits/nightly"
AUTOGEN_REGISTRY = REPO_ROOT / "docs/auto_generated_files.md"
CHECKLIST_DIR = REPO_ROOT / "docs/audits/nightly_checklists"

LINE_BUDGET = 2500
FILE_CAP = 15
SLICE_CAP = 600
RECENT_FINDINGS_CAP = 3
LARGE_NUM = 100_000
DECAY_DAYS = 90
# Per-new-doc penalty applied during greedy selection. Each doc a candidate
# would add to the auditor's reading list subtracts this much from its effective
# score, biasing picks toward files that share docs with already-selected
# targets. ~5 days of staleness equivalent — soft cluster, stale outliers still
# break in.
NEW_DOC_PENALTY = 5.0

SCAN_ROOTS = ["common", "events", "gui", "localization/english", "map_data", "gfx"]

# Mod content wholly regenerated by tools — editing gets overwritten. These are
# the entries the drift check diffs against `docs/auto_generated_files.md`.
EXCLUDED_REGISTRY_GLOBS = [
    "common/ideologies/modified.txt",
    "common/interest_groups/00_*.txt",
    "common/buy_packages/00_buy_packages.txt",
    "common/script_values/auto_combat_unit_market_costs.txt",
    "common/scripted_effects/company_building_cleanup_effects.txt",
    "common/geographic_regions/te_formable_regions_generated.txt",
    "map_data/state_regions/*.txt",
]

# Repo scaffolding — never registry-tracked, never audited. Not in drift diff.
ALWAYS_EXCLUDED_GLOBS = [
    "descriptor.mod",
    ".metadata/*",
    "thumbnail.png",
]

EXCLUDED_GLOBS = EXCLUDED_REGISTRY_GLOBS + ALWAYS_EXCLUDED_GLOBS

# Files that appear in docs/auto_generated_files.md but are intentionally audited
# (generator only manages comments or specific keys; bodies are hand-authored).
# Keep this list aligned with the registry's "wholly regenerated" vs "partially
# managed" distinction. Drift check uses this to suppress noise.
INTENTIONALLY_NOT_EXCLUDED = {
    "localization/english/te_*_l_english.yml": "strings hand-authored; organize_loc.py only sorts/categorizes",
    "common/production_methods/extra_pms.txt": "PM bodies hand-authored; only cost-comment headers managed by pm_costs.py",
    "common/production_methods/unique_pms.txt": "PM bodies hand-authored; only cost-comment headers managed by pm_costs.py",
    "common/combat_unit_types/extra_combat_units.txt": "unit bodies hand-authored; only cost-comment headers managed",
    "common/mobilization_options/extra_mobilization_options.txt": "unit bodies hand-authored; only cost-comment headers managed",
    "common/buildings/company_buildings.txt": "one-shot bootstrap, hand-edited after",
    "common/buildings/unique_pm_groups.txt": "one-shot bootstrap, hand-edited after",
    "common/buildings/unique_pms.txt": "one-shot bootstrap, hand-edited after",
    "common/company_types/extra_companies_vanilla_updates.txt": "one-shot bootstrap, hand-edited after",
    "localization/english/te_buildings_l_english.yml": "mostly hand-authored, generator only appends/preserves",
    "localization/english/te_power_bloc_unlocks_l_english.yml": "mostly hand-authored, generator only manages *_desc keys",
    "localization/english/extra_law_events_l_english.yml": "bootstrap dump, hand-edited freely after",
    "localization/english/ministry_law_events_l_english.yml": "bootstrap dump, hand-edited freely after",
    "common/production_method_groups/unique_pm_groups.txt": "one-shot bootstrap, hand-edited after",
    "common/prestige_goods/extra_prestige_goods.txt": "only `texture =` lines auto-managed by gen_prestige_icons.py; rest hand-authored",
    # Vanilla data referenced as INPUT to generators (not outputs). The registry
    # mentions them in the "Input:" column; the parser can't distinguish.
    "common/goods/*.txt": "input to pm_costs.py — vanilla goods data, not generator output",
    "common/ideologies/*.txt": "input to apply_ideologies.py — vanilla ideology data (modified.txt is the actual output)",
    "common/strategic_regions/*.txt": "input to gen_formable_regions.py — vanilla data, not generator output",
    "common/modifier_type_definitions/tech_gate_modifier_types.txt": "input to gen_pb_principle_unlock_descs.py — hand-authored modifier defs",
    "common/power_bloc_principles/extra_power_bloc_principles.txt": "input to gen_pb_principle_unlock_descs.py — hand-authored",
}

ALWAYS_READ = [
    "CLAUDE.md",
    "docs/guides/scripting_best_practices.md",
    "docs/vanilla/CLAUDE.md",
    "docs/audits/open_issues.md",
    "docs/vanilla/vanilla_known_bugs.md",
]

# Path-pattern mapping: each entry is (compiled_regex, [docs], area_checklist).
# Evaluated in order; the FIRST match determines area. All matching entries
# contribute docs (deduplicated, original order preserved).
_DOC_MAPPING_RAW: list[tuple[str, list[str], str]] = [
    # Events — most-specific first, generic fallback last
    (r"^events/(economic|banking|te_construction_market)",
     ["docs/guides/event_creation_guide.md", "docs/vanilla/vanilla_economy_reference.md", "docs/systems/mod_systems.md"],
     "events"),
    (r"^events/(political|modern_election|movement|extra_law|ministry_law|social_tensions|irredentism|heir_education|religious_revival|mental_health|environmentalism|augmentation|post_scarcity)",
     ["docs/guides/event_creation_guide.md", "docs/vanilla/vanilla_politics_reference.md"],
     "events"),
    (r"^events/(un_|international_relations|dp_escalation|treaty_article)",
     ["docs/guides/event_creation_guide.md", "docs/vanilla/vanilla_diplomacy_reference.md", "docs/vanilla/treaty_articles_reference.md"],
     "events"),
    (r"^events/(space_|society_technology|wonder)",
     ["docs/guides/event_creation_guide.md", "docs/vanilla/vanilla_technology_reference.md", "docs/vanilla/wonder_buildings_reference.md"],
     "events"),
    (r"^events/(nuclear|world_war|covert|surveillance|probe_result)",
     ["docs/guides/event_creation_guide.md", "docs/vanilla/vanilla_war_reference.md"],
     "events"),
    (r"^events/(decolonization|cultural_hegemony)",
     ["docs/guides/event_creation_guide.md", "docs/vanilla/vanilla_colonization_reference.md", "docs/vanilla/vanilla_pops_reference.md"],
     "events"),
    (r"^events/(te_map_modes|repeatable|minor|te_construction_market_pulse|te_construction_market_recalc)",
     ["docs/guides/event_creation_guide.md"],
     "events"),
    (r"^events/",
     ["docs/guides/event_creation_guide.md"],
     "events"),
    # Journal entries
    (r"^common/journal_entries/",
     ["docs/systems/journal_entry_systems.md", "docs/systems/mod_systems.md"],
     "journal_entries"),
    (r"^common/journal_entry_groups/",
     ["docs/systems/journal_entry_systems.md"],
     "journal_entries"),
    # Laws & politics
    (r"^common/(laws|law_groups|interest_groups|interest_group_traits|political_movements|political_movement_pop_support|parties|ideologies|government_types|amendments|institutions)/",
     ["docs/vanilla/vanilla_politics_reference.md"],
     "laws_and_politics"),
    # Diplomacy / power blocs / treaties
    (r"^common/(diplomatic_actions|diplomatic_plays|power_blocs|power_bloc_principle_groups|power_bloc_principles|power_bloc_identities|power_bloc_names|subject_types|treaty_articles)/",
     ["docs/vanilla/vanilla_diplomacy_reference.md", "docs/vanilla/treaty_articles_reference.md"],
     "laws_and_politics"),
    # Companies, formables
    (r"^common/(companies|company_types|company_charter_types)/",
     ["docs/vanilla/vanilla_company_buildings_reference.md"],
     "production_methods_and_buildings"),
    (r"^common/(country_formation|dynamic_country_names|dynamic_treaty_names|country_definitions|country_ranks|flag_definitions)/",
     ["docs/vanilla/vanilla_formable_countries_reference.md"],
     "laws_and_politics"),
    # Production / buildings / goods / pop needs
    (r"^common/(production_methods|production_method_groups|buildings|building_groups|goods|prestige_goods|buy_packages|pop_needs|harvest_condition_types)/",
     ["docs/vanilla/vanilla_economy_reference.md"],
     "production_methods_and_buildings"),
    # Technology
    (r"^common/technology/",
     ["docs/vanilla/vanilla_technology_reference.md"],
     "technologies"),
    # Pops / culture / religion / discrimination
    (r"^common/(pop_needs|discrimination_traits|religions|named_colors)/",
     ["docs/vanilla/vanilla_pops_reference.md"],
     "laws_and_politics"),
    # States / regions / decrees
    (r"^common/(strategic_regions|geographic_regions|decrees)/",
     ["docs/vanilla/vanilla_states_reference.md"],
     "production_methods_and_buildings"),
    # War / military
    (r"^common/(combat_unit_types|combat_unit_groups|combat_unit_experience_levels|mobilization_options|mobilization_option_groups|ship_types|ship_modifications|ship_name_definitions|war_goal_types|battle_conditions)/",
     ["docs/vanilla/vanilla_war_reference.md"],
     "production_methods_and_buildings"),
    # Scripted helpers, rules, GUIs, on_actions
    (r"^common/(scripted_effects|scripted_triggers|scripted_buttons|scripted_progress_bars|scripted_rules|scripted_guis|on_actions|messages|customizable_localization|ai_strategies|script_values)/",
     ["docs/audits/script_parameterization_audit.md"],
     "scripted_effects_and_triggers"),
    # Characters
    (r"^common/(character_traits|character_interactions)/",
     ["docs/vanilla/vanilla_politics_reference.md"],
     "laws_and_politics"),
    # Modifiers
    (r"^common/(static_modifiers|modifier_type_definitions)/",
     ["docs/engine/vic3_modifier_type_definitions_reference.md", "docs/engine/modifier_patterns.md"],
     "production_methods_and_buildings"),
    # Concepts
    (r"^common/game_concepts/",
     ["docs/engine/concept_reference_report.md"],
     "localization"),
    # Game rules
    (r"^common/game_rules/",
     ["README.md"],
     "journal_entries"),
    # History
    (r"^common/history/",
     ["docs/vanilla/vanilla_states_reference.md"],
     "laws_and_politics"),
    # Generic common/ fallback
    (r"^common/",
     [],
     "scripted_effects_and_triggers"),
    # GUI
    (r"^gui/",
     ["docs/guides/gui_modding_guide.md"],
     "gui"),
    # Map data
    (r"^map_data/",
     ["docs/vanilla/vanilla_states_reference.md"],
     "production_methods_and_buildings"),
    # gfx text files
    (r"^gfx/.*\.(gfx|asset)$",
     [],
     "gui"),
    # Localization (always last because of broad pattern)
    (r"^localization/english/.*\.yml$",
     ["docs/guides/event_creation_guide.md"],
     "localization"),
]

DOC_MAPPING = [(re.compile(p), docs, area) for p, docs, area in _DOC_MAPPING_RAW]


# --------------------------------------------------------------------------- #
# File enumeration & exclusion
# --------------------------------------------------------------------------- #

def is_binary_file(path: Path) -> bool:
    """Heuristic: a file is binary if its first 1KB contains a NUL byte.

    Fast and reliable for distinguishing text from .dds/.png/.tga/etc. UTF-8
    text files with BOMs or non-ASCII chars pass this check correctly.
    """
    try:
        with open(path, "rb") as f:
            chunk = f.read(1024)
    except OSError:
        return True
    return b"\x00" in chunk


def has_autogen_marker(path: Path) -> bool:
    """Check the first 10 lines for AUTO-GENERATED / do not edit manually markers."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            for _ in range(10):
                line = f.readline()
                if not line:
                    break
                if "AUTO-GENERATED" in line or "do not edit manually" in line:
                    return True
    except OSError:
        return False
    return False


def matches_any_glob(rel_path: str, globs: Iterable[str]) -> bool:
    """fnmatch each glob against the relative path."""
    for g in globs:
        if fnmatch.fnmatch(rel_path, g):
            return True
        # Also match if the glob is a directory prefix
        if g.endswith("/*") and rel_path.startswith(g[:-2] + "/"):
            return True
    return False


def enumerate_candidates() -> list[tuple[Path, str, int]]:
    """Walk SCAN_ROOTS and return (abs_path, rel_path, line_count) for each
    candidate. Excludes binary files, autogen-marked files, and EXCLUDED_GLOBS."""
    candidates: list[tuple[Path, str, int]] = []
    for root_rel in SCAN_ROOTS:
        root = REPO_ROOT / root_rel
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            rel = path.relative_to(REPO_ROOT).as_posix()
            if matches_any_glob(rel, EXCLUDED_GLOBS):
                continue
            if is_binary_file(path):
                continue
            if has_autogen_marker(path):
                continue
            try:
                with open(path, "r", encoding="utf-8", errors="replace") as f:
                    line_count = sum(1 for _ in f)
            except OSError:
                continue
            if line_count == 0:
                continue
            candidates.append((path, rel, line_count))
    return candidates


# --------------------------------------------------------------------------- #
# State file
# --------------------------------------------------------------------------- #

def load_state() -> dict:
    if not STATE_FILE.exists():
        return {"version": 1, "files": {}}
    try:
        with open(STATE_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return {"version": 1, "files": {}}
    data.setdefault("version", 1)
    data.setdefault("files", {})
    return data


# --------------------------------------------------------------------------- #
# Scoring & selection
# --------------------------------------------------------------------------- #

def seeded_rng(date_str: str) -> random.Random:
    seed = int(hashlib.sha256(date_str.encode("utf-8")).hexdigest()[:8], 16)
    return random.Random(seed)


def days_since(iso_date: str | None, today: Date) -> int:
    if not iso_date:
        return LARGE_NUM
    try:
        last = datetime.strptime(iso_date, "%Y-%m-%d").date()
    except ValueError:
        return LARGE_NUM
    return max(0, (today - last).days)


def score_candidate(rel: str, state: dict, today: Date, rng: random.Random) -> float:
    file_state = state.get("files", {}).get(rel, {})
    days = days_since(file_state.get("last_audited"), today)
    findings = file_state.get("recent_findings", 0) or 0
    recency_boost = min(findings, RECENT_FINDINGS_CAP) * 0.5
    jitter = rng.uniform(0.0, 1.0)
    return days + recency_boost + jitter


def pick_slice(line_count: int, partial_coverage: list[list[int]]) -> tuple[int, int]:
    """Pick a contiguous slice of length min(line_count, SLICE_CAP) with least
    overlap to any prior coverage range. partial_coverage is [[start, end], ...]."""
    if line_count <= SLICE_CAP:
        return (1, line_count)
    step = max(SLICE_CAP // 4, 50)
    best_range = (1, SLICE_CAP)
    best_overlap = None
    for start in range(1, line_count - SLICE_CAP + 2, step):
        end = start + SLICE_CAP - 1
        overlap = 0
        for prior in partial_coverage:
            ps, pe = prior[0], prior[1]
            overlap += max(0, min(end, pe) - max(start, ps) + 1)
        if best_overlap is None or overlap < best_overlap:
            best_overlap = overlap
            best_range = (start, end)
    # Also consider the very last possible slice (covers the tail when step misses it)
    tail_start = line_count - SLICE_CAP + 1
    tail_end = line_count
    tail_overlap = sum(
        max(0, min(tail_end, p[1]) - max(tail_start, p[0]) + 1)
        for p in partial_coverage
    )
    if best_overlap is None or tail_overlap < best_overlap:
        best_range = (tail_start, tail_end)
    return best_range


def area_and_docs(rel: str) -> tuple[str, list[str]]:
    """Determine the area (checklist name) and the doc-reading list for a file."""
    docs: list[str] = []
    area: str | None = None
    for pattern, mapped_docs, mapped_area in DOC_MAPPING:
        if pattern.search(rel):
            if area is None:
                area = mapped_area
            for d in mapped_docs:
                if d not in docs:
                    docs.append(d)
    if area is None:
        area = "general"
    return area, docs


def select_targets(candidates: list[tuple[Path, str, int]], state: dict,
                   today: Date, rng: random.Random) -> list[dict]:
    """Iterative greedy pick under LINE_BUDGET / FILE_CAP, with per-file
    slicing and a marginal-new-doc penalty.

    Seed pick is by base score alone. For each subsequent pick the effective
    score is `base - NEW_DOC_PENALTY * |candidate.docs - selected_docs|`,
    biasing toward files that don't expand the auditor's reading list.
    """
    pool = []
    for abs_path, rel, line_count in candidates:
        base = score_candidate(rel, state, today, rng)
        _, docs = area_and_docs(rel)
        pool.append({
            "base": base,
            "abs_path": abs_path,
            "rel": rel,
            "line_count": line_count,
            "docs": docs,
        })

    targets: list[dict] = []
    total_lines = 0
    selected_docs: set[str] = set()

    while pool and len(targets) < FILE_CAP:
        if not targets:
            # Seed: pure base-score order.
            pool.sort(key=lambda c: c["base"], reverse=True)
        else:
            pool.sort(
                key=lambda c: c["base"]
                - NEW_DOC_PENALTY * len(set(c["docs"]) - selected_docs),
                reverse=True,
            )

        picked_idx: int | None = None
        for i, cand in enumerate(pool):
            file_state = state.get("files", {}).get(cand["rel"], {})
            partial = file_state.get("partial_coverage", []) or []
            if cand["line_count"] > SLICE_CAP:
                line_range = list(pick_slice(cand["line_count"], partial))
                slice_lines = line_range[1] - line_range[0] + 1
            else:
                line_range = None
                slice_lines = cand["line_count"]

            if total_lines + slice_lines > LINE_BUDGET and targets:
                # Doesn't fit — try the next candidate (some may be smaller).
                continue

            # Either fits, or this is the seed and exceeds budget alone — take it.
            area, docs = area_and_docs(cand["rel"])
            effective = cand["base"] - NEW_DOC_PENALTY * len(
                set(docs) - selected_docs
            ) if targets else cand["base"]
            targets.append({
                "path": cand["rel"],
                "line_range": line_range,
                "lines": slice_lines,
                "area": area,
                "docs": docs,
                "score": round(effective, 3),
                "last_audited": file_state.get("last_audited"),
                "audit_count": file_state.get("audit_count", 0),
                "recent_findings": file_state.get("recent_findings", 0),
            })
            total_lines += slice_lines
            selected_docs.update(docs)
            picked_idx = i
            break

        if picked_idx is None:
            # No remaining candidate fits the budget.
            break
        pool.pop(picked_idx)

    return targets


# --------------------------------------------------------------------------- #
# Registry drift check
# --------------------------------------------------------------------------- #

_PATH_LIKE_RE = re.compile(r"`([^`]+)`")
_EXT_RE = re.compile(r"\.[a-z]{2,5}$")
_BINARY_EXT_RE = re.compile(r"\.(dds|png|tga|jpg|jpeg|webp|gif|wav|ogg|mp3|asset|mesh)\b")


def _is_audit_relevant(entry: str) -> bool:
    """Drift only matters for paths/globs that would be audit candidates: under
    SCAN_ROOTS, and not obviously binary."""
    if not any(entry == root or entry.startswith(root + "/") for root in SCAN_ROOTS):
        return False
    if _BINARY_EXT_RE.search(entry):
        return False
    # `gfx/.../icons/*` patterns without extension are DDS icon dirs
    if "/icons/" in entry and entry.endswith("*"):
        return False
    return True


def parse_autogen_registry() -> set[str]:
    """Extract path-like entries from docs/auto_generated_files.md backtick-quoted cells.

    Strips triple-backtick code blocks first — otherwise the inline-backtick regex
    matches across them and swallows real paths as junk.
    """
    if not AUTOGEN_REGISTRY.exists():
        return set()
    text = AUTOGEN_REGISTRY.read_text(encoding="utf-8", errors="replace")
    text = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
    paths: set[str] = set()
    for match in _PATH_LIKE_RE.finditer(text):
        candidate = match.group(1).strip()
        if "/" not in candidate:
            continue
        if not (_EXT_RE.search(candidate) or "*" in candidate):
            continue
        if candidate.startswith(("http://", "https://", "~/", "./")):
            continue
        if any(c in candidate for c in (" ", "(", ")", "$")):
            continue
        # Out of audit scope entirely
        if candidate.startswith("docs/data/"):
            continue
        paths.add(candidate)
    return paths


def detect_registry_drift() -> tuple[list[str], list[str]]:
    """Returns (registry_not_excluded, excluded_globs_not_in_registry).

    Only considers paths under SCAN_ROOTS and non-binary extensions — drift on
    docs/, scripts/, gfx icons, or scaffolding (always-excluded by policy) is
    not actionable for the audit.
    """
    registry = {e for e in parse_autogen_registry() if _is_audit_relevant(e)}
    excluded = set(EXCLUDED_REGISTRY_GLOBS)
    known_partial = set(INTENTIONALLY_NOT_EXCLUDED.keys())

    not_excluded: list[str] = []
    for entry in sorted(registry):
        if entry in known_partial:
            continue
        if any(fnmatch.fnmatch(entry, g) for g in excluded):
            continue
        if any(fnmatch.fnmatch(entry, g) for g in known_partial):
            continue
        not_excluded.append(entry)

    orphaned: list[str] = []
    for glob in sorted(excluded):
        if any(fnmatch.fnmatch(reg, glob) for reg in registry):
            continue
        if glob in registry:
            continue
        orphaned.append(glob)

    return not_excluded, orphaned


# --------------------------------------------------------------------------- #
# Prompt rendering
# --------------------------------------------------------------------------- #

def render_prompt(date_str: str, targets: list[dict],
                  drift_added: list[str], drift_orphaned: list[str],
                  with_report: bool) -> str:
    # Deduplicated doc-reading list (always-read first, then per-target docs)
    doc_list: list[str] = list(ALWAYS_READ)
    used_areas: set[str] = set()
    for t in targets:
        used_areas.add(t["area"])
        for d in t["docs"]:
            if d not in doc_list:
                doc_list.append(d)
    for area in sorted(used_areas):
        cl = f"docs/audits/nightly_checklists/{area}.md"
        if (REPO_ROOT / cl).exists() and cl not in doc_list:
            doc_list.append(cl)

    lines: list[str] = []
    lines.append(f"# Nightly mod audit — {date_str}")
    lines.append("")
    lines.append("Generated by `scripts/nightly_audit_select.py`. Read `docs/audits/nightly_audit_README.md` first if you haven't.")
    lines.append("")
    lines.append("## What you're doing")
    lines.append("")
    lines.append("Audit the slice of mod content below for things the procedural audits *don't* catch:")
    lines.append("internal logic, mod-convention adherence, balance/coherence vs peers, localization tone.")
    lines.append("File findings as GitHub issues; fix what's trivially fixable as PRs.")
    lines.append("")
    lines.append("## Pre-audit reading (in order)")
    lines.append("")
    for d in doc_list:
        lines.append(f"- `{d}`")
    lines.append("")
    lines.append("Also skim `gh issue list --search nightly-audit --state open --limit 30` and")
    lines.append("`gh issue list --state open --limit 30` to avoid duplicate filings.")
    lines.append("")
    lines.append("## Tooling available")
    lines.append("")
    lines.append("`mod_state_server` is running on `http://localhost:8950`. Prefer it over raw file reads for engine-surface questions:")
    lines.append("")
    lines.append("- `curl 'http://localhost:8950/modifier-search?q=<name>'` — validate a modifier name (catches typos / unregistered dynamic patterns).")
    lines.append("- `curl http://localhost:8950/engine-docs/origin/<name>` — confirm an effect / trigger / modifier exists in this vanilla version.")
    lines.append("- `curl http://localhost:8950/events/<name>` — fetch a parsed event.")
    lines.append("- `curl http://localhost:8950/scripted_triggers/<name>` / `/scripted_effects/<name>`.")
    lines.append("- `curl http://localhost:8950/status` if a call returns nothing — confirms the server is up.")
    lines.append("- Full endpoint inventory: `curl http://localhost:8950/help` or `docs/guides/python_tools.md`.")
    lines.append("")
    lines.append("## Targets")
    lines.append("")
    lines.append("| # | File | Lines | Area | Last audited | Count | Recent findings |")
    lines.append("|---|---|---|---|---|---|---|")
    for i, t in enumerate(targets, 1):
        if t["line_range"]:
            lines_cell = f"{t['line_range'][0]}–{t['line_range'][1]} ({t['lines']})"
        else:
            lines_cell = f"all ({t['lines']})"
        last = t["last_audited"] or "never"
        lines.append(
            f"| {i} | `{t['path']}` | {lines_cell} | {t['area']} | {last} | {t['audit_count']} | {t['recent_findings']} |"
        )
    lines.append("")
    total = sum(t["lines"] for t in targets)
    lines.append(f"**Budget**: {total} of {LINE_BUDGET} lines, {len(targets)} of {FILE_CAP} files.")
    lines.append("")

    if drift_added or drift_orphaned:
        lines.append("## Registry drift")
        lines.append("")
        lines.append("`docs/auto_generated_files.md` and `EXCLUDED_GLOBS` (in `scripts/nightly_audit_select.py`) have drifted.")
        lines.append("Investigate as part of this audit; if action is needed, update `EXCLUDED_GLOBS` or `INTENTIONALLY_NOT_EXCLUDED` in the script accordingly.")
        lines.append("")
        if drift_added:
            lines.append("**In registry but not excluded** (newly generator-managed files? — add to `EXCLUDED_GLOBS` or `INTENTIONALLY_NOT_EXCLUDED`):")
            lines.append("")
            for p in drift_added:
                lines.append(f"- `{p}`")
            lines.append("")
        if drift_orphaned:
            lines.append("**Excluded globs no longer in registry** (generator removed? glob stale?):")
            lines.append("")
            for p in drift_orphaned:
                lines.append(f"- `{p}`")
            lines.append("")

    lines.append("## Focus ranking")
    lines.append("")
    lines.append("Prioritize, in this order:")
    lines.append("")
    lines.append("1. **Internal logic** — triggers fire when intended, effects do what's described, no orphan references, scope chains valid, modifier durations in correct units (days vs months — note `*_modifier_time` constants are days), state-scoped scaling runs from `on_yearly_pulse_state`.")
    lines.append("2. **Mod convention adherence** — patterns documented in `CLAUDE.md` § Building blocks and `docs/guides/scripting_best_practices.md`. **If you see repeated convention violations across files, flag it as a question for the user** rather than fixing each instance — the convention may need to broaden.")
    lines.append("3. **Balance / design coherence** — within-system consistency, ludo-narrative consistency (e.g. becoming an exploited dependency shouldn't raise SoL), modifier magnitudes out of whack vs peers.")
    lines.append("4. **Localization narrative / style** — tone consistency (`event_creation_guide.md` § General Tone), mechanical-narrative alignment.")
    lines.append("")
    lines.append("Explicitly **deprioritized** (don't actively search — these are covered by procedural audits running on `/reload`):")
    lines.append("")
    lines.append("- Syntax / parser correctness (the engine and `paradox_file_parser.py` flag these)")
    lines.append("- Loc completeness (`loc_coverage_audit`)")
    lines.append("- Modifier visibility (`modifier_visibility_audit`)")
    lines.append("- Magnitude-based event fast-scaling (`event_magnitude_audit`)")
    lines.append("- `kill_character` guards (`kill_character_audit`)")
    lines.append("- Concept link presence (`concept_reference_audit`)")
    lines.append("- Localization accessor chain parse-validity (`localization_accessor_audit`)")
    lines.append("- Performance hazards (flag obvious ones only)")
    lines.append("")

    has_loc_target = any(t["path"].startswith("localization/english/") for t in targets)
    if has_loc_target:
        lines.append("## Loc-file self-instrumentation")
        lines.append("")
        lines.append("For each `localization/english/*.yml` target above, **as your first step on that file**:")
        lines.append("list the entity-type prefixes you find in its keys (`event_`, `je_`, `law_`, `building_`, `pm_`, `decree_`, ...).")
        lines.append("In wrap-up, note whether the docs pre-loaded for this file were the right ones,")
        lines.append("what else you ended up needing, and any prefixes the loc heuristic didn't predict.")
        lines.append("This data refines the loc heuristic over time.")
        lines.append("")

    lines.append("## Bar for filing")
    lines.append("")
    lines.append("Every finding must include:")
    lines.append("")
    lines.append("- A specific `file:line` reference.")
    lines.append("- A concrete proposed fix **or** a specific question to the user.")
    lines.append("- Reasoning tied to a doc, a convention, or a vanilla mechanic (cite the source).")
    lines.append("")
    lines.append("\"This section feels underspecified\" without a concrete proposal does not get filed.")
    lines.append("")
    lines.append("## Auto-fix rule")
    lines.append("")
    lines.append("> If fixing it is no more effort than filing an issue, fix it directly via PR. Otherwise, file an issue.")
    lines.append("")
    lines.append("Judgment-based, not category-based. Calibrating examples:")
    lines.append("")
    lines.append("- Typo in a loc string → fix.")
    lines.append("- Missing `# REVIEWED YYYY-MM-DD` on a known-intentional suppression → fix.")
    lines.append("- Two effects firing in the wrong order per a clear doc rule → fix.")
    lines.append("- A modifier that's wrong by 30× because months were used in place of days → fix.")
    lines.append("- A whole system of events whose IG approvals don't match the politics reference → **issue** (the system may need re-thinking, not 12 patches).")
    lines.append("- Anything where the fix depends on understanding designer intent → **issue**.")
    lines.append("")
    lines.append(f"**Cap**: {5} files / {50} lines changed per night across all auto-fix PRs. If more would fit, fix some and file an issue listing the rest.")
    lines.append("")
    lines.append("**Branch + PR convention**:")
    lines.append("")
    lines.append("- Branch: `nightly-audit/YYYY-MM-DD-<short-slug>` from `main`.")
    lines.append("- PR title: `nightly-audit(YYYY-MM-DD): <short description>`.")
    lines.append("- PR body: cite the auto-fix rule, link to this night's `docs/audits/nightly/<date>/` directory, list the rule each fix passes.")
    lines.append("")
    lines.append("## Fast verify after fixes")
    lines.append("")
    lines.append("After each batch of mod-file edits (and before opening the PR):")
    lines.append("")
    lines.append("1. `curl -X POST 'http://localhost:8950/reload?mod_only=true&audits_only=true'` — fast (~25s vs ~90s for a full reload); reuses the cached vanilla parse and skips the file-rewriting generators. The only on-disk side effect is updates to `docs/engine/*_report.md` reflecting the new warnings.")
    lines.append("2. Inspect the response's `warnings` array. If a warning references one of your edits, revert that hunk.")
    lines.append("3. Iterate until the warnings are clean (or attributable to pre-existing issues unrelated to your edits — note those in the PR body if relevant).")
    lines.append("")
    lines.append("Do **not** use the unflagged `POST /reload` for verification — it re-runs the file-rewriting post-load generators and will dirty your working tree with their output.")
    lines.append("")
    lines.append("## Dedup workflow")
    lines.append("")
    lines.append("Before filing any issue:")
    lines.append("")
    lines.append("1. `gh issue list --search \"<file_path>\" --state open --limit 30`")
    lines.append("2. Skim `docs/audits/open_issues.md` for matching entries.")
    lines.append("3. If a match exists with roughly the same finding: **comment on the existing issue, don't file a new one**.")
    lines.append("")
    lines.append("## Wrap-up")
    lines.append("")
    lines.append("After all targets are audited:")
    lines.append("")
    lines.append(f"1. Update `docs/audits/.nightly_coverage.json` for each target: bump `audit_count`, set `last_audited` to `{date_str}`, set `recent_findings` to the count this run produced for that file. For sliced files, append the slice's `[start, end]` to `partial_coverage`. Decay any *other* file's `recent_findings` by half if its `last_audited` is older than {DECAY_DAYS} days.")
    lines.append("2. **State bump rides in a PR. Never direct-push to `main`.**")
    lines.append("   - If there are auto-fix PRs this night: include the `.nightly_coverage.json` diff in the **first** auto-fix PR (or a dedicated coordinating PR — one PR per night carries the state diff).")
    lines.append(f"   - If there are no auto-fix PRs: open a state-bump-only PR titled `nightly-audit({date_str}): state bump` from branch `nightly-audit/{date_str}-state-bump`. Enable auto-merge if available; otherwise leave open for manual merge.")
    if with_report:
        lines.append("3. Write `docs/audits/nightly/<date>/report.md` summarizing what was looked at, what was passed over, and counts by finding type. Include it in the PR.")
    lines.append("")
    lines.append("## Failure handling")
    lines.append("")
    lines.append("If you cannot complete the audit for any reason — context exhaustion, tool failure, unexpected error — **before exiting**:")
    lines.append("")
    lines.append("1. Open a GitHub issue with labels `priority:critical` and `nightly-audit:failure`. Title: `nightly-audit failure (<date>): <short reason>`. Body: what failed, at which step (selector run / pre-reading / per-target audit / wrap-up), and any partial findings.")
    lines.append("2. **Do not update the state file.** Leaving it untouched ensures the next run re-selects the same targets.")
    lines.append("3. Do not open a state-bump-only PR.")
    lines.append("")
    lines.append("## What NOT to do")
    lines.append("")
    lines.append("- Don't reimplement what `modifier_visibility_audit`, `event_magnitude_audit`, `kill_character_audit`, `loc_coverage_audit`, `concept_reference_audit`, `localization_accessor_audit`, `mod_structure_audit` already do.")
    lines.append("- Don't auto-fix anything that touches design intent.")
    lines.append("- Don't audit auto-generated files (the selector already excluded them).")
    lines.append("- Don't audit the Python tooling (out of scope, has its own unittest coverage). Exception: file an issue if a generator visibly breaks while you're working.")
    lines.append("- Don't push directly to `main`.")
    lines.append("")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Nightly mod audit target selector.")
    parser.add_argument("--dry-run", action="store_true", help="Print selection; don't write files.")
    parser.add_argument("--date", help="Override today's date (ISO format YYYY-MM-DD).")
    parser.add_argument("--out-dir", help="Override the output directory.")
    parser.add_argument("--report", action="store_true", help="Instruct the audit prompt to also write docs/audits/nightly/<date>/report.md.")
    args = parser.parse_args(argv)

    if args.date:
        try:
            today = datetime.strptime(args.date, "%Y-%m-%d").date()
        except ValueError:
            print(f"--date must be YYYY-MM-DD, got {args.date!r}", file=sys.stderr)
            return 2
    else:
        today = Date.today()
    date_str = today.isoformat()

    rng = seeded_rng(date_str)
    state = load_state()
    candidates = enumerate_candidates()
    targets = select_targets(candidates, state, today, rng)
    drift_added, drift_orphaned = detect_registry_drift()

    if not targets:
        print("no candidates selected; check SCAN_ROOTS and EXCLUDED_GLOBS", file=sys.stderr)
        return 1

    total_lines = sum(t["lines"] for t in targets)
    area_counts: dict[str, int] = {}
    for t in targets:
        area_counts[t["area"]] = area_counts.get(t["area"], 0) + 1
    area_summary = " ".join(f"{a}:{c}" for a, c in sorted(area_counts.items()))

    out_dir = Path(args.out_dir) if args.out_dir else (OUT_DIR_BASE / date_str)
    prompt_path = out_dir / "prompt.md"
    targets_path = out_dir / "targets.json"

    prompt_text = render_prompt(date_str, targets, drift_added, drift_orphaned, args.report)

    if args.dry_run:
        print(f"[dry-run] date={date_str}  selected={len(targets)}  lines={total_lines}/{LINE_BUDGET}  areas: {area_summary}")
        if drift_added or drift_orphaned:
            print(f"[dry-run] registry drift: added={len(drift_added)} orphaned={len(drift_orphaned)}")
        print()
        for t in targets:
            lr = f"{t['line_range'][0]}-{t['line_range'][1]}" if t["line_range"] else "all"
            print(f"  {t['area']:<35} {t['path']:<70} lines={lr:<12} score={t['score']}")
        print()
        print(f"[dry-run] would write: {prompt_path.relative_to(REPO_ROOT)}")
        print(f"[dry-run] would write: {targets_path.relative_to(REPO_ROOT)}")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    prompt_path.write_text(prompt_text, encoding="utf-8")
    with open(targets_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "date": date_str,
                "total_lines": total_lines,
                "line_budget": LINE_BUDGET,
                "file_cap": FILE_CAP,
                "slice_cap": SLICE_CAP,
                "report_requested": bool(args.report),
                "registry_drift": {
                    "in_registry_not_excluded": drift_added,
                    "excluded_globs_not_in_registry": drift_orphaned,
                },
                "targets": [
                    {
                        "path": t["path"],
                        "line_range": t["line_range"],
                        "lines": t["lines"],
                        "area": t["area"],
                        "docs": t["docs"],
                        "last_audited": t["last_audited"],
                        "audit_count": t["audit_count"],
                        "recent_findings": t["recent_findings"],
                    }
                    for t in targets
                ],
            },
            f,
            indent=2,
        )
        f.write("\n")

    print(f"date={date_str}  selected={len(targets)}  lines={total_lines}/{LINE_BUDGET}  areas: {area_summary}")
    if drift_added or drift_orphaned:
        print(f"registry drift: in-registry-not-excluded={len(drift_added)} excluded-not-in-registry={len(drift_orphaned)}")
    print(f"prompt:  {prompt_path.relative_to(REPO_ROOT)}")
    print(f"targets: {targets_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
