#!/usr/bin/env python3
"""Record a nightly audit's per-file results as a per-run delta file.

Why this exists (and why it changed): the per-file audit state used to live in a
single committed JSON aggregate (docs/audits/.nightly_coverage.json) that every
nightly run mutated. Because two unmerged nightly PRs both rewrote that one file,
they conflicted on GitHub the moment either merged — the "a nightly ran before
the prior PR merged" problem (#202/#204). A custom merge driver can't fix this:
GitHub's mergeability check and web merge button don't run them.

The fix removes the shared merge surface entirely. State is now reconstructed as:

    effective state = frozen baseline  +  replay(per-run delta files, in date order)

- `docs/audits/.nightly_coverage_baseline.json` — committed, immutable snapshot of
  the aggregate as of its `as_of` date. Only re-frozen by an explicit maintenance op.
- `docs/audits/nightly/<run_label>/findings.json` — committed per-run delta written
  by THIS script: `{repo_relative_path: finding_count}` for every target the run
  covered. Paired with that run's already-committed `targets.json` (file list +
  slice bounds + run date), it fully describes the run's effect on state.
- `docs/audits/.nightly_coverage.json` — now a DERIVED, git-ignored cache,
  regenerated by `fold_state()`. Never committed, never the source of truth.

Because each PR now touches only its own dated `findings.json` (a disjoint path),
concurrent nightly PRs no longer conflict — in any merge order.

The replay reuses `update_state` per run, so the recency/decay scoring behavior is
reproduced byte-for-byte from what the old write-time mutation produced.

Usage (unchanged at the call site):
    python3 scripts/nightly_audit_state_update.py \\
        --targets-json docs/audits/nightly/2026-05-29/targets.json \\
        --findings-json -    # JSON on stdin, e.g. {"path/to/file.txt": 2}

    # Or read findings from a file:
    python3 scripts/nightly_audit_state_update.py \\
        --targets-json docs/audits/nightly/2026-05-29/targets.json \\
        --findings-json /tmp/findings.json

    # Dry-run prints what would be written and exits 0 without writing.
    python3 scripts/nightly_audit_state_update.py ... --dry-run

The targets manifest supplies the file list, slice bounds, and run date; the
findings JSON supplies a `{repo_relative_path: finding_count}` map for that
run (omit a path → 0 findings). The script writes `findings.json` next to the
targets manifest and refreshes the git-ignored cache.

Decay: during replay, any file *not* in a given run whose `last_audited` is older
than DECAY_DAYS has its `recent_findings` halved (floor to 0). Mirrors the scoring
decay used by nightly_audit_select.py.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date as Date, datetime, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# Derived, git-ignored cache of the folded aggregate (kept fresh for humans/tools;
# never the source of truth, never committed).
CACHE_FILE = REPO_ROOT / "docs/audits/.nightly_coverage.json"
DEFAULT_STATE_FILE = CACHE_FILE  # backwards-compatible alias for --state-file
# Committed, immutable snapshot the per-run deltas replay on top of.
BASELINE_FILE = REPO_ROOT / "docs/audits/.nightly_coverage_baseline.json"
# Per-run output dirs: docs/audits/nightly/<run_label>/{targets,findings}.json
NIGHTLY_DIR = REPO_ROOT / "docs/audits/nightly"
DECAY_DAYS = 90


def _parse_date(s: str) -> Date:
    return datetime.strptime(s, "%Y-%m-%d").date()


def _load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _coerce_findings(data: dict) -> dict[str, int]:
    if not isinstance(data, dict):
        raise SystemExit("findings JSON must be an object mapping path -> int")
    out: dict[str, int] = {}
    for k, v in data.items():
        if not isinstance(v, int) or v < 0:
            raise SystemExit(f"findings count for {k!r} must be a non-negative int, got {v!r}")
        out[str(k)] = v
    return out


def _load_findings(arg: str) -> dict[str, int]:
    if arg == "-":
        raw = sys.stdin.read()
    else:
        with open(arg, encoding="utf-8") as f:
            raw = f.read()
    if not raw.strip():
        return {}
    return _coerce_findings(json.loads(raw))


def update_state(
    state: dict,
    targets_doc: dict,
    findings: dict[str, int],
    run_date: Date,
) -> tuple[dict, list[str]]:
    """Apply one run's results to `state` in place. Returns (state, change_lines).

    Pure w.r.t. the filesystem — the caller writes. Reused as the per-run replay
    step in fold_state(), so any change here changes both write-time recording
    and read-time reconstruction identically."""
    files: dict[str, dict] = state.setdefault("files", {})
    changes: list[str] = []
    touched: set[str] = set()

    for target in targets_doc.get("targets", []):
        path = target["path"]
        line_range = target.get("line_range")
        finding_count = findings.get(path, 0)
        touched.add(path)

        entry = files.setdefault(path, {})
        prev_count = entry.get("audit_count", 0)
        entry["audit_count"] = prev_count + 1
        entry["last_audited"] = run_date.isoformat()
        entry["recent_findings"] = finding_count
        if line_range is not None:
            partial = entry.setdefault("partial_coverage", [])
            slice_pair = [int(line_range[0]), int(line_range[1])]
            if slice_pair not in partial:
                partial.append(slice_pair)
        changes.append(
            f"  audited: {path} "
            f"(audit_count {prev_count} -> {entry['audit_count']}, "
            f"findings={finding_count}"
            + (f", slice={line_range}" if line_range else "")
            + ")"
        )

    decay_cutoff = run_date - timedelta(days=DECAY_DAYS)
    decayed = 0
    for path, entry in files.items():
        if path in touched:
            continue
        last = entry.get("last_audited")
        if not last:
            continue
        try:
            last_date = _parse_date(last)
        except ValueError:
            continue
        if last_date >= decay_cutoff:
            continue
        old = entry.get("recent_findings", 0)
        if old <= 0:
            continue
        new = old // 2
        if new != old:
            entry["recent_findings"] = new
            decayed += 1
    if decayed:
        changes.append(f"  decayed recent_findings on {decayed} stale entries")

    return state, changes


# --------------------------------------------------------------------------- #
# Baseline + per-run-delta reconstruction
# --------------------------------------------------------------------------- #

def load_baseline() -> dict:
    """Return a deep-ish-copy of the frozen baseline as {"version", "as_of",
    "files"}. Missing/corrupt baseline degrades to an empty cold-start state."""
    if not BASELINE_FILE.exists():
        return {"version": 1, "as_of": None, "files": {}}
    try:
        data = _load_json(BASELINE_FILE)
    except (OSError, json.JSONDecodeError):
        return {"version": 1, "as_of": None, "files": {}}
    # Fresh dicts per entry so replay mutation never touches the loaded object.
    files = {k: dict(v) for k, v in data.get("files", {}).items()}
    for v in files.values():
        if isinstance(v.get("partial_coverage"), list):
            v["partial_coverage"] = [list(p) for p in v["partial_coverage"]]
    return {"version": data.get("version", 1), "as_of": data.get("as_of"), "files": files}


def iter_run_deltas(after: str | None) -> list[dict]:
    """Collect committed per-run deltas (dirs with BOTH targets.json and
    findings.json) whose run date is strictly after `after` (the baseline's
    as_of). Returns dicts sorted by (date, label) for deterministic replay.

    Dirs without findings.json (e.g. historical runs already folded into the
    baseline) are skipped — that's what stops double-counting."""
    deltas: list[dict] = []
    if not NIGHTLY_DIR.is_dir():
        return deltas
    for run_dir in sorted(NIGHTLY_DIR.iterdir()):
        if not run_dir.is_dir():
            continue
        targets_path = run_dir / "targets.json"
        findings_path = run_dir / "findings.json"
        if not (targets_path.is_file() and findings_path.is_file()):
            continue
        try:
            targets_doc = _load_json(targets_path)
            findings = _coerce_findings(_load_json(findings_path))
        except (OSError, json.JSONDecodeError):
            continue
        date_str = targets_doc.get("date")
        if not date_str:
            continue
        if after is not None and date_str <= after:
            # Already incorporated into the baseline; skip to avoid double-count.
            continue
        deltas.append(
            {"date": date_str, "label": run_dir.name, "targets_doc": targets_doc, "findings": findings}
        )
    deltas.sort(key=lambda d: (d["date"], d["label"]))
    return deltas


def fold_state(extra_deltas: list[dict] | None = None) -> dict:
    """Reconstruct the effective per-file state: baseline + replay(deltas).

    `extra_deltas` (same dict shape as iter_run_deltas yields) lets a caller
    preview a not-yet-written run (used by --dry-run) without touching disk."""
    state = load_baseline()
    as_of = state.pop("as_of", None)
    deltas = iter_run_deltas(as_of)
    if extra_deltas:
        deltas = sorted(deltas + list(extra_deltas), key=lambda d: (d["date"], d["label"]))
    for d in deltas:
        update_state(state, d["targets_doc"], d["findings"], _parse_date(d["date"]))
    return state


def write_cache(state: dict, cache_path: Path = CACHE_FILE) -> None:
    """Write the derived aggregate cache (git-ignored). sort_keys keeps it
    stable so a casual `git status` doesn't churn it."""
    payload = {"version": state.get("version", 1), "files": state.get("files", {})}
    with open(cache_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
        f.write("\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--targets-json", required=True, help="Path to the run's targets.json")
    parser.add_argument(
        "--findings-json",
        required=True,
        help="Path to a JSON file mapping {repo-relative path: finding count}, or '-' for stdin.",
    )
    parser.add_argument(
        "--state-file",
        default=str(DEFAULT_STATE_FILE),
        help="Path for the derived cache (default: docs/audits/.nightly_coverage.json, git-ignored).",
    )
    parser.add_argument("--date", help="Override the run date (YYYY-MM-DD). Defaults to targets.json's date, then today.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written; touch nothing.",
    )
    args = parser.parse_args(argv)

    targets_path = Path(args.targets_json)
    cache_path = Path(args.state_file)
    if not targets_path.is_file():
        print(f"error: targets file not found: {targets_path}", file=sys.stderr)
        return 2

    targets_doc = _load_json(targets_path)
    findings = _load_findings(args.findings_json)
    if args.date:
        run_date = _parse_date(args.date)
    elif targets_doc.get("date"):
        run_date = _parse_date(targets_doc["date"])
    else:
        run_date = Date.today()

    # Canonical delta: a finding count for every target the run covered (0 default).
    # Recording 0-finding targets is required — that's what bumps their audit_count
    # and ages them out of the next selection.
    targets = targets_doc.get("targets", [])
    if not targets:
        print("error: targets.json has no targets", file=sys.stderr)
        return 2
    findings_out = {t["path"]: int(findings.get(t["path"], 0)) for t in targets}
    findings_path = targets_path.parent / "findings.json"

    # Preview the run's effect by folding it in (without writing it yet).
    extra = [{
        "date": run_date.isoformat(),
        "label": targets_path.parent.name,
        "targets_doc": targets_doc,
        "findings": findings_out,
    }]
    preview = fold_state(extra_deltas=extra)
    nonzero = {p: c for p, c in findings_out.items() if c}

    print(f"recording run {targets_path.parent.name} (date {run_date.isoformat()}):")
    for t in targets:
        p = t["path"]
        entry = preview["files"].get(p, {})
        slice_note = f", slice={t['line_range']}" if t.get("line_range") else ""
        print(
            f"  {p} (audit_count -> {entry.get('audit_count')}, "
            f"findings={findings_out[p]}{slice_note})"
        )
    print(f"  findings.json -> {findings_path.relative_to(REPO_ROOT) if findings_path.is_relative_to(REPO_ROOT) else findings_path}")
    print(f"  nonzero findings: {nonzero or '{}'}")

    if args.dry_run:
        print("(dry-run: nothing written)")
        return 0

    with open(findings_path, "w", encoding="utf-8") as f:
        json.dump(findings_out, f, indent=2, sort_keys=True)
        f.write("\n")
    # Refresh the git-ignored cache from baseline + all on-disk deltas (now
    # including the one we just wrote).
    write_cache(fold_state(), cache_path)
    print(f"  cache refreshed -> {cache_path.relative_to(REPO_ROOT) if cache_path.is_relative_to(REPO_ROOT) else cache_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
